### ISSUE TITLE
Check if the active view is a MarkdownView

### ISSUE THREAD

**Issue by liamcain** [tadashi-aikawa/obsidian-various-complements-plugin#1]
https://github.com/tadashi-aikawa/obsidian-various-complements-plugin/blob/84641c409f1ed8cec823bce3a95bb74394c45d50/main.ts#L38

This will fail if the active view is not a MarkdownView. You will want to use `getActiveViewOfType` here instead.

Example:

```ts
const activeView = this.app.workspace.getActiveViewOfType(MarkdownView);
if (!activeView) {
  // Do nothing if the command is triggered outside a MarkdownView
  return;
}
```

Similarly, in the `addCommand` hook, you might want to use [checkCallback](https://github.com/obsidianmd/obsidian-api/blob/master/obsidian.d.ts#L415) instead of callback. Then you can provide a condition for the command to be available (e.g. only when the activeView is a MarkdownView)

**Comment by tadashi-aikawa** [comment]
@liamcain 
Thank you for your nice suggestions.😄 I have fixed it 👍
