### ISSUE TITLE
Trivial enhancement suggestion

### ISSUE THREAD

**Issue by chenyukang** [tadashi-aikawa/obsidian-various-complements-plugin#100]
Hi @tadashi-aikawa 

Thank you for your awesome work for this plugin.

I use everyday, and currently I think it's annoying in this scenario: 

![image](https://user-images.githubusercontent.com/230646/157790356-c9d09c90-8bea-4073-9daf-f9ae6794fb7c.png)

You see I finished input the word `Linux` by myself, but the candidate list will not gone.
It seems we must use `ESC` to disappear it.
My suggest enhancement is could we have a options to customize hotkey for it.
Or some option to enable a hook when cursor moved in editor, the candidate list will gone.

**Comment by tadashi-aikawa** [comment]
Hi, @chenyukang. Thank you for your nice suggestion :)

> some option to enable a hook when cursor moved in editor, the candidate list will gone.

I will try to implement it, not as an option but as a default 👍

**Comment by tadashi-aikawa** [comment]
@chenyukang 

I have released to [v5.9.0](https://github.com/tadashi-aikawa/obsidian-various-complements-plugin/releases/tag/5.9.0) 🚀

Please confirm whether it works as you expected.

**Comment by chenyukang** [comment]
@tadashi-aikawa  it works, thank you very much!
