### ISSUE TITLE
FR: Option for case-insentive matching

### ISSUE THREAD

**Issue by chrisgrieser** [tadashi-aikawa/obsidian-various-complements-plugin#101]
Not 100% sure, but it seems that currently, the matching is case-sensitive. At least for my use case, it makes sense to use case-*insensitive* matching, so it would be great to have a toggle for that :)

**Comment by tadashi-aikawa** [comment]
Hi, @chrisgrieser. Matching logic is as follows.

- case-sensitive
  - [Predictable complement](https://tadashi-aikawa.github.io/docs-obsidian-various-complements-plugin/1.%20Features/Predictable%20complement/#matching-logic)
- case-sensitive (only first letter)
  - [Current file complement](https://tadashi-aikawa.github.io/docs-obsidian-various-complements-plugin/1.%20Features/Current%20file%20complement/#matching-logic)
  - [Current vault complement](https://tadashi-aikawa.github.io/docs-obsidian-various-complements-plugin/1.%20Features/Current%20vault%20complement/#matching-logic)
  - [Custom dictionary complement](https://tadashi-aikawa.github.io/docs-obsidian-various-complements-plugin/1.%20Features/Custom%20dictionary%20complement/#matching-logic)
- case-insensitive
  - [Front matter complement](https://tadashi-aikawa.github.io/docs-obsidian-various-complements-plugin/1.%20Features/Front%20matter%20complement/#matching-logic)
  - [Internal link complement](https://tadashi-aikawa.github.io/docs-obsidian-various-complements-plugin/1.%20Features/Internal%20link%20complement/#matching-logic)

Could I need to support all of the following three?

- case-sensitive (only first letter)
  - [Current file complement](https://tadashi-aikawa.github.io/docs-obsidian-various-complements-plugin/1.%20Features/Current%20file%20complement/#matching-logic)
  - [Current vault complement](https://tadashi-aikawa.github.io/docs-obsidian-various-complements-plugin/1.%20Features/Current%20vault%20complement/#matching-logic)
  - [Custom dictionary complement](https://tadashi-aikawa.github.io/docs-obsidian-various-complements-plugin/1.%20Features/Custom%20dictionary%20complement/#matching-logic)

**Comment by chrisgrieser** [comment]
> case-sensitive (only first letter)
[Current file complement](https://tadashi-aikawa.github.io/docs-obsidian-various-complements-plugin/1.%20Features/Current%20file%20complement/#matching-logic)
[Current vault complement](https://tadashi-aikawa.github.io/docs-obsidian-various-complements-plugin/1.%20Features/Current%20vault%20complement/#matching-logic)
[Custom dictionary complement](https://tadashi-aikawa.github.io/docs-obsidian-various-complements-plugin/1.%20Features/Custom%20dictionary%20complement/#matching-logic)

exactly, having an option for case-insensitive matching for those three would be real useful! 🙏

**Comment by tadashi-aikawa** [comment]
@chrisgrieser 
I have released [v7.0.0-beta3](https://github.com/tadashi-aikawa/obsidian-various-complements-plugin/discussions/133#discussion-4104744) 🚀 

I decided not to add options but change the default behaviors.

**Comment by tadashi-aikawa** [comment]
Ah.. sorry, I didn't publish the new version 😅 (done)

**Comment by tadashi-aikawa** [comment]
Released in [v7.0.0](https://github.com/tadashi-aikawa/obsidian-various-complements-plugin/releases/tag/7.0.0) 🚀

**Comment by chrisgrieser** [comment]
thank you 😊

**Comment by OnkelTem** [comment]
@tadashi-aikawa 

Hi!

From the description it follows that only Internal Link Complement are case-insensitive. I disabled it but still I get wrong-cased words in the suggestion list. Why is that?

I asked my question here:
https://github.com/tadashi-aikawa/obsidian-various-complements-plugin/discussions/283

**Comment by tadashi-aikawa** [comment]
@OnkelTem 
I have just answered your question👍
