### ISSUE TITLE
BUG: styles.css should not overwrite default suggestion styling in quick switcher

### ISSUE THREAD

**Issue by lguenth** [tadashi-aikawa/obsidian-various-complements-plugin#105]
Hi, thanks for this very useful plugin!

I noticed a few days ago that my suggestions in the quick switcher looked a bit weird. 

I had started using Supercharged Links and let it add emojis before certain link types, which also helps distinguish notes when browsing.

![220318_113831_screenshot](https://user-images.githubusercontent.com/69049131/158990314-c8c50dc4-fce3-41cc-afcc-45ade5fbdbbd.png)

Your plugin's `styles.css` however (#76), targets the suggestor directly and thus overwrites changes made by other plugins or snippets. https://github.com/tadashi-aikawa/obsidian-various-complements-plugin/blob/main/styles.css#L80

![220318_113600_screenshot](https://user-images.githubusercontent.com/69049131/158990418-870ed2f9-983a-451f-a1b0-7274b9b806c5.png)

Would it be possible to find a workaround for that? :pray:

**Comment by tadashi-aikawa** [comment]
Hi, @lguenth. Thank you for your bug report :)

It seems my mistake, I'll fix it, but I can't confirm it as in your environment. It would be great if you would confirm it after the next release.

**Comment by tadashi-aikawa** [comment]
@lguenth 
I have released to [v5.9.1](https://github.com/tadashi-aikawa/obsidian-various-complements-plugin/releases/tag/5.9.1) 🚀

Please confirm whether it works as you expected.

**Comment by lguenth** [comment]
> @lguenth I have released to [v5.9.1](https://github.com/tadashi-aikawa/obsidian-various-complements-plugin/releases/tag/5.9.1) rocket
> 
> Please confirm whether it works as you expected.

It does! Thank you so much for fixing it this quickly! :rocket: Now it's all back to normal. :)
![grafik](https://user-images.githubusercontent.com/69049131/159010197-208a8033-659e-4ae7-a87a-3befd1f1007b.png)

For future reference: This happened when emojis were prepended to links using Supercharged Links and the corresponding Style Settings options.
![grafik](https://user-images.githubusercontent.com/69049131/159010471-0cf8104d-363d-43a3-8100-143df13e21bd.png)
