### ISSUE TITLE
Question: how I use the plugin that input number like daily format?

### ISSUE THREAD

**Issue by YIRU69** [tadashi-aikawa/obsidian-various-complements-plugin#106]
Firstly, your plugin so power and I'm very grateful to you!
I have a problem when input daily note file.
Imaging when I want to input daily today just like 2022-03-18, then I put "20" and the plugin is working . Next I input number 2, and it means I choose the second choose.
How to reslove the matter?

**Comment by tadashi-aikawa** [comment]
Hi, @YIRU69.

I couldn't reproduce it. Could you show me the gif or mp4 file?

**Comment by YIRU69** [comment]
> Hi, @YIRU69.
> 
> I couldn't reproduce it. Could you show me the gif or mp4 file?

Hi, I have not sitting on my desktop. Maybe the matter is simple to reproduce.
1. I have some files like 2022-03-16.md 2022-03-17.md and so on.
2. I type something on my note just like "20", then the plugin worked, and it show all about "20" files expect what I want to choose file "2022-03-18"
3. So I should continue type number to match it what I want. But when I type "2", it will choose the sencond list.
So how to resolve it ?
Please give me some advise.

**Comment by tadashi-aikawa** [comment]
Thank you for a reply :)
 
> 3. So I should continue type number to match it what I want. But when I type "2", it will choose the sencond list.

It doesn't reproduce and keep suggestions shown. Am I misread about "it will choose the sencond list" ?

https://user-images.githubusercontent.com/9500018/159047298-40df6edb-23fe-4083-8913-f4a37b03ac67.mp4

**Comment by YIRU69** [comment]
Thank you for your reply.
Maybe I understand what it cause.
![演示1](https://user-images.githubusercontent.com/48148292/159107148-d0ef75fb-95e5-45c2-9d33-d81ff3dd069b.gif)
The plugin version that I using have some different version.

**Comment by tadashi-aikawa** [comment]
Don't you install other plugins that add indexes before suggestions and select by pushing the number key?

![image](https://user-images.githubusercontent.com/9500018/159110935-229478c5-19f1-4cf2-9d17-22ca2f7a9179.png)

**Comment by YIRU69** [comment]
Yes, I install other plugin what someone modify by your plugin

**Comment by tadashi-aikawa** [comment]
That means "This problem is not about Various Complements"? I can't support plugins created by other authors.

**Comment by YIRU69** [comment]
Oh, this is my wrong. I'm so sorry about it. And hope you have a good day.

**Comment by tadashi-aikawa** [comment]
No worries 👍
