### ISSUE TITLE
Error about custom dictionary

### ISSUE THREAD

**Issue by YIRU69** [tadashi-aikawa/obsidian-various-complements-plugin#107]
When I use custom dictionary, I get some wrong about it.
![image](https://user-images.githubusercontent.com/48148292/159111594-88932f47-2f06-4f21-b3c4-ee8b75ce1e8e.png)
 My Plugin version is 5.9.1
[dictionary-various-complements.md](https://github.com/tadashi-aikawa/obsidian-various-complements-plugin/files/8308769/dictionary-various-complements.md)
This is my custom dictionary.

![image](https://user-images.githubusercontent.com/48148292/159111649-c22745ab-a29f-4186-9cd6-b1dc5014fd7d.png)
This is my setting!

**Comment by YIRU69** [comment]
The reason that I use other modify version. T.T
Please help me to resolve the problem.

**Comment by tadashi-aikawa** [comment]
@YIRU69 
You should set [Column delimiter](https://tadashi-aikawa.github.io/docs-obsidian-various-complements-plugin/4.%20Options/4.6.%20Custom%20dictionary%20complement/%E2%9A%99%EF%B8%8FColumn%20delimiter/). However it sets `Tab` as default, it is strange that your setting is empty. 🤔 

![image](https://user-images.githubusercontent.com/9500018/159116527-66cf7efa-56cd-4db4-b992-ae66779e5547.png)

**Comment by YIRU69** [comment]
Thanks for your reply. It word when I set [Column delimiter](https://tadashi-aikawa.github.io/docs-obsidian-various-complements-plugin/4.%20Options/4.6.%20Custom%20dictionary%20complement/%E2%9A%99%EF%B8%8FColumn%20delimiter/).
And I should advice it that the plugin should support allow quick select. For example, use number to quick select. Although I have some problem to use it.😀

**Comment by tadashi-aikawa** [comment]
That's good!

And thank you for your feature suggestion. It seems handy, but as you said, it conflicts with the user's input for filtering suggestions. I'll not implement it because some famous editors like VSCode, Vim, and JetBrains IDE don't support them (probably for the same reasons).
