### ISSUE TITLE
Setting Suggestions: Delay & minimal word length

### ISSUE THREAD

**Issue by chrisgrieser** [tadashi-aikawa/obsidian-various-complements-plugin#11]
Hi, thanks for this wonderful plugin, works like a charm already!

Two reasonable settings that come to my mind are
1. a delay before autocomplete appears.
2. a minimal word length, I think right now it's 3?

**Comment by tadashi-aikawa** [comment]
Hi, @chrisgrieser!

> a minimal word length, I think right now it's 3?

It looks good. I'll implement it.

> a delay before autocomplete appears.

Would you tell me why it needs?  Because it uses Obsidian `EditorSuggest` class which doesn't have delay options.

Best regards.

**Comment by chrisgrieser** [comment]
Setting a slight delay might be useful to prevent the autocompletion suggestion popping up when you are simply slowly typing and don't need them. In that case, they block the view, which is rather distracting.

A delay would keep the aspect of automatic suggestion but only display them when you are thinking for a second

**Comment by tadashi-aikawa** [comment]
> In that case, they block the view, which is rather distracting.

That makes sense!

I don't know whether it is possible or not, but I try it :)

**Comment by tadashi-aikawa** [comment]
@chrisgrieser 
I have implemented this feature. Please confirm what is you expected or not.

![image](https://user-images.githubusercontent.com/9500018/142421407-88d78c97-00e0-49a5-b9de-b45ee7134f03.png)
![2021-11-18](https://user-images.githubusercontent.com/9500018/142422085-217a0655-af73-48b6-92b7-c766a0d8e0c6.gif)

**Comment by chrisgrieser** [comment]
Looks fine to me! :)

**Comment by tadashi-aikawa** [comment]
Released as [v1.2.0](https://github.com/tadashi-aikawa/obsidian-various-complements-plugin/releases/tag/1.2.0) 🚀

**Comment by tadashi-aikawa** [comment]
@chrisgrieser 
As I type using the `Various Complements` plugin, I really understand that it is certainly needed, `Delay` option. Thanks!!

(Especially on Vim mode)

**Comment by chrisgrieser** [comment]
Isn't it? :) 
I code in Sublime and I indeed noticed that changing the autocomplete delay there by only 500ms made autocomplete much more useful to me, so I kind of had the feeling that this would help in Obsidian, too!
