### ISSUE TITLE
Feature Request: Remove the `=> ...` when separating display/insert

### ISSUE THREAD

**Issue by chrisgrieser** [tadashi-aikawa/obsidian-various-complements-plugin#110]
for me, it only adds clutter. Maybe use a alternative symbol the the left to indicate that the text displayed is not the text that's going to be inserted?

<img width="297" alt="Screenshot 2022-04-03 11 46 51" src="https://user-images.githubusercontent.com/73286100/161421762-ccb6d037-f16f-4f79-8bef-e1360b5c2c58.png">

**Comment by tadashi-aikawa** [comment]
> Maybe use a alternative symbol the the left to indicate that the text displayed is not the text that's going to be inserted?

Yes. But I can add an option about `separating display/insert symbol` 👍

**Comment by tadashi-aikawa** [comment]
@chrisgrieser 
I have released [v5.11.0](https://github.com/tadashi-aikawa/obsidian-various-complements-plugin/releases/tag/5.11.0) 🚀 

Please confirm whether it works as you expected.

**Comment by chrisgrieser** [comment]
works great!

I set the display text to `⊕` which looks like a plus, without being the regular plus, and is still a unicode character, so it does not stand out too much. Looks fantastic 😊 
Thanks!
<img width="368" alt="Screenshot 2022-04-09 17 36 13" src="https://user-images.githubusercontent.com/73286100/162580911-ac7d16d1-d1b7-45cc-8e25-429df6227d6b.png">
