### ISSUE TITLE
Conflict with Natural Language Dates plugin and @ trigger

### ISSUE THREAD

**Issue by corinnekaryiu** [tadashi-aikawa/obsidian-various-complements-plugin#111]
I believe there is a conflict with using the `@` trigger to insert dates via the Natural Language Dates plugin.

This was mentioned in a previous issue (#47) but still seems to be a problem. If I type `@` and more than 2 characters (ie. `@fri`), the date suggestion box disappears. Emoji shortcodes and slash commands work correctly, however.

If I disable Various Complements, the issue is fixed.

**Comment by tadashi-aikawa** [comment]
Hi, @corinnekaryiu. Thank you for your issue :)

It seems to depend on the order of loading plugins. It only occurs when we install or enable `Natural Language Dates` after `Various Complements`.

To avoid the issue, I'll add an option that doesn't trigger Various complements if it starts with special prefix.

**Comment by tadashi-aikawa** [comment]
Reproduction procedure

1. Install both plugins and enable
2. Disable `Natural Language Dates`
3. Enable `Natural Language Dates`

**Comment by tadashi-aikawa** [comment]
@corinnekaryiu 
I have released [v5.11.0](https://github.com/tadashi-aikawa/obsidian-various-complements-plugin/releases/tag/5.11.0) 🚀 

You should use a new option called [⚙️First characters to disable suggestions](https://tadashi-aikawa.github.io/docs-obsidian-various-complements-plugin/4.%20Options/4.1.%20Main/%E2%9A%99%EF%B8%8FFirst%20characters%20to%20disable%20suggestions/). Please confirm whether it works as you expected.

**Comment by corinnekaryiu** [comment]
Thanks for taking a look at this so quickly, @tadashi-aikawa! The latest update has fixed the issue.
