### ISSUE TITLE
Feature Request: Space key to select suggestion

### ISSUE THREAD

**Issue by dolphinpoint** [tadashi-aikawa/obsidian-various-complements-plugin#112]
I love this plugin! Thanks for making it. What do you think about adding the option to use space key for selecting a suggestion. This would mirror the behaviour of macOS on a system level. What do you think?

**Comment by tadashi-aikawa** [comment]
Hi, @dolphinpoint. Thank you for your PR :)

Do you mean adding a `Space` option to `Select a suggestion key`?
![image](https://user-images.githubusercontent.com/9500018/162569714-c1f03f69-3107-4a86-9ae8-0b5ce4afd18a.png)

**Comment by dolphinpoint** [comment]
Yep! That's exactly what I mean.

**Comment by tadashi-aikawa** [comment]
Thanks! I'll implement it 👍 

By the way, if you use a space key as selecting suggestion, how will you insert space instead?

**Comment by FelipeRearden** [comment]
> Thanks! I'll implement it 👍 

+1 for this feature :) Thanks for bring this feature for us 🎉

 
> By the way, if you use a space key as selecting suggestion, how will you insert space instead?

I'm gonna try to give feedback based on my workflow :)

I only use Custom Dictionaries + alias -> that opens the suggester menu with 3 to 8 suggestions. 
- **TAB** with the Left Hand to select the suggestion;
- **ARROWS** to navigate with the Right Hand;

This way, using SPACE instead of TAB would be 1000 times better than TAB because my left hand thumb is almost touching the SPACE BAR :)

Have a great day 🌞

**Comment by tadashi-aikawa** [comment]
@dolphinpoint @FelipeRearden 
I have released [v6.0.0-beta1](https://github.com/tadashi-aikawa/obsidian-various-complements-plugin/releases/tag/6.0.0-beta1) and [v6.0.0-beta2](https://github.com/tadashi-aikawa/obsidian-various-complements-plugin/releases/tag/6.0.0-beta2) 🚀

The main target of these releases is not this feature. However, it includes this feature. 

If you use BRAT and you want to use it as soon as possible, I hope you can use them until the official release of v6.0.0 🙏

**Comment by FelipeRearden** [comment]
Thank you very much @tadashi-aikawa  !!!!!!!

> If you use BRAT and you want to use it as soon as possible, I hope you can use them until the official release of v6.0.0 🙏

Working **perfect** on version `6.0.0-beta2` on Obsidian `0.14.5`

Thanks again for making one of my favorite plugins 💙 

Have a great day 🌞

**Comment by dolphinpoint** [comment]
Amazing! thanks!!!

**Comment by tadashi-aikawa** [comment]
I have released [v6.0.0](https://github.com/tadashi-aikawa/obsidian-various-complements-plugin/releases/tag/6.0.0) 🚀

**Comment by FelipeRearden** [comment]
> I have released [v6.0.0](https://github.com/tadashi-aikawa/obsidian-various-complements-plugin/releases/tag/6.0.0) 🚀 

Working perfect on version `6.0.0` Obsidian `0.14.6`

Thank you very much @tadashi-aikawa !!!!!!!!!!!!!!!!!!! 💙

**Comment by tristone13th** [comment]
Hi, seems this is not working after the key customization part is updated to the input box rather than the list?

<img width="769" alt="Image" src="https://github.com/user-attachments/assets/90d0ce79-cf0c-439f-a164-b1e9ba6b6bf3" />

FYI, the above configuration is not working.

**Comment by tadashi-aikawa** [comment]
@tristone13th 
You need to set a **whitespace character** rather than the string "Space". (This is because you need to set the value of `event.key` rather than `event.code`)

![Image](https://github.com/user-attachments/assets/22a38788-fb68-42da-98fb-e1c6e7d8a72f)

**Comment by tristone13th** [comment]
@tadashi-aikawa Thanks for the information!

I tried but seems it will break other functions. e.g.,  it will make the ArrowUp and ArrowDown almost unusable, pressing them will always select the current completion item. Could you spare some time to look at it? Thanks.

**Comment by tadashi-aikawa** [comment]
@tristone13th 
Thank you for the additional information. I've confirmed the issue and can reproduce it - this is indeed a bug. I'll address it in a separate issue 👍

**Comment by tadashi-aikawa** [comment]
@tristone13th 
➡ https://github.com/tadashi-aikawa/obsidian-various-complements-plugin/issues/333
