### ISSUE TITLE
Help! How to adjust the width and height of the candidate box？

### ISSUE THREAD

**Issue by gradyhandle** [tadashi-aikawa/obsidian-various-complements-plugin#113]
The CSS setting doesn't contain this command, and I don't know much about java and how to find this element.
Please help!
Thanks!

**Comment by tadashi-aikawa** [comment]
Hi, @gradyhandle :)

Please specify as follows,

```
.various-complements__suggestion-item {
    width: 600px;
    height: 100px;
}
```

![image](https://user-images.githubusercontent.com/9500018/162569845-abbe4853-8f2a-48c9-94ea-18f7ae48d0ce.png)

`Note`
It is not supported as official, so it might be broken after release in the future.

**Comment by gradyhandle** [comment]
Thanks for your reply.
I'm sorry for not making myself clear, what I meant was adjusting the whole suggestion window, including multi-suggestions.
![image](https://user-images.githubusercontent.com/97155298/162582740-21c614d5-f935-4c91-a106-6241897a4e9f.png)
（the red rectangle）
With your tip, I've reread the main.js and tried so many times but failed anyway. Could you please do some help? Thanks again!

**Comment by tadashi-aikawa** [comment]
It is possible to specify as follows,

```
.suggestion {
    max-height: 500px;
}
```

However, the above is not a Various complements style but Obsidian's. So I think there will be side effects.

**Comment by gradyhandle** [comment]
> It is possible to specify as follows,
> 
> ```
> .suggestion {
>     max-height: 500px;
> }
> ```
> 
> However, the above is not a Various complements style but Obsidian's. So I think there will be side effects.

It worked this time. Thank you so much!

As for the side effects, I haven't found any crashes so far, the main inconvenience is that it may hide the content of the current input, momentarily. It doesn't matter though, and that's the perfect solution already. It's a really useful tool. Hope this plugin works better in future updates.
