### ISSUE TITLE
✨Intelligent suggestion prioritization (for FR: factor in frequent/recent use?)

### ISSUE THREAD

**Issue by chrisgrieser** [tadashi-aikawa/obsidian-various-complements-plugin#114]
This is best explained with an example. Right now, these are the 5 complements that get suggested to me when I type "note":
<img width=30% alt="Screenshot 2022-04-09 13 00 50" src="https://user-images.githubusercontent.com/73286100/162569089-046cf2e1-f905-49bc-82e8-def2fff735b3.png">

Now I select for example item number 3 for the note-callout. I do that a couple of times, since I use the callout a lot, and I rarely selected the other items. But even though the note callout is the most frequent and most recent item I selected, it still gets placed as the third item, requiring me to press `arrow down` a few times. 

Would it be possible to make Various complements collect some minor data, so it can factor in frequency & recency for the order of the suggestions? It's a tiny thing, but would speed up the use of the plugin markedly, I think. (Especially when people start using it for callouts)

**Comment by tadashi-aikawa** [comment]
Hi, @chrisgrieser :)

Coincidentally, I have been attempting to create a similar issue to resolve an issue, https://github.com/tadashi-aikawa/obsidian-another-quick-switcher/issues/29 👍

**Comment by tadashi-aikawa** [comment]
This feature is profound and seems fantastic if we achieve the ideal quality. Therefore I will release what includes this as v6.0.0.

So I will release some beta releases. It would be great and helpful for me to try it by using BRAT :)

**Comment by tadashi-aikawa** [comment]
@chrisgrieser 
I have released to [v6.0.0-beta1](https://github.com/tadashi-aikawa/obsidian-various-complements-plugin/releases/tag/6.0.0-beta1) and [v6.0.0-beta2](https://github.com/tadashi-aikawa/obsidian-various-complements-plugin/releases/tag/6.0.0-beta2) 🚀

I have good news about the beta version. We no longer need to use `tadashi-aikawa/obsidian-various-complements-plugin-beta` for testing. Instead, we can use the `tadashi-aikawa/obsidian-various-complements-plugin` (this repository) repository (by using BRAT) 😄 

There are still many limitations, but I hope you can use them :)

**Comment by chrisgrieser** [comment]
hmm, how exactly are they supposed to work? I spammed my complements a bunch of times, and the one I used frequently & recently still didn't show up on top :(

**Comment by tadashi-aikawa** [comment]
Could you show me the debug log displayed after selecting a suggestion? (need to enable  `Show log about performance in a console`)

![](https://user-images.githubusercontent.com/9500018/163706170-9414c23e-b128-4a1f-b264-3ac68e66a99d.png)

**Comment by tadashi-aikawa** [comment]
Ah.. I found better logic. Please wait for the next release 👍

**Comment by tadashi-aikawa** [comment]
Released [v6.0.0-beta3](https://github.com/tadashi-aikawa/obsidian-various-complements-plugin/releases/tag/6.0.0-beta3) 🚀

**Comment by chrisgrieser** [comment]
hmm, still doesn't seem to work properly for me. here is me trying it out & tthe logs created from exactly that video.

https://user-images.githubusercontent.com/73286100/163731383-a5c4ee91-1df9-43c2-9d27-6d2ef46fab1f.mov

[obsidian.md-1650222396699.log](https://github.com/tadashi-aikawa/obsidian-various-complements-plugin/files/8502396/obsidian.md-1650222396699.log)

**Comment by tadashi-aikawa** [comment]
I understood. It doesn't work because it doesn't consider that there are the same aliases.

I'll consider it and will release v6.0.0-beta4 👍

**Comment by tadashi-aikawa** [comment]
@chrisgrieser 
Released [v6.0.0-beta4](https://github.com/tadashi-aikawa/obsidian-various-complements-plugin/releases/tag/6.0.0-beta4). It seems to work correctly.

**Comment by chrisgrieser** [comment]
can confirm, works now 🥳

**Comment by chrisgrieser** [comment]
I think the only obstacle left before it can be part of the regular release is removing this limitation:
> ✋ Limitations
> - User selection histories will clear after rebooting Obsidian or reloading this plugin

**Comment by tadashi-aikawa** [comment]
I want to release v6.0.0 this weekend, but it might be next weekend since I've been busy recently 😵‍💫

**Comment by tadashi-aikawa** [comment]
@chrisgrieser 
Released [v6.0.0-beta6](https://github.com/tadashi-aikawa/obsidian-various-complements-plugin/releases/tag/6.0.0-beta6) 🚀 

**Please back up your `.obsidian/plugins/various-complements/data.json` because it might remove the file unintentionally.**

**Comment by tadashi-aikawa** [comment]
I have released [v6.0.0-beta7](https://github.com/tadashi-aikawa/obsidian-various-complements-plugin/releases/tag/6.0.0-beta7) 🚀

This release will be the last beta version of v6.0.0.

**Comment by tadashi-aikawa** [comment]
I have released [v6.0.0](https://github.com/tadashi-aikawa/obsidian-various-complements-plugin/releases/tag/6.0.0) 🚀
