### ISSUE TITLE
request: absolute path 

### ISSUE THREAD

**Issue by woshitoutouge** [tadashi-aikawa/obsidian-various-complements-plugin#116]
I love internal link complement! Could you add the absolute path for an option?

**Comment by tadashi-aikawa** [comment]
Hi, @woshitoutouge :)

Please trying set `Full` to [⚙️Description on suggestion](https://tadashi-aikawa.github.io/docs-obsidian-various-complements-plugin/4.%20Options/4.2.%20Appearance/%E2%9A%99%EF%B8%8FDescription%20on%20suggestion/). 

(It is not an absolute path but a relative path from the root of a vault.)

![](https://tadashi-aikawa.github.io/docs-obsidian-various-complements-plugin/resources/description-on-suggestion-full.png)

**Comment by woshitoutouge** [comment]
@tadashi-aikawa  Sorry, I didn't make it clear. I mean after the auto complement, the internal link should be like [[folder/filename]], just like when i use "[[" to insert an internal link (if i set the new link format like this ↓)
![image](https://user-images.githubusercontent.com/99337435/164125325-37309885-3fe6-40a3-8f1f-b11629ce246c.png)

**Comment by woshitoutouge** [comment]
The absolute path of the internal link means a lot to me, because it gives extra information about the link. And I know not everyone need this, could you add an option here ↓ so we can choose the link format? 
Various complements is a great tool and i love it
![image](https://user-images.githubusercontent.com/99337435/164132962-3d014b69-6b11-42ee-ab62-967ff3a7bc65.png)

**Comment by tadashi-aikawa** [comment]
OK. I understood 👍 

I'll respect of `New link format option` if possible.

**Comment by woshitoutouge** [comment]
That'd be nice. All the best! @tadashi-aikawa

**Comment by tadashi-aikawa** [comment]
@woshitoutouge 
I have released [v7.0.0-beta4](https://github.com/tadashi-aikawa/obsidian-various-complements-plugin/discussions/133#discussion-4104744) 🚀 

If you use [BRAT](https://github.com/TfTHacker/obsidian42-brat), please confirm whether it works as you expected.

**Comment by woshitoutouge** [comment]
It's amazing! Perfectly match the system link format without extra menu, great work! Thanks a lot!

> @woshitoutouge I have released [v7.0.0-beta4](https://github.com/tadashi-aikawa/obsidian-various-complements-plugin/discussions/133#discussion-4104744) 🚀
> 
> If you use [BRAT](https://github.com/TfTHacker/obsidian42-brat), please confirm whether it works as you expected.

**Comment by tadashi-aikawa** [comment]
Released in [v7.0.0](https://github.com/tadashi-aikawa/obsidian-various-complements-plugin/releases/tag/7.0.0) 🚀
