### ISSUE TITLE
Text gets partly duplicated when typing special character e.g., :, ! and alike

### ISSUE THREAD

**Issue by boriskroeger** [tadashi-aikawa/obsidian-various-complements-plugin#117]
Hello,

I have the effect that text gets partly duplicated when typing special characters such as :, !, -, ...
example:
- text before special character was typed: "hello, this is a test"
- then type ":" right after the text
- text after special character ":" was typed: "hello, this is a ttest" (or similar)

other example:
- I want to create "-->"
- typing "-->" leads to "----"

Unfortunately I can't give you specific hints on when exactly this happens as it seem to happen randomly.
I will add to the issue once I find a more clear way to recreate the effect.

Environment:
obsidian: 14.6
various complements plugin: 5.11.0
System os: Windows 10 (latest patch) or macOS 12.3.1

**Comment by tadashi-aikawa** [comment]
Hi, @boriskroeger :)

If you push the `shift + space` key, it triggers [Predictable complement](https://tadashi-aikawa.github.io/docs-obsidian-various-complements-plugin/1.%20Features/Predictable%20complement/) that might transform to unintentionally result.
