### ISSUE TITLE
Feature Request: API for Dictionary registration

### ISSUE THREAD

**Issue by MSzturc** [tadashi-aikawa/obsidian-various-complements-plugin#118]
Hi,

i've created a custom dictionary to for Advanced Slides syntax. I would like to ship this dictionary with the current build of advanced slides and register it dynamically when the user also has installed various complements plugin. Therefore it would be be cool when provide me such an api for integration

**Comment by tadashi-aikawa** [comment]
Hi, @MSzturc :)

Does that mean it is needed to add the path(URL) to the [Custom dictionary paths](https://tadashi-aikawa.github.io/docs-obsidian-various-complements-plugin/4.%20Options/4.6.%20Custom%20dictionary%20complement/%E2%9A%99%EF%B8%8FCustom%20dictionary%20paths/) via the API? (ex: `addCustomDictionaryPath(path: string)` )

**Comment by MSzturc** [comment]
Yes exactly, with a path like `.obsidian/plugins/obsidian-advanced-slides/autoComplete/dict.md`. I would call it when advanced slides get's initialized so you have to check if the path exists in custom dictionary list

**Comment by tadashi-aikawa** [comment]
OK. LGTM 👍 

Probably, I will add the API such a `ensureCustomDictionaryPath(path: string, state: "present" | "absent")`.

**Comment by tadashi-aikawa** [comment]
@MSzturc 
I have released [v6.1.0-beta1](https://github.com/tadashi-aikawa/obsidian-various-complements-plugin/releases/tag/6.1.0-beta1) 🚀

Please confirm whether it works as you expected via BRAT.

P.S.
This is my first time creating a public API as the Obsidian plugin, so if you know a better implementation, It would be great to hear about it :)

**Comment by MSzturc** [comment]
Awesome, works as expected! The implementation is fine. One think i would introduce with v.6.1 is an API Method `isFeatureSupported(featureName: string) => boolean` With this method every user of the API can check if the installed variousComponents Version supports a feature. This allows a more robust implementation since it could be used to handle version mismatches.

Thx ;-)

**Comment by MSzturc** [comment]
Got a prototype running ;-)

https://user-images.githubusercontent.com/4275753/166114827-b7402f6b-d51e-4ff4-9b8c-70fc4d9b29f8.mov

**Comment by tadashi-aikawa** [comment]
> isFeatureSupported(featureName: string) => boolean 

Thank you! I'll add the function 👍

**Comment by tadashi-aikawa** [comment]
@MSzturc
I have released [v6.2.0-beta1](https://github.com/tadashi-aikawa/obsidian-various-complements-plugin/releases/tag/6.2.0-beta1) 🚀

There is a bit of breaking change. Please fix the code as follows.

```diff
- app.plugins.plugins["various-complements"].ensureCustomDictionaryPath("./your-dictionary.md", "present")
+ app.plugins.plugins["various-complements"].api.ensureCustomDictionaryPath("./your-dictionary.md", "present")
```

**Comment by MSzturc** [comment]
done.

**Comment by tadashi-aikawa** [comment]
I noticed that the current version couldn't have settings for each custom dictionary file. 

![image](https://user-images.githubusercontent.com/9500018/166137228-23fc5cd9-1272-4720-afd1-6e0d6600038b.png)

I think we need to embed the settings in custom dictionary files. So I'll support JSON format as a dictionary file that includes the settings.

**Comment by tadashi-aikawa** [comment]
Ah... it doesn't need settings except for `Caret location symbol after complement` in the case of JSON file format :)

**Comment by MSzturc** [comment]
> I noticed that the current version couldn't have settings for each custom dictionary file.

That would be a nice feature since there are some Settings to get the dict working properly:

```
settings.maxNumberOfSuggestions = 15; //this one is optional but more than 5 feels better using it
settings.enableCustomDictionaryComplement = true; // this could be activated automatically when ensureCustomDictionaryPath was called
settings.insertAfterCompletion = false; //feels better, otherwise you have to move the cursor back after many completion (would be cool when this one would be dict specific
settings.caretLocationSymbolAfterComplement = "<CARET>"; //would be cool if it's dict specific
```

A dict based on a JSON file would make a hierarchically dictionary easier to implement since we wont have to parse a md file

**Comment by tadashi-aikawa** [comment]
> settings.caretLocationSymbolAfterComplement = "<CARET>"; //would be cool if it's dict specific

I'll add this option certainly. However I think that will not add other settings for now.

> A dict based on a JSON file would make a hierarchically dictionary easier to implement since we wont have to parse a md file

Yes. Originally I don't use Custom dictionary (I do now), so I selected the specifications based on the IME dictionary, but already the expressions are pushing the limits 😅

**Comment by tadashi-aikawa** [comment]
@MSzturc 
Mostly done. However, I am afraid of degradation. Therefore it would be great if you try it for a few days after I release it as v6.1.0-beta4 🙏 

https://user-images.githubusercontent.com/9500018/166485820-2f1150fd-8e0b-46e4-901f-62a935639be4.mp4

**Comment by tadashi-aikawa** [comment]
Support properties.

```json
{
  "caretSymbol": "[[CARET]]",
  "ignoreSpaceAfterCompletion": true,
  "words": [
    { "value": "custom dictionary1" },
    { "value": "custom dictionary2", "description": "hogehoge" },
    { "value": "custom dictionary3", "aliases": ["w3", "word3"] },
    { "value": "```json\n[[CARET]]\n```", "displayed": "code-json" }
  ]
}
```

> settings.insertAfterCompletion = false; //feels better, otherwise you have to move the cursor back after many completion (would be cool when this one would be dict specific
> settings.caretLocationSymbolAfterComplement = "<CARET>"; //would be cool if it's dict specific

**Comment by MSzturc** [comment]
Uhhh... looks neat! Will test it tomorrow and give you feedback. Thx

**Comment by MSzturc** [comment]
Will v6.1.0-beta4 support dict hierarchy (as described in #119 )?

**Comment by tadashi-aikawa** [comment]
No it doesn't because of https://github.com/tadashi-aikawa/obsidian-various-complements-plugin/issues/119#issuecomment-1114161098.

**Comment by tadashi-aikawa** [comment]
@MSzturc 
I have released [v6.1.0-beta4](https://github.com/tadashi-aikawa/obsidian-various-complements-plugin/releases/tag/6.1.0-beta4) 🚀

**Comment by MSzturc** [comment]
Played a bit with it! Works like intended! Thx man

**Comment by tadashi-aikawa** [comment]
@MSzturc
Thanks for conforming!

By the way, can I remove the API of this issue by any chance? Because `Advanced Slides for Obsidian` seems not to use this feature.

Best regards.

**Comment by MSzturc** [comment]
Yeah, if you want you may remove it. I experimented yesterday a bit with it and i was not comfortable with my dictionary without the hierarchy feature, Advanced Slides is too complex for a basic auto complete, so i hacked an own suggester... but i have to rewrite it after its stable.. the code is too complex

**Comment by tadashi-aikawa** [comment]
OK! Thanks for reply 👍
