### ISSUE TITLE
FR: Custom Autocomplete Dictionary

### ISSUE THREAD

**Issue by chrisgrieser** [tadashi-aikawa/obsidian-various-complements-plugin#12]
It would be extremely useful if you can customize the words available via autocomplete. Right now, it takes only the words occurring in the same note already, I believe?

You could e.g. add a word list with common long words from your field of study and have them autocomplete, which would be very useful to academics and students.

--

btw, You should set up a Donation button! Your plugins are so great, I'd donate if you had one :)

**Comment by tadashi-aikawa** [comment]
> it takes only the words occurring in the same note already, I believe?

Yes.

> You could e.g. add a word list with common long words from your field of study and have them autocomplete, which would be very useful to academics and students.

I agree. I'll try it :)

**Comment by tadashi-aikawa** [comment]
@chrisgrieser 
I have Implemented custom dictionaries!

![image](https://user-images.githubusercontent.com/9500018/142438148-afb5cef5-d291-4ee6-a65e-7185a3d3ceb0.png)

https://user-images.githubusercontent.com/9500018/142438692-6ba731e8-2032-42de-94d0-09a5e5df3edb.mp4

**Comment by chrisgrieser** [comment]
that looks great! :) 
Now I just need to find good wordlists^^

**Comment by tadashi-aikawa** [comment]
Released as [v1.2.0](https://github.com/tadashi-aikawa/obsidian-various-complements-plugin/releases/tag/1.2.0) 🚀
