### ISSUE TITLE
[Feature Request] Executre Obsidian commands

### ISSUE THREAD

**Issue by emisjerry** [tadashi-aikawa/obsidian-various-complements-plugin#120]
There's a core plujgin-slash command-when we press slash (/) can invokes a Obsidian command to execute.

But in Chinese/Japanese/Korean environment, these commands replaced by language strings, and there are hard to input. For example, "/pin" changed to "/釘選" in Traditional Chinese environment.

Could it be possible that you provide a trigger command, such as dot command? Triggered by pressing a dot (.) in the begining of line, and execute the corresping Obsidian commands?

For example:

.pin => Execurte Pin command
.pdf => Execute export PDF command?
etc.

I think it will be very useful to let us expand the commands and very convinent to execute commands.

Thanks.

**Comment by tadashi-aikawa** [comment]
Hi, @emisjerry :)

Thank you for your FR, but I'll not implement that feature because this plugin is for auto-complete, not for executing a command.

Kind regards.

**Comment by emisjerry** [comment]
What a pity...

**Comment by emisjerry** [comment]
i found a solution: using command alias to add alias to commands. Then i can use slash command to invoke it.
