### ISSUE TITLE
Toggle mode for status bar toggler

### ISSUE THREAD

**Issue by aubreyz** [tadashi-aikawa/obsidian-various-complements-plugin#122]
Currently this toggles between prefix and partial. 

It would be nice to have this as a three way toggle instead
Prefix
Partial
Off (manual triggering mode)

That would provide an easy intuitive way to switch between different modes depending on what work is being done. It would also provide a good visual clue as to whether triggering is active at all (or might need four modes).

**Comment by tadashi-aikawa** [comment]
Hi, @aubreyz. Thank you for your FR :)

> It would be nice to have this as a three way toggle instead

That toggle is only for [Match strategy](https://tadashi-aikawa.github.io/docs-obsidian-various-complements-plugin/5.%20Terms/%F0%9F%96%BC%EF%B8%8FMatch%20strategy/). So If I am going to add a feature, I will add a [Complement automatically](https://tadashi-aikawa.github.io/docs-obsidian-various-complements-plugin/4.%20Options/4.1.%20Main/%E2%9A%99%EF%B8%8FComplement%20automatically/) toggle just like a [Toggle Match strategy](https://tadashi-aikawa.github.io/docs-obsidian-various-complements-plugin/3.%20Commands/%F0%9F%8E%AEToggle%20Match%20strategy/). Would it satisfy your demands?

**Comment by aubreyz** [comment]
That sounds a great solution. Thank you for your great work. Need a very short button title maybe auto/manual

I also think while doing that - the status bar needs uncluttering (for those who want it) by removing the various static entries (counts of words etc) unless there is already a toggle I have not seen. I suppose these counts could also be turned into active switches to toggle various types of matches -- links etc, which would also be nice (maybe bolded count if on).

**Comment by tadashi-aikawa** [comment]
[Show Indexing status](https://tadashi-aikawa.github.io/docs-obsidian-various-complements-plugin/4.%20Options/4.2.%20Appearance/%E2%9A%99%EF%B8%8FShow%20Indexing%20status/) option can hide [Indexing status](https://tadashi-aikawa.github.io/docs-obsidian-various-complements-plugin/5.%20Terms/%F0%9F%96%BC%EF%B8%8FIndexing%20status/) on footer items.

> I suppose these counts could also be turned into active switches to toggle various types of matches -- links etc

It looks good. If some people need this feature, I'll implement it 👍 (not for now)

**Comment by aubreyz** [comment]
> [Show Indexing status](https://tadashi-aikawa.github.io/docs-obsidian-various-complements-plugin/4.%20Options/4.2.%20Appearance/%E2%9A%99%EF%B8%8FShow%20Indexing%20status/) option can hide [Indexing status](https://tadashi-aikawa.github.io/docs-obsidian-various-complements-plugin/5.%20Terms/%F0%9F%96%BC%EF%B8%8FIndexing%20status/) on footer items.

I missed that one 👍

**Comment by tadashi-aikawa** [comment]
@aubreyz 
Added in [v7.0.0-beta8](https://github.com/tadashi-aikawa/obsidian-various-complements-plugin/discussions/133) 🚀

**Comment by aubreyz** [comment]
I love it. Great to be able to easily see the status and switch the plugin off completely when it is getting in the way. Works well.

**Comment by tadashi-aikawa** [comment]
Released in [v7.0.0](https://github.com/tadashi-aikawa/obsidian-various-complements-plugin/releases/tag/7.0.0) 🚀
