### ISSUE TITLE
Feature Request: Only suggest words longer than X characters

### ISSUE THREAD

**Issue by Ampa** [tadashi-aikawa/obsidian-various-complements-plugin#125]
Suggestions are only really useful if they save keypresses. I find that suggestions for short words (3 or 4 characters) actually slow down my typing.

**Could we have a slider so specify the minimum length of words that should be suggested?**

Example… I specify a minimum suggestion length of 5 characters.

I type 'car'.
I don't want suggestions of: cart, card, cars, carp
I do want suggestions of: cargo, carol, carry, carrying etc.

Secondly, **could we specify a sort order for the suggestions, with longer words at the top of the list?**
Again, useful as this saves the largest number of key strokes.

Thank you for your consideration, and time writing the plugin.

**Comment by aubreyz** [comment]
Indeed +1 to both suggestions

**Comment by tadashi-aikawa** [comment]
Hi, @Ampa. Thank you for your FR :)

First of all, Could you tell me your settings by [this command](https://tadashi-aikawa.github.io/docs-obsidian-various-complements-plugin/3.%20Commands/%F0%9F%8E%AECopy%20plugin%20settings/)?

**Comment by Ampa** [comment]
Here are my setting. Not sure that I've changed any from default...

{
    "version": "6.0.0",
    "mobile": false,
    "settings": {
        "strategy": "english-only",
        "matchStrategy": "prefix",
        "maxNumberOfSuggestions": 5,
        "maxNumberOfWordsAsPhrase": 3,
        "minNumberOfCharactersTriggered": 0,
        "minNumberOfWordsTriggeredPhrase": 1,
        "complementAutomatically": true,
        "delayMilliSeconds": 0,
        "disableSuggestionsDuringImeOn": false,
        "insertAfterCompletion": true,
        "firstCharactersDisableSuggestions": ":/^",
        "showMatchStrategy": true,
        "showIndexingStatus": true,
        "descriptionOnSuggestion": "Short",
        "selectSuggestionKeys": "Enter",
        "additionalCycleThroughSuggestionsKeys": "None",
        "openSourceFileKey": "None",
        "propagateEsc": false,
        "enableCurrentFileComplement": true,
        "onlyComplementEnglishOnCurrentFileComplement": false,
        "enableCurrentVaultComplement": true,
        "includeCurrentVaultPathPrefixPatterns": "",
        "excludeCurrentVaultPathPrefixPatterns": "",
        "includeCurrentVaultOnlyFilesUnderCurrentDirectory": false,
        "enableCustomDictionaryComplement": false,
        "customDictionaryPaths": "https://raw.githubusercontent.com/first20hours/google-10000-english/master/google-10000-english-no-swears.txt",
        "columnDelimiter": "Tab",
        "customDictionaryWordRegexPattern": "",
        "delimiterToHideSuggestion": "",
        "delimiterToDivideSuggestionsForDisplayFromInsertion": "",
        "caretLocationSymbolAfterComplement": "",
        "displayedTextSuffix": " => ...",
        "enableInternalLinkComplement": true,
        "suggestInternalLinkWithAlias": true,
        "excludeInternalLinkPathPrefixPatterns": "",
        "enableFrontMatterComplement": true,
        "frontMatterComplementMatchStrategy": "inherit",
        "insertCommaAfterFrontMatterCompletion": false,
        "showLogAboutPerformanceInConsole": false,
        "selectionHistoryTree": null
    }
}

**Comment by Ampa** [comment]
>  it would be helpful to create another issue :)

Done!

**Comment by Glint-Eye** [comment]
> Suggestions are only really useful if they save keypresses. I find that suggestions for short words (3 or 4 characters) actually slow down my typing.
> 
> **Could we have a slider so specify the minimum length of words that should be suggested?**
> 
> Example… I specify a minimum suggestion length of 5 characters.
> 
> I type 'car'. I don't want suggestions of: cart, card, cars, carp I do want suggestions of: cargo, carol, carry, carrying etc.
> 
> Secondly, **could we specify a sort order for the suggestions, with longer words at the top of the list?** Again, useful as this saves the largest number of key strokes.
> 
> Thank you for your consideration, and time writing the plugin.

I also agree with both suggestions.

**Comment by tadashi-aikawa** [comment]
@Ampa @aubreyz @Glint-Eye 
I have released [v7.0.0-beta5](https://github.com/tadashi-aikawa/obsidian-various-complements-plugin/discussions/133#discussion-4104744) 🚀

If you use [BRAT](https://github.com/TfTHacker/obsidian42-brat), please confirm whether it works as you expected.

**Comment by tadashi-aikawa** [comment]
Released in [v7.0.0](https://github.com/tadashi-aikawa/obsidian-various-complements-plugin/releases/tag/7.0.0) 🚀

**Comment by Ampa** [comment]
Thank you for this addition.

It is working well for me (and I hope for others too!).

**Comment by colinbr96** [comment]
If anyone is looking for this setting, it's called "Min number of characters for indexing" under **Current file complement** and **Current vault complement**. Personal dictionaries seem to override this setting, so either disable them or make your own with exclusively longer words.
