### ISSUE TITLE
Algorithm for Intelligent suggestion - possible tweaking

### ISSUE THREAD

**Issue by aubreyz** [tadashi-aikawa/obsidian-various-complements-plugin#131]
Intelligent suggestion works great!

However I wonder if the algorithm should be tweaked. 
https://tadashi-aikawa.github.io/docs-obsidian-various-complements-plugin/1.%20Features/Intelligent%20suggestion%20prioritization/

I agree that recent use should factor in, but
a) it is less sensible that it is a particular time-scale. If abracadabra is the best suggestion to abr because every time I type abr that is what I want, then it makes no difference whether the last use was 5 minutes ago or 5 weeks ago. 

I'd suggest if possible that "last use" should get weighted much higher than the exact time of last use. 

b) A bigger issue is why the data (i.e selected times) should be cleared within 30 days (and why it should be cleared ever). Not sure what a good reason for this is? I don't want it forgotten if it was the main choice for that trigger phrase. The bonuses of less than 1 for older use seems more than enough to prevent a score from ever being changed if I suddenly find a new field of work. 

I would be inclined to leave the bonus as it with a 0.25 factor for >30 days, is but NOT make the selected expire. 

So that something used 100 days ago would be retained if it is the best match

**Comment by tadashi-aikawa** [comment]
Hi, @aubreyz.

> I'd suggest if possible that "last use" should get weighted much higher than the exact time of last use.

I agree with you 👍 

> why the data (i.e selected times) should be cleared within 30 days (and why it should be cleared ever).

`Intelligent suggestion prioritization` saves the history to `data.json` stored in the plugin directory. If we use Obsidian sync, Obsidian synchronizes `data.json` with other machines via the network. Therefore I don't want to increase history data as much as possible. That is the reason.

However, I know that there is anyone like you who want to remember more than 30 days. So I'll add an option to specify the period instead of `Within 30 days`.

**Comment by tadashi-aikawa** [comment]
@aubreyz 

> I'd suggest if possible that "last use" should get weighted much higher than the exact time of last use.

Released in [v7.2.0-beta1](https://github.com/tadashi-aikawa/obsidian-various-complements-plugin/discussions/161#discussion-4308693) 🚀 

If you use [BRAT](https://github.com/TfTHacker/obsidian42-brat), please confirm whether it works as you expected.

**Comment by tadashi-aikawa** [comment]
@aubreyz 

> A bigger issue is why the data (i.e selected times) should be cleared within 30 days (and why it should be cleared ever). 

> https://github.com/tadashi-aikawa/obsidian-various-complements-plugin/discussions/159#discussioncomment-3359643

Released in [v7.2.0-beta2](https://github.com/tadashi-aikawa/obsidian-various-complements-plugin/releases/tag/7.2.0-beta2) 🚀 

If you use [BRAT](https://github.com/TfTHacker/obsidian42-brat), please confirm whether it works as you expected.

**Comment by aubreyz** [comment]
Thank you for this. I am away from my obsidian over the next week, and will try the beta when back home. Sound good

**Comment by tadashi-aikawa** [comment]
I have released in [v7.2.0](https://github.com/tadashi-aikawa/obsidian-various-complements-plugin/releases/tag/7.2.0) 🚀 (Because Obsidian v16.0 was released, and had some bugs)
