### ISSUE TITLE
FR: suggestion board doesn't disappear when press space (Chinese strategy)

### ISSUE THREAD

**Issue by woshitoutouge** [tadashi-aikawa/obsidian-various-complements-plugin#136]
version: 7.0.0-beta 6
Chinese strategy: press space many times but the suggestion board still exist.
expect result: press space then the suggestion board disappear as default stragety 

![image](https://user-images.githubusercontent.com/99337435/171661675-c26a0ec3-0ffc-4b60-994c-ee819952bce9.png)

**Comment by tadashi-aikawa** [comment]
Thank you for your bug report, @woshitoutouge :)

I have fixed it in `v7.0.0-beta7` 🚀

**Comment by woshitoutouge** [comment]
so efficient!
