### ISSUE TITLE
Chinese strategy doesn't work as expected

### ISSUE THREAD

**Issue by emisjerry** [tadashi-aikawa/obsidian-various-complements-plugin#137]
Hi, i have stored cedict_ts.u8 in the root, but it always displayed the warning message and i cannot input the compments words.
Is trhere any wrong in my environment?

![image](https://user-images.githubusercontent.com/131511/172283375-b2d1832d-715d-454a-b75c-fd895970e7e8.png)

![image](https://user-images.githubusercontent.com/131511/172283396-1196c557-1480-429e-bb36-47fd89816f1c.png)

**Comment by tadashi-aikawa** [comment]
Hi, @emisjerry :)

What OS do you use? (Windows/Mac/Android/iOS/iPadOS)

**Comment by tadashi-aikawa** [comment]
> it always displayed the warning message

It displays a warning no matter ｗhether`cedict_ts.u8` exists or not. 

If there is not `cedict_ts.u8` in your vault root, you can see the following error toast.

![image](https://user-images.githubusercontent.com/9500018/172290514-e06c305c-6769-44fa-9726-c27a86c50753.png)

**Comment by emisjerry** [comment]
Windows 11, 22H2

**Comment by tadashi-aikawa** [comment]
@emisjerry 
Does it display the error toast?

![](https://user-images.githubusercontent.com/9500018/172290514-e06c305c-6769-44fa-9726-c27a86c50753.png)

**Comment by emisjerry** [comment]
No, there's no warning at the startup. So i think it's the IME issue?
How can i activate the plugin's complements popup? For next example that comes from cedict_ts.u8:

一一 一一 [yi1 yi1] /one by one/one after another/
一一對應 一一对应 [yi1 yi1 dui4 ying4] /one-to-one correspondence/

If i input "一一" it will popup complements? But i dont see any popup.

**Comment by tadashi-aikawa** [comment]
In my environment. Is it what you expected?

![image](https://user-images.githubusercontent.com/9500018/172294225-3c6de872-85ff-464b-88b8-1758be0031c2.png)

**Comment by tadashi-aikawa** [comment]
Could you tell me your settings by [this command](https://tadashi-aikawa.github.io/docs-obsidian-various-complements-plugin/3.%20Commands/%F0%9F%8E%AECopy%20plugin%20settings/)?

**Comment by emisjerry** [comment]
Yes. But i cannot see the popup. 

Your file contain the string, it will pop. Right? 
But there's many phrases starting "一", 

like 一下 一下 [yi1 xia4] /(used after a verb) 

How to pop these phrases? 
cedict_ts.u8 line 258

**Comment by emisjerry** [comment]
Here it is:

{
    "version": "7.0.0",
    "mobile": false,
    "settings": {
        "strategy": "chinese",
        "matchStrategy": "prefix",
        "maxNumberOfSuggestions": 5,
        "maxNumberOfWordsAsPhrase": 2,
        "minNumberOfCharactersTriggered": 0,
        "minNumberOfWordsTriggeredPhrase": 1,
        "complementAutomatically": true,
        "delayMilliSeconds": 0,
        "disableSuggestionsDuringImeOn": false,
        "insertAfterCompletion": true,
        "firstCharactersDisableSuggestions": ":/^",
        "showMatchStrategy": true,
        "showComplementAutomatically": true,
        "showIndexingStatus": true,
        "descriptionOnSuggestion": "Short",
        "selectSuggestionKeys": "Enter",
        "additionalCycleThroughSuggestionsKeys": "None",
        "disableUpDownKeysForCycleThroughSuggestionsKeys": false,
        "openSourceFileKey": "None",
        "propagateEsc": false,
        "enableCurrentFileComplement": true,
        "currentFileMinNumberOfCharacters": 0,
        "onlyComplementEnglishOnCurrentFileComplement": false,
        "enableCurrentVaultComplement": false,
        "currentVaultMinNumberOfCharacters": 0,
        "includeCurrentVaultPathPrefixPatterns": "",
        "excludeCurrentVaultPathPrefixPatterns": "",
        "includeCurrentVaultOnlyFilesUnderCurrentDirectory": false,
        "enableCustomDictionaryComplement": true,
        "customDictionaryPaths": "https://raw.githubusercontent.com/first20hours/google-10000-english/master/google-10000-english-no-swears.txt\n000-Index/!dict.json",
        "columnDelimiter": "Tab",
        "customDictionaryWordRegexPattern": "",
        "delimiterToHideSuggestion": "",
        "delimiterToDivideSuggestionsForDisplayFromInsertion": "",
        "caretLocationSymbolAfterComplement": "",
        "displayedTextSuffix": " => ...",
        "enableInternalLinkComplement": true,
        "suggestInternalLinkWithAlias": false,
        "excludeInternalLinkPathPrefixPatterns": "",
        "enableFrontMatterComplement": true,
        "frontMatterComplementMatchStrategy": "inherit",
        "insertCommaAfterFrontMatterCompletion": false,
        "showLogAboutPerformanceInConsole": false,
        "selectionHistoryTree": null
    }
}

**Comment by tadashi-aikawa** [comment]
Thanks. And could you show me [Status bar](https://tadashi-aikawa.github.io/docs-obsidian-various-complements-plugin/5.%20Terms/%F0%9F%96%BC%EF%B8%8FStatus%20bar/) capture?

**Comment by emisjerry** [comment]
![image](https://user-images.githubusercontent.com/131511/172295272-487aad58-ad14-47e0-ae8a-1a4893e418ef.png)

**Comment by emisjerry** [comment]
I use Windows 11 default Traditional input method 倉頡 to test. This IME has its own suggestion window. I'm not sure will it be a problem or not?

![image](https://user-images.githubusercontent.com/131511/172295867-89773eb6-089c-44b1-9fec-527ef4f05701.png)

**Comment by tadashi-aikawa** [comment]
Hmm... it seems correct. I adapted your settings directly to my environment, and it works fine.

![2022-06-07](https://user-images.githubusercontent.com/9500018/172296630-d8f780ca-2609-4d34-a9e5-002b41b6ba3e.gif)

My environment is

- WIndows10
- Windows IME
- Obsidian v0.14.15

**Comment by tadashi-aikawa** [comment]
That is a Popup. Your problem is not "popup is not shown" but "popup is hidden by suggestions of IME"?

![image](https://user-images.githubusercontent.com/9500018/172296953-a7e9e0a0-95ec-47a8-8722-b07f85fbeeaa.png)

**Comment by emisjerry** [comment]
No, you popup still does not contains all the phrases. It dipslayed phrases list in the current file only.

**Comment by tadashi-aikawa** [comment]
It would be helpful to show me the following items because I don't have Windows 11 and a Chinese IME environment.

- The video that reproduced it
- Text contents in the file
- Expected behavior (suggestions)

**Comment by emisjerry** [comment]
Thanks. I'll record the screen when i'm avaiable. 

Here is the screen snapshot. A new file, using another IME. I'm using the v0.14.15 insider edition.

![image](https://user-images.githubusercontent.com/131511/172299563-b81aedab-0a37-40f9-af85-ce62c4eb2c8c.png)

**Comment by tadashi-aikawa** [comment]
Thank you for your sharing :)

> using another IME.

As you said, it seems to be a problem with IME (Obsidian / Code mirror). If so, there is nothing to do I can 😢

@tyf2018 @lbgws2
If you see this thread and have information to resolve this issue, it would be great to share it 🙏

**Comment by emisjerry** [comment]
But the links suggestions can be found. Maybe you can write some messages after reading cedict_ts.u8 or after displaying the links suggestions? 

I can open DevTools to see what messages by your console.log.

**Comment by tadashi-aikawa** [comment]
@emisjerry 
Do you want suggestions not only in the current file but also in current vault?

If so, please enable [Enable Current vault complement](https://tadashi-aikawa.github.io/docs-obsidian-various-complements-plugin/4.%20Options/4.5.%20Current%20vault%20complement/%E2%9A%99%EF%B8%8FEnable%20Current%20vault%20complement/) option.

**Comment by emisjerry** [comment]
Here is the situation:

1. I input "一"
2. Obsidian displays two file links (一鍵錄影.md and 一文...md) which filename starts with "一" by your plugin
3. But there's no any phrases come from cedict_ts.u8, like "一下", "一一" or "一一對應", ...

The Chinese strategy should list these phrases in cedict_ts.u8. Or i need do any setting?

**Comment by emisjerry** [comment]
Same new file, if i inputed "一起", then the popup was different. The second file "一文带你掌握Vue3新特性，再也不怕面试官啦~.md" not in the popup. These tests all doing a fresh new Obsidian startup.

![image](https://user-images.githubusercontent.com/131511/172307471-bf167a3a-3150-4990-90b0-788f5a887482.png)

**Comment by tadashi-aikawa** [comment]
> The Chinese strategy should list these phrases in cedict_ts.u8. Or i need do any setting?

Various complements does **not** use `cedict_ts.u8` to show suggestions but uses it only to tokenize Chinese sentence.

**Comment by tadashi-aikawa** [comment]
> The second file "一文带你掌握Vue3新特性，再也不怕面试官啦~.md" not in the popup

I couldn't reproduce it with your settings 🤔 

![image](https://user-images.githubusercontent.com/9500018/172318973-8b4fc527-45c5-4f21-b499-253fb45e37f9.png)

**Comment by tyf2018** [comment]
Hi， @tadashi-aikawa 
The recognition and support of Chinese in version 7.0 has met my expectations. In addition, I am using Coyote Mill input method, and I have not encountered the above problem so far.
Operating system: windows 10
obsidian: 0.14.15

However, the problem I am currently experiencing is that after updating the plugin to V7.0, if the number of custom dictionaries is too large and the size of the dictionary files is large (about 800Mb in total), it will cause Obsidian to crash. After reducing the number of custom dictionaries, it is back to normal.

**Comment by emisjerry** [comment]
I've fixed the result. Your plugin works well.

FIX: "Min number of characters for trigger / It uses a default value of Strategy if set O."
This setting must be 0. After changing it back to 0, there's two file links and "一起" inserted text.

Ha, it turns out I misunderstood this Chinese strategy... So maybe README should be mentioned so that others don't think it can be selected like a dictionary.

**Comment by emisjerry** [comment]
Sorry to have wasted your precious time.

**Comment by tadashi-aikawa** [comment]
Thank you for your reply, @tyf2018 :)

> if the number of custom dictionaries is too large and the size of the dictionary files is large (about 800Mb in total)

Does it occur only after v7.0.0? If there is no problem in v6.x, I want to find the reason and fix it if possible.

**Comment by tadashi-aikawa** [comment]
@emisjerry 
 
> I've fixed the result. Your plugin works well.

Good 👍 

`cedict_ts.u8` is a dictionary file, so I think that is not intuition and has a risk to occur misunderstanding.

[The document](https://tadashi-aikawa.github.io/docs-obsidian-various-complements-plugin/4.%20Options/4.1.%20Main/%E2%9A%99%EF%B8%8FStrategy/) already describes it, but it might be better to emphasize it in settings 👍 

> This options decides a tokenizer logic.

**Comment by tyf2018** [comment]
> Does it occur only after v7.0.0? If there is no problem in v6.x
Yes，only after v7.0.0 . There is no problem in v6.x

**Comment by tadashi-aikawa** [comment]
@tyf2018 
Mmm... 

> it will cause Obsidian to crash. 

When did Obsidian crash? (load dictionary files / show suggestions)

**Comment by tyf2018** [comment]
> When did Obsidian crash?

load dictionary files

**Comment by tadashi-aikawa** [comment]
That's strange 🤔 I didn't change the code about loading/indexing dictionary files.

**Comment by tadashi-aikawa** [comment]
> But it doesn't matter, now I reduced the number of custom dictionaries and the file size and it is back to normal now.

Glad to hear that :)
