### ISSUE TITLE
Feature Request: tab *and* return should accept a completion

### ISSUE THREAD

**Issue by chrisgrieser** [tadashi-aikawa/obsidian-various-complements-plugin#138]
only a small Quality-of-Life feature:
right now, we have options to choose tab, return (and various other) keys accept a suggested completion, but from many other apps, that accept both, I am used to sometimes use enter, sometimes tab, depending on where my fingers currently are.

Would it be possible to add an option to have both, tab and return, both be used as key for accepting completions?

**Comment by tadashi-aikawa** [comment]
Hi, @chrisgrieser :)

It doesn't move to the caret symbol until "reload custom dictionaries" runs if it adds words from "Add a word to a custom dictionary dialog" 👍

**Comment by chrisgrieser** [comment]
fantastic, thank you so much 😊

**Comment by tadashi-aikawa** [comment]
@chrisgrieser 
I have released it in [v9.0.0-beta1](https://github.com/tadashi-aikawa/obsidian-various-complements-plugin/releases/tag/9.0.0-beta1) 🚀 

I would appreciate it if you could check it out before the official release.
