### ISSUE TITLE
[Feature Request] Option to only use Tokens from the Custom Autocomplete Dictionary

### ISSUE THREAD

**Issue by FelipeRearden** [tadashi-aikawa/obsidian-various-complements-plugin#14]
Hello @tadashi-aikawa !!!!!!

I'd like to suggest an option in the Settings to only use the words in the custom dictionary 

`From README.md`

> Auto Complete
> It complements the text with tokens that exists in a current file.

In my case I just want to complement the text with tokens from the Custom Autocomplete Dictionary and NOT from the current file :)

---

Let me know if you need more information !

Thanks for reading this :)

I wish you a fantastic day!

**Comment by tadashi-aikawa** [comment]
Hi, @FelipeRearden. Thank you for your Feature Request!

> I'd like to suggest an option in the Settings to only use the words in the custom dictionary

It looks good. I'll add a new option 👍

**Comment by FelipeRearden** [comment]
> Hi, @FelipeRearden. Thank you for your Feature Request!
> 
> 
> 
> > I'd like to suggest an option in the Settings to only use the words in the custom dictionary
> 
> 
> 
> It looks good. I'll add a new option 👍 

Hello @tadashi-aikawa !!!!!

Thank you very much !!! I'm glad that you like my FR :)

Have a great day!

**Comment by tadashi-aikawa** [comment]
@FelipeRearden 
I have released as [v1.3.0](https://github.com/tadashi-aikawa/obsidian-various-complements-plugin/releases/tag/1.3.0) 🚀 

![image](https://user-images.githubusercontent.com/9500018/142722023-ab06cd76-55da-4bda-982c-8ab638e4ade7.png)

**Comment by FelipeRearden** [comment]
> @FelipeRearden 
> 
> I have released as [v1.3.0](https://github.com/tadashi-aikawa/obsidian-various-complements-plugin/releases/tag/1.3.0) 🚀 

Hello @tadashi-aikawa !!!!!

Thank you very much !!!!!!!! 

I updated and is working perfect !!!! Thank you very much for this new feature, it's perfect :)

Working on version `1.3.0` Obsidian `0.12.19`

I wish you a fantastic day :)
