### ISSUE TITLE
FR: Add the alt/cmd 1-9 keyboard shortcuts from Another Quick Switcher 

### ISSUE THREAD

**Issue by brimwats** [tadashi-aikawa/obsidian-various-complements-plugin#141]
I'd love to use alt1-9 to select options 1-9 on the suggestion modal.

**Comment by tadashi-aikawa** [comment]
Hi, @brimwats. Thank you for your FR :)

I'll implement it in the next release 👍

**Comment by tadashi-aikawa** [comment]
After #245

**Comment by tadashi-aikawa** [comment]
Coming soon...

![image](https://github.com/tadashi-aikawa/obsidian-various-complements-plugin/assets/9500018/9aea01b5-9848-47a4-9751-a189884b693d)

**Comment by tadashi-aikawa** [comment]
@brimwats 
I have released it in [v9.0.0-beta4](https://github.com/tadashi-aikawa/obsidian-various-complements-plugin/releases/tag/9.0.0-beta4) 🚀 

I would appreciate it if you could check it out before the official release.

**Comment by Drakemoor** [comment]
It works well for me after i set the hotkeys. The only thing is that the numbers aren't visible in the suggestions which makes it hard to know what hot key to use. Please, consider this: 
![image](https://github.com/tadashi-aikawa/obsidian-various-complements-plugin/assets/93224920/a363a230-1152-4b89-854c-592324d07e46)
![image](https://github.com/tadashi-aikawa/obsidian-various-complements-plugin/assets/93224920/7a7f7a2f-b5c7-49be-ba21-b912ab26fad4)
thank you.

**Comment by brimwats** [comment]
+1 on the visibility thing, maybe placing them on the right of the file text too is an option. but the keys themselves work!
