### ISSUE TITLE
Overlarge icons in 0.15.5 Obsidian

### ISSUE THREAD

**Issue by menagerie198** [tadashi-aikawa/obsidian-various-complements-plugin#149]
In the latest insider build of Obsidian, when the suggestion window comes up for compliments, the link and vault icons are VERY large. Confirmed in a sandbox vault
![Screenshot 2022-07-08 211627](https://user-images.githubusercontent.com/7330436/178064332-e2967f7a-7cfb-47e9-850a-dd0bb9dfbefd.jpg)

**Comment by tadashi-aikawa** [comment]
Thank you for your report, @menagerie198 :)

I have fixed it in [v7.0.4](https://github.com/tadashi-aikawa/obsidian-various-complements-plugin/releases/tag/7.0.4) 🚀

**Comment by menagerie198** [comment]
Amazingly swift and effective response :-)
