### ISSUE TITLE
Bug: Suggestions cause current line to jump all the way to the top on Ipad

### ISSUE THREAD

**Issue by SignusV** [tadashi-aikawa/obsidian-various-complements-plugin#151]
Demonstrated below:
On the latest version, when the various complements suggestion pops up. It will scroll that line to the top of the page. This is a bug because we are unable to type while looking at the lines above it. This was not the behaviour before.

Device: Ipad Pro
OS: IpadOS 15.5

https://user-images.githubusercontent.com/65055912/178256782-b1bda57d-aa94-4f05-aec8-64f50c166821.MOV

Thanks for checking out this bug, really love the work you have put in :)

**Comment by tadashi-aikawa** [comment]
Hi, @SignusV. Thank you for your report :)

I could reproduce it, but it seems Obsidian's bug (or new specification) because it also occurs in core completions (tag and internal link and ...).

Best regards.
