### ISSUE TITLE
[feature request] hide suggestion board when click somewhere else (command show suggestion)

### ISSUE THREAD

**Issue by woshitoutouge** [tadashi-aikawa/obsidian-various-complements-plugin#152]
two processes for comparison
1. typing → show suggestion board → mouse click another place → the board disappear ✔️
2. command show suggestion → show suggestion board → mouse click another place → the board still exist

request: the second one, hide suggestion board when click somewhere else

![image](https://user-images.githubusercontent.com/99337435/179130515-4452e2fd-9637-42a3-b5b3-40d4c5e1a9db.png)

**Comment by tadashi-aikawa** [comment]
Hi, @woshitoutouge. Thank you for your report :)

I'll fix it in the next release 👍

**Comment by tadashi-aikawa** [comment]
@woshitoutouge 
Fixed in [v7.0.6](https://github.com/tadashi-aikawa/obsidian-various-complements-plugin/releases/tag/7.0.6) 🚀

**Comment by woshitoutouge** [comment]
cool! thanks a lot!
