### ISSUE TITLE
Disable Suggestions in Math Mode

### ISSUE THREAD

**Issue by zcysxy** [tadashi-aikawa/obsidian-various-complements-plugin#153]
When the auto suggestion is on, some weird suggestions show up in the math mode

<img width="438" alt="image" src="https://user-images.githubusercontent.com/48207708/179922802-a94e6c42-9444-4cde-b3da-0e616f6214a9.png">

Since this plugin does not provide auto-completion for latex, I suggest to disable suggestions in the math mode.
This can also let other plugins like Completr to provide suggestions in the math mode.

**Comment by tadashi-aikawa** [comment]
Hi, @zcysxy. Thank you for your FR :)

I understand what you want to, but let me make the issue's status gathering interest. If some people need this feature, I'll consider implementing it 👍 

FYI: You can use a [🎮Toggle Complement automatically] command for workaround.

[🎮Toggle Complement automatically]: https://tadashi-aikawa.github.io/docs-obsidian-various-complements-plugin/3.%20Commands/%F0%9F%8E%AEToggle%20Complement%20automatically/

**Comment by Paulgudring** [comment]
> 

Thanks for your efforts to the community! Various-Completement thoroughly changed my obsidian experience. I like math auto-completion. But I dont want two similar plugins in my vault, afraid of conflicts. My answer is to create a markdown file with a collection of frequent latex commands. So, will there be any feature like [completer](https://github.com/tth05/obsidian-completr) in the feature? with my highest respect to [tth05](https://github.com/tth05) as well.

**Comment by tadashi-aikawa** [comment]
Hi, @Paulgudring :)

> But I dont want two similar plugins in my vault, afraid of conflicts.

Right. I agree with you.

> will there be any feature like [completer](https://github.com/tth05/obsidian-completr) in the feature?

No, I do not intend to support LaTeX completion. However, we could achieve similar functionality by creating a dictionary file and using the 'Custom dictionary complement' feature.

FYR: https://github.com/tadashi-aikawa/obsidian-various-complements-plugin/issues/95

**Comment by LioSergent** [comment]
I think that would be a good option since there are various ways of managing fast writing in Latex (latex-suite, completr, probably others). Could there be a way using <Patterns to suppress trigger> ?

**Comment by tadashi-aikawa** [comment]
"Trigger suppression patterns" are only valid for the same row, so a different approach would be needed.

**Comment by maxbrodeur** [comment]
hi! just an option to disable when in math mode would let me use this plugin. No need for latex suggestions

**Comment by tadashi-aikawa** [comment]
OK. I have found that many people want this functionality, so I will consider implementing it 👍

**Comment by mayurankv** [comment]
That would be great! Really looking forward to this!

**Comment by tadashi-aikawa** [comment]
I'll consider it for the next version 👍

**Comment by tadashi-aikawa** [comment]
@zcysxy @Paulgudring @LioSergent @maxbrodeur @mayurankv 
Released in [v9.4.0](https://github.com/tadashi-aikawa/obsidian-various-complements-plugin/releases/tag/9.4.0) 🚀
