### ISSUE TITLE
Question：How to increase the height of the popup window to display more candidate words?

### ISSUE THREAD

**Issue by tyf2018** [tadashi-aikawa/obsidian-various-complements-plugin#155]
I would like to increase the height of the popup so that more candidates can be displayed. The css snippet is as follows:

.suggestion-container {
    height: 700px;
}

After use, although the height of the pop-up window has increased, the effective area for displaying candidate words has not changed. In the end, only a large invalid blank area is added. As shown below:

![image](https://user-images.githubusercontent.com/56342788/180594920-ba93dbcb-8153-43ec-a49b-778f67719a84.png)

How should I modify the css snippet to achieve the desired effect?

Best regards.

**Comment by tadashi-aikawa** [comment]
@tyf2018 
You should specify the following CSS.

```
.suggestion-container {
  max-height: 500px;
}
.suggestion-container .suggestion {
  max-height: 500px;
}
```

However, that affects the height of other suggestions. If you don't prefer it, I need to update Various Complements.

**Comment by tyf2018** [comment]
> @tyf2018 You should specify the following CSS.

Thank you so much, it solved my problem perfectly.
