### ISSUE TITLE
Wiki link style brackets wrapped around markdown brackets

### ISSUE THREAD

**Issue by kyriss42** [tadashi-aikawa/obsidian-various-complements-plugin#157]
When in obsidian the use of wiki links is left unchecked in favor of markdown links, the plugin wraps wiki link style square brackets around a note file which is already formatted with markdown style brackets.

In other words, let's say I have a note file, stored as 'my_note'.

When I type 'my_note', I get a suggestion to link to this file, which is great. However, clicking on the suggestion gives me now:

`[[[my_note](my_note.md)]]
`

I have an extra pair of wiki link style square brackets wrapped around my markdown linked note.

Choosing wiki links over markdown links resolves the issue, but 1 would like the plugin to be compatible with markdown style linking.

**Comment by tadashi-aikawa** [comment]
Hi, @kyriss42. Thank you for your report :)

I could reproduce it, so I'll consider the option 👍

**Comment by tadashi-aikawa** [comment]
Released in [v7.1.0](https://github.com/tadashi-aikawa/obsidian-various-complements-plugin/releases/tag/7.1.0) 🚀
