### ISSUE TITLE
FR: Option to use a folder as source for the autocomplete suggestions

### ISSUE THREAD

**Issue by chrisgrieser** [tadashi-aikawa/obsidian-various-complements-plugin#16]
Right now, the two sources for words are the custom dictionary and the the current note. However, especially when you split up your writing into multiple smaller notes, (longform plugins, atomic notes, etc.) it would also make sense to alternatively use all notes of a folder as the source for words. I see two options for this:

1. automatically use the folder the current note is located in.
2. set a folder yourself in the settings 

A potential hindrance to implement this, however, could be that folders with a lot of notes would strain performance. 🤔

**Comment by tadashi-aikawa** [comment]
@chrisgrieser 
Thank you for your FR!

I think your requests are very useful, but I will not implement them for a while because

1. As you wrote, there might be performance problems
2. It needs to change many codes if it updates indexes correctly for suggestions when files are updated (especially, it is challenging other than English)

On the other hand, **If it is only once to create indexes during start Obsidian**, I might be able to.

**Comment by chrisgrieser** [comment]
Sure, at least for my usecase, it doesn't need to live update!

Maybe also have a command to simply manually update the index?

**Comment by tadashi-aikawa** [comment]
> for my usecase, it doesn't need to live update!

Then I will attempt to add the feature 👍

In fact, I had had an idea that it treats markdown files in the vault as custom dictionary files.

> Maybe also have a command to simply manually update the index?

It will use a `Reload custom dictionaries` command which is already existed.

![image](https://user-images.githubusercontent.com/9500018/142715336-db9ecf3b-a53f-42a0-82c2-ba8ceb0961f5.png)

**Comment by sinewave** [comment]
+1 for the ability to manually add a folder of notes go the custom dictionary!

**Comment by tadashi-aikawa** [comment]
I am implementing this feature, and I want to release it as 5.1.0.beta2 today 👍

**Comment by tadashi-aikawa** [comment]
There are about 500000 words in my vault.

![2022-02-06](https://user-images.githubusercontent.com/9500018/152666519-3f83504a-74ea-48b3-ae67-78632e27fc90.gif)

**Comment by tadashi-aikawa** [comment]
New status bar for Various Complements.

![image](https://user-images.githubusercontent.com/9500018/152668595-49673ff9-2a1e-4d55-857a-7b0e220d6ffd.png)

**Comment by tadashi-aikawa** [comment]
@chrisgrieser @sinewave

I have updated beta version to [obsidian-various-complements-plugin-beta v5.1.0-beta2](https://github.com/tadashi-aikawa/obsidian-various-complements-plugin-beta/releases/tag/5.1.0.beta2) 🚀 

If you use [BRAT](https://github.com/TfTHacker/obsidian42-brat), please confirm whether it works as you expected. 

The new version loads words from all files in your vault. In addition, of course, If you think that needs to include or exclude directories that start with a specific path, I can add these options. I would be grateful if you would send me feedback :)

**Comment by tadashi-aikawa** [comment]
>  If you think that needs to include or exclude directories that start with a specific path, I can add these options.

After beta-testing for a couple of hours, I decided to add them.

![image](https://user-images.githubusercontent.com/9500018/152680140-73c6e9d5-c67f-4f1d-8f92-cee77fe66f6b.png)

**Comment by tadashi-aikawa** [comment]
Released [obsidian-various-complements-plugin-beta v5.1.0-beta3](https://github.com/tadashi-aikawa/obsidian-various-complements-plugin-beta/releases/tag/5.1.0.beta3) 🚀

**Comment by tadashi-aikawa** [comment]
Released [obsidian-various-complements-plugin-beta v5.1.0-beta4](https://github.com/tadashi-aikawa/obsidian-various-complements-plugin-beta/releases/tag/5.1.0.beta4) 🚀

**Comment by brimwats** [comment]
I can't speak for @chrisgrieser but I can confirm that this works for me!

**Comment by tadashi-aikawa** [comment]
Thank you @chrisgrieser!

**Comment by chrisgrieser** [comment]
Hey! Sorry forgot to answer. The beta does work for me

**Comment by tadashi-aikawa** [comment]
Released at v5.1.0 🚀 

https://github.com/tadashi-aikawa/obsidian-various-complements-plugin/releases/tag/5.1.0
