### ISSUE TITLE
Disable suggestions using terminal components of email address / URLs etc

### ISSUE THREAD

**Issue by nickynicolson** [tadashi-aikawa/obsidian-various-complements-plugin#162]
I have a page called `Organisations`, so if I enter an email address that ends in `.org` I get this popping up as a suggestion. 
I have disabled this by setting the `Min number of characters for trigger=4` but I think there could be a more elegant way to handle this.

**Comment by tadashi-aikawa** [comment]
Thank you for creating an issue, @nickynicolson :)

I agree with your opinion. It sounds good that it doesn't show suggestions when the current word matches specified regex patterns.

**Comment by tadashi-aikawa** [comment]
@nickynicolson 
Released in [v8.0.0-beta2](https://github.com/tadashi-aikawa/obsidian-various-complements-plugin/discussions/183) 🚀

If you use BRAT, please confirm it. If not, please wait to release it as official, v8.0.0.

---

Ex: email address / URLs

Please set it as follows.

```
^~~~.*
^```.*
.+@\S*$
https?://\S*$
```

![image](https://user-images.githubusercontent.com/9500018/204122383-4d180ce9-e2b2-4d38-8bc4-074c7d9ed6fd.png)

**Comment by queezythegreat** [comment]
Great feature, this also solves my problem with Dataview Inline Fields and MetadaEdit fieldClass completion conflict.

I use the following:
```
[^([:]+::[^\]\)\n]+$
```

Which matches when the cursor is currently within a Inline Field, here a quick example of the match:

<img width="857" alt="image" src="https://user-images.githubusercontent.com/552992/221558290-3ac20f00-c1d7-43ee-b227-4fde57cba293.png">

**Comment by tadashi-aikawa** [comment]
Thank you for your sharing, @queezythegreat :)

I don't use both plugins. So your follow-up is highly appreciated! Thanks so much!😄

**Comment by tadashi-aikawa** [comment]
@nickynicolson @queezythegreat 
Released in [v8.0.0](https://github.com/tadashi-aikawa/obsidian-various-complements-plugin/releases/tag/8.0.0) 🚀
