### ISSUE TITLE
Files that have the same name but are under different folders, only show one of the files

### ISSUE THREAD

**Issue by RealRavens** [tadashi-aikawa/obsidian-various-complements-plugin#166]
I'm not sure if it's designed this way intentionally, maybe a sort of optimization.

But anyway here's the issue:

Let's say there are three seperate folders and they all have a file named test within them.
![image](https://user-images.githubusercontent.com/76891274/189253777-417eff18-8fc3-4331-8c77-e54530a4e3db.png)

Note: A quick random example of why a note structure may appear like this is if you seperate sources by folders and you captured the same piece of info from both sources and named the file under them the same for each.

Results: Only one appears (I've tried this a variety of ways)
![Result](https://user-images.githubusercontent.com/76891274/189255675-2fa37e4f-9304-4f8d-a82c-d7e05e4cf5b8.gif)

I would like the option that all files, even if the name has already been found, to show up in complements list. Take folder separation into account basically.

Now, I can understand for visual reasons, if someone doesn't use the "Full" option under "Description on a suggestion" they may not know which of these with the same name is the file they're looking for. So that is something to think about, but I just wanted to bring this up if it's something you considered.

Thanks again for your plugin.

**Comment by tadashi-aikawa** [comment]
Thank you for creating the issue, @RealRavens :)

As you said, in the case of "Internal link complement", I think there should be three suggestions. 

Why there are not is that I didn't have much time to consider it then. So I want to give it a try 👍

**Comment by tadashi-aikawa** [comment]
Fixed in [v7.2.3](https://github.com/tadashi-aikawa/obsidian-various-complements-plugin/releases/tag/7.2.3) 🚀

**Comment by RealRavens** [comment]
Great work! 👍
