### ISSUE TITLE
Internal Link Header Complements

### ISSUE THREAD

**Issue by RealRavens** [tadashi-aikawa/obsidian-various-complements-plugin#167]
Ok so at this point you can see I like keeping you busy Tadashi. I have an idea, but first, a quick story. I was programming some games as I do in my free time and I was thinking about how sometimes I make a library full of functions that are useful. I thought hmm, this would be cool if the same thing could be an option in the complements plugin. Where header links can be suggested.

Now obviously, depending on how someone structures their note database, this could be slow searching through so many notes if they designed each note as a seperate file for each and every nugget of knowledge they capture and write down. But for those that prefer to take notes all in one or a few files on a topic and just use nested headers for the most part, this could almost be like having a function library, but for notes. Since this plugin is IDE inspired. The note basically becomes something like a namespace or class and the header becomes a function.

I promise this is my last feature idea for a bit... I know you have a lot on your plate haha. It's just that this plugin has so much potential, it's awesome!

**Comment by RealRavens** [comment]
Yes, I think we can integrate it with our friend over there. 👍This idea, as trivial as it may seem on paper, just takes this to a whole new level. I might even want this more than the other things I've suggested haha.

**Comment by tadashi-aikawa** [comment]
Thanks! I'll close this issue and continue to #72 👍
