### ISSUE TITLE
Can't use this plugin in KanBan

### ISSUE THREAD

**Issue by kehehee1** [tadashi-aikawa/obsidian-various-complements-plugin#168]
This is a great plugin. Unfortunately it can't use when I edit in Kanban.

**Comment by tadashi-aikawa** [comment]
Hi @kehehee1 :)

I don't use the Kanban plugin, but I have read the plugin's code. Unfortunately, the plugin would have its original implementation to make auto-completion features. So it is not easy to implement auto-completion features used in Various Complements with the Kanban plugin.

Kind regards.
