### ISSUE TITLE
Dictionary Path not accepted?

### ISSUE THREAD

**Issue by chrisgrieser** [tadashi-aikawa/obsidian-various-complements-plugin#17]
I tried to set a custom dictionary, but for some reason it does not work. I guess it's something with the paths, since I see in the demo that you enter an absolute path on Windows?

```zsh
# vault-relative path
Meta/Autocomplete Dictionary.md

# absolute path (I'm on Mac)
file:///Users/chrisgrieser/Library/Mobile%20Documents/iCloud~md~obsidian/Documents/Vault/Meta/Autocomplete%20Dictionary.md
```

**Comment by tadashi-aikawa** [comment]
It uses Obsidian API, so it should support Mac.

> but for some reason it does not work

Does `it does not work` mean that it shows errors as follows?

![image](https://user-images.githubusercontent.com/9500018/142610198-7377ecd1-87c3-4d92-b5cf-58d0f463561f.png)

**Comment by chrisgrieser** [comment]
when I use the absolute path, it shows this:
<img width="453" alt="Screenshot 2021-11-19 11 53 05" src="https://user-images.githubusercontent.com/73286100/142611071-ab959ba1-1d08-4a0e-83fd-04750e0fbb0f.png">

with the relative path, it displays this:
<img width="470" alt="Screenshot 2021-11-19 11 54 56" src="https://user-images.githubusercontent.com/73286100/142611288-044e3423-f3cf-4905-a68f-3b6f6453deed.png">

**Comment by tadashi-aikawa** [comment]
Thank you!

Mmm.. I don't know why they are not accepted. First of all, I will survey a bit more.

**Comment by tadashi-aikawa** [comment]
@chrisgrieser 
I have released [v1.2.1](https://github.com/tadashi-aikawa/obsidian-various-complements-plugin/releases/tag/1.2.1).

It includes bug fixes related to this issue, so please try it and inform me it is working correctly or not.

(v1.2.1 becomes to show error details more than v1.2.0 💚 )

**Comment by chrisgrieser** [comment]
Thanks! here is what I get in the notification
<img width="452" alt="Screenshot 2021-11-20 10 17 07" src="https://user-images.githubusercontent.com/73286100/142721104-4cdcdba8-b4b4-48b7-9a07-56b07099ad14.png">

btw, you could also use `console.log()`, which makes it a bit easier to catch the error messages (other than trying to screenshot the notification before it disappears 😅 )

**Comment by tadashi-aikawa** [comment]
Thank you for your screenshot!

How about absolute path? Relative path is not supported for now and not working in my environment, too.

> (other than trying to screenshot the notification before it disappears 😅 )

If you use v1.2.1 or later, notification never disappears because I set timeout to 0 :)

**Comment by chrisgrieser** [comment]
ah found the issue – absolute paths do not have to the in the `file:///` format. `/Users/chrisgrieser/Library/Mobile Documents/iCloud~md~obsidian/Documents/Vault/Meta/Autocomplete Dictionary.md`does work!

For purposes of mobile & syncing vaults onto different devices, a vault-relative path would probably be more advantageous. (And would also prevent the problem I had from even occurring.)

**Comment by tadashi-aikawa** [comment]
@chrisgrieser 
Good!

> a vault-relative path would probably be more advantageous

I think so, too. I'll try it 👍

**Comment by tadashi-aikawa** [comment]
Once, I'll close this issue.

**Comment by tadashi-aikawa** [comment]
@chrisgrieser 
Coming soon! (v1.4.0)

![image](https://user-images.githubusercontent.com/9500018/142730352-c182a94b-99db-47ab-91bc-eb78c3da61dc.png)

**Comment by tadashi-aikawa** [comment]
@chrisgrieser 
I have released [v1.4.0](https://github.com/tadashi-aikawa/obsidian-various-complements-plugin/releases/tag/1.4.0) 🚀 

Would you please confirm it?

**Comment by chrisgrieser** [comment]
can confirm, runs perfectly 🥳

**Comment by tadashi-aikawa** [comment]
Great!

However, it doesn't work on mobile.. 😅 (https://github.com/tadashi-aikawa/obsidian-various-complements-plugin/issues/21)

So I think it will not support an absolute path in the next release. 😢
