### ISSUE TITLE
Request: Frontmatter "Insert comma after completion" for tags only

### ISSUE THREAD

**Issue by willasm** [tadashi-aikawa/obsidian-various-complements-plugin#172]
For most YAML key values pairs, a comma between words is not desirable. It is with tags though and perhaps a few other keys like status, etc. Perhaps if you could have list of keys that would have the 'comma inserted after completion' enabled for rather than every key in the entire frontmatter.

Great plugin by the way, getting a lot of use out of it, William.

**Comment by tadashi-aikawa** [comment]
Thank you for your FR, @willasm :)

However, Obsidian also allows at the end of commas. It means that the two frontmatters are the same.

```
---
title: hogehoge,
aliases: Python Package Index,
tags: aaa, bbb,
---
```

```
---
title: hogehoge
aliases: Python Package Index
tags: aaa, bbb
---
```

So, I think it doesn't need.

Best regards.

**Comment by willasm** [comment]
That makes sense then, thank you.
