### ISSUE TITLE
[FR] "Show suggestions" hotkey could also be used to close

### ISSUE THREAD

**Issue by huyz** [tadashi-aikawa/obsidian-various-complements-plugin#173]
If the "Show suggestions" popup is already showing, hitting the hotkey again should close it.

Maybe rename "Show suggestions" to "Open/close suggestions popup"

**Comment by tadashi-aikawa** [comment]
Thank you for your FR, @huyz :)

However, sorry, I don't want to implement the feature because Both VS Code nor Jetbrains IDE don't take such an action.

Best regards.

**Comment by huyz** [comment]
@tadashi-aikawa In that case, would it be possible to have a separate hotkey to close the suggestions popup?  Sometimes I can't use `<Esc>` because I use vim mode and at the end of the line, I want to be able to hit `<Esc>` to close the popup and then `<Enter>`.  Or sometimes, I just want to just close the popup to see underneath.

**Comment by tadashi-aikawa** [comment]
@huyz 
It may be possible. Could you create a new FR issue?
