### ISSUE TITLE
[FR] ability to specify an absolute path for custom dictionary

### ISSUE THREAD

**Issue by huyz** [tadashi-aikawa/obsidian-various-complements-plugin#174]
On desktop (but not mobile), I'd like to add `~/Library/Application Support/obsidian/Custom Dictionary.txt` to the list of custom dictionaries because it already contains a bunch of spelling words that I've added via Obsidian core.
Right now the settings only allow a relative path.

**Comment by tadashi-aikawa** [comment]
Hi, @huyz :)

I am not going to implement this feature as far. The reason is in https://github.com/tadashi-aikawa/obsidian-various-complements-plugin/issues/26.

(workaround) Using symbolic links should solve this problem.
