### ISSUE TITLE
Plugin Suggestion Note link is broken

### ISSUE THREAD

**Issue by erdemalpkaya** [tadashi-aikawa/obsidian-various-complements-plugin#175]
I am not sure the issue related with the plugin or Obsidian itself. So for the example that I am going to share below I chose the `Cluvio Update` note from the plugin suggestion and you can see there but whenever I click the note link, the note link rather than send me the `Cluvio Update` note it creates an extra note called `Cluvio`, however if I put the %20 between Cluvio and Update it sends me to the correct note. How can we fix the issue? Thanks.

![CleanShot 2022-10-24 at 15 01 54](https://user-images.githubusercontent.com/24259112/197533383-b655df04-bce2-4345-a3f4-d605a630c94a.png)

**Comment by tadashi-aikawa** [comment]
Hi, @erdemalpkaya. Thank you for creating an issue :)

It seems to be a bug of Various Complements, only if "Use [[Wikilinks]]" is enabled.

**Comment by tadashi-aikawa** [comment]
@erdemalpkaya 
Fixed in [v7.2.5](https://github.com/tadashi-aikawa/obsidian-various-complements-plugin/releases/tag/7.2.5) 🚀
