### ISSUE TITLE
[FR] Support Ctrl+J and Ctrl+K even on macOS

### ISSUE THREAD

**Issue by huyz** [tadashi-aikawa/obsidian-various-complements-plugin#176]
I'm on macOS.  Strangely, when I select the additional keys "Ctrl/Cmd+N" for additional cycle, I can choose either "Ctrl" or "Cmd" with the "N".  But if I select "Ctrl/Cmd+J" for additional cycle, I can only choose "Cmd" with the "J".  I'm a vim, FZF, CtrlP user, and I'm used to doing "Ctrl+J" and "Ctrl+K" to navigate choices.

**Comment by tadashi-aikawa** [comment]
Thank you for your FR, @huyz :)

First of all, I'll implement this FR.

> when I select the additional keys "Ctrl/Cmd+N" for additional cycle, I can choose either "Ctrl" or "Cmd" with the "N". 

That's so weird.🤔 On macOS, `Ctrl+N` should not work, only `Cmd+N`.

> But if I select "Ctrl/Cmd+J" for additional cycle, I can only choose "Cmd" with the "J".

It works as I expected.

**Comment by huyz** [comment]
I guess ideally it would be nice if we could choose between Cmd and Ctrl ahead of time in the Various Complements settings, to minimize potential conflicts with other plugins or Hotkeys.

But simultaneously supporting Cmd and Ctrl at the same time is a second best option (over disabling Cmd), if that's easier to implement.  That's because I really prefer Ctrl even on macOS.

I've always loved that macOS has more available modifiers than Windows: allows us even more non-conflicting hotkeys, especially great for vi users who are accustomed to using Ctrl

**Comment by tadashi-aikawa** [comment]
> I guess ideally it would be nice if we could choose between Cmd and Ctrl ahead of time in the Various Complements settings, to minimize potential conflicts with other plugins or Hotkeys.

Sure.

-  `"Ctrl/Cmd+N"` means `Cmd + N` on macOS
- `"Ctrl + N"` means `Ctrl + N` both on macOS and Windows (I'll implement)

**Comment by tadashi-aikawa** [comment]
After #245

**Comment by tadashi-aikawa** [comment]
@huyz 
I have released it in [v9.0.0-beta1](https://github.com/tadashi-aikawa/obsidian-various-complements-plugin/releases/tag/9.0.0-beta1) 🚀 

If you use BRAT, I would appreciate it if you could check it out before the official release.

**Comment by huyz** [comment]
Looks good so far.  Thanks!
