### ISSUE TITLE
[FR] hotkey for closing suggestions popup (but remain in vim insert mode)

### ISSUE THREAD

**Issue by huyz** [tadashi-aikawa/obsidian-various-complements-plugin#177]
(follow-up to https://github.com/tadashi-aikawa/obsidian-various-complements-plugin/issues/173)

Would love a separate hotkey to close the suggestions popup. Sometimes I can't use `<Esc>` because I do use vim mode and `<Esc>` thus has 2 meanings.
Often, at the end of the line, I want to be able to hit `<Esc>` once to close the popup but remain in vim insert mode and then hit `<Enter>`. Or sometimes, I just want to just close the popup to see underneath and continue what I'm doing.

**Comment by tadashi-aikawa** [comment]
@huyz 
Thank you for creating an issue :)

> Often, at the end of the line, I want to be able to hit <Esc> once to close the popup but remain in vim insert mode and then hit <Enter>. Or sometimes, I just want to just close the popup to see underneath and continue what I'm doing.

By the way, I guess that it should satisfy your requirements by disabling `Propagate ESC`. Doesn't it work correctly on macOS? 🤔 

![image](https://user-images.githubusercontent.com/9500018/197941220-4e6da9f9-fdde-4336-b8c6-64ad8b58a6d2.png)

**Comment by huyz** [comment]
It wouldn't satisfy because most of the time I do want Esc to propagate. Basically, I don't want the pop up to interfere with my vim habits, as it would force me to hit Esc twice very often

**Comment by tadashi-aikawa** [comment]
@huyz 
Thanks 👍

**Comment by huyz** [comment]
Btw, VS Code provides a `hideSuggestWidget` command which is mapped to Shift+Esc by default.

**Comment by tadashi-aikawa** [comment]
@huyz 
Released in [v7.3.0](https://github.com/tadashi-aikawa/obsidian-various-complements-plugin/releases/tag/7.3.0) 🚀

**Comment by huyz** [comment]
@tadashi-aikawa awesome, thanks!
