### ISSUE TITLE
Warning of downloading `cedict_ts.u8` should disappear if I have cedict_ts.u8 in my vault root.

### ISSUE THREAD

**Issue by JohnsonLee-debug** [tadashi-aikawa/obsidian-various-complements-plugin#178]
![image](https://user-images.githubusercontent.com/53596783/199975096-b1825951-0b36-45fd-b75c-68cad28bc8ca.png)

I think this Waring should disappear if I already have cedict_ts.u8 in my vault root.

![image](https://user-images.githubusercontent.com/53596783/199975232-843c0e62-e740-43cc-a845-44ee51e3d928.png)

**Comment by tadashi-aikawa** [comment]
@JohnsonLee-debug 
Thanks for your feedback 👍

**Comment by tadashi-aikawa** [comment]
@JohnsonLee-debug 
Released in [v8.0.0-beta1](https://github.com/tadashi-aikawa/obsidian-various-complements-plugin/discussions/183) 🚀 

If you use BRAT, please confirm it. If not, please wait to release it as official, v8.0.0.

**Comment by tadashi-aikawa** [comment]
@JohnsonLee-debug 
Released in [v8.0.0](https://github.com/tadashi-aikawa/obsidian-various-complements-plugin/releases/tag/8.0.0) 🚀
