### ISSUE TITLE
Feature Request: Remove complements that are block refs

### ISSUE THREAD

**Issue by Caffa** [tadashi-aikawa/obsidian-various-complements-plugin#184]
![image](https://user-images.githubusercontent.com/1797721/204438050-bba2ec31-d7bc-4d8c-83f5-64a2b9df1fea.png)

The last one should be removed because we cannot see what the block reference is to, and it is not even the full reference link. 

Also we might want to remove the complements that are part of html links?

**Comment by tadashi-aikawa** [comment]
Hi, @Caffa :)

I couldn't reproduce your situation. Could you tell me the reproduction steps in the Sandbox vault?

**Comment by tadashi-aikawa** [comment]
This issue will be closed for now, as there have been no comments from visitors for a month.
