### ISSUE TITLE
Request to add support for Russian lang

### ISSUE THREAD

**Issue by CinemaGame** [tadashi-aikawa/obsidian-various-complements-plugin#185]
Greetings! I'm new to Obsidian and I'm really amazed by both the huge number of plugins and their functionality. I was very glad to find this plugin, but I was a little upset that I didn't find Russian among the supported languages. Will it be supported in the future? In any case, thanks to the author for the development and contribution to the community!

**Comment by tadashi-aikawa** [comment]
Hi, @CinemaGame :)

At first, I am not familiar with Russian, but if that uses whitespace as the word separator, You should be able to use this plugin with the `Main > Strategy` setting set to `default`.

**Comment by tadashi-aikawa** [comment]
This issue will be closed for now, as there have been no comments from visitors for a month.
