### ISSUE TITLE
Android app crashes

### ISSUE THREAD

**Issue by alabotski** [tadashi-aikawa/obsidian-various-complements-plugin#186]
Hi 

I enabled customer dictionary complement 
And added dictionary of Russian words
https://raw.githubusercontent.com/alabotski/dictionary/main/russian.txt

On computer all works fine
But on Android Obsidian app crashes.

**Comment by tadashi-aikawa** [comment]
Hi, @alabotski :)

I could reproduce your situation. The cause is probably that the memory allowance is exceeded, i.e., the file is too large. This is a limitation of the OS and Obsidian execution environment, so there seems to be nothing I can do about it.

Best regards.

**Comment by tadashi-aikawa** [comment]
This issue will be closed for now, as there have been no comments from visitors for a month.
