### ISSUE TITLE
[Feature Request] Remove space before dot

### ISSUE THREAD

**Issue by Fooftilly** [tadashi-aikawa/obsidian-various-complements-plugin#187]
Would it be possible if I have "insert space after completion" option turned on to add option to remove that space if I type dot after completion? It would be nice quality of life feature for completions at the end of the sentence.

**Comment by tadashi-aikawa** [comment]
Thank you for your FR, @Fooftilly :)

> Would it be possible if I have "insert space after completion" option turned on to add option to remove that space if I type dot after completion? 

I have understood your suggestion, but it is a bit tricky because it needs to handle after the completion.
