### ISSUE TITLE
Option for autocompleting by Tab

### ISSUE THREAD

**Issue by phlind** [tadashi-aikawa/obsidian-various-complements-plugin#19]
Would that be possible, or does it mess with other Tab functions? One is just used to it by other programs. Thanks!

**Comment by tadashi-aikawa** [comment]
Hi, @phlind. Thank you for your Feature Request!

Which do you mean as follows?

1. It shows suggestions when we push a TAB key
2. It selects a suggestion by push a TAB key instead of Enter

Best regards.

**Comment by phlind** [comment]
Hi, @tadashi-aikawa! Thansk for your fast answer.

I was thinking about the second one ("It selects a suggestion by pushing a TAB key instead of Enter").

**Comment by tadashi-aikawa** [comment]
Thank you for your reply! I'll try it 👍

**Comment by tadashi-aikawa** [comment]
@phlind 
I have released as [v1.3.0](https://github.com/tadashi-aikawa/obsidian-various-complements-plugin/releases/tag/1.3.0) 🚀

**Comment by phlind** [comment]
@tadashi-aikawa Wow, very nice, that was fast. 👍
