### ISSUE TITLE
No option to select alias when autocompleting from alias

### ISSUE THREAD

**Issue by Sinled** [tadashi-aikawa/obsidian-various-complements-plugin#190]
Hi 
i am not sure if this is a bug, or i am missing some settings, but behaviour described in this issues - doesn't work for me
https://github.com/tadashi-aikawa/obsidian-various-complements-plugin/issues/64
https://github.com/tadashi-aikawa/obsidian-various-complements-plugin/issues/73

it finds note corresponding to alias, but will insert link to it without alias.

Obsidian v1.1.9
Various complements v7.3.0

**Comment by tadashi-aikawa** [comment]
Hi, @Sinled :)

Do you enable the following option?

![image](https://user-images.githubusercontent.com/9500018/210281855-efd2091e-4d62-41f2-8cff-eb285beb8649.png)

**Comment by Sinled** [comment]
My bad, i've missed this option. Thanks for quick reply
