### ISSUE TITLE
FR - Would love this plugin if it treated links like 'outgoing links' core plugin/feature

### ISSUE THREAD

**Issue by delzero** [tadashi-aikawa/obsidian-various-complements-plugin#192]
By which I mean - to retain the single word typed and NOT replace it with the full path of the page link. Or at least an option to do this.

I imagine my use case is common, that I *would* use this awesome tool to find all links if it did this. But currently having full paths just looks clunky - and so currently I use the built-in 'outgoing links' panel to create my links.

If there is already a method to do this, sorry but I could not find it in the manual/help pages.

**Comment by tadashi-aikawa** [comment]
Hi, @delzero :)

Thank you for your FR. However, I couldn't imagine your situation. Could you tell me a specific example?

**Comment by tadashi-aikawa** [comment]
This issue will be closed for now, as there have been no comments from visitors for a month.
