### ISSUE TITLE
[Feature Request] Add Note Name as Alias

### ISSUE THREAD

**Issue by helicos6** [tadashi-aikawa/obsidian-various-complements-plugin#193]
Thank you for creating this excellent plugin, I just discovered it!

I would like to request the following:

`Show the File Path in the suggestions and Automatically add the File Name as the Alias.`

Example: I have several notes with the title "Resources" in my vault as shown here:

![image](https://user-images.githubusercontent.com/34452093/211646821-fc2b4caf-f4b4-45ec-9128-9d0f2f1b33e4.png)

Right now, I don't know which Resource file is the correct one because no path is shown. If the File Path is in the suggestions, it will be easier to select the correct one.

Once I make a selection, the file path is shown in Reading View because there is no alias:

![image](https://user-images.githubusercontent.com/34452093/211648212-91a34fcf-098c-4273-8c15-26ef8200c039.png)

Please automatically add the File Name as the alias so that the file path is not shown in Reading View, like this:

`[[Programming/Python/Resources|Resources]]`

**Comment by tadashi-aikawa** [comment]
Hi, @helicos6 :)

> Right now, I don't know which Resource file is the correct one because no path is shown. If the File Path is in the suggestions, it will be easier to select the correct one.

Please set `Full` to [Description on suggestion](https://tadashi-aikawa.github.io/docs-obsidian-various-complements-plugin/4.%20Options/4.2.%20Appearance/%E2%9A%99%EF%B8%8FDescription%20on%20suggestion/
).

> Please automatically add the File Name as the alias so that the file path is not shown in Reading View, like this:

Please set `ON` to [Suggest with an alias](https://tadashi-aikawa.github.io/docs-obsidian-various-complements-plugin/4.%20Options/4.7.%20Internal%20link%20complement/%E2%9A%99%EF%B8%8FSuggest%20with%20an%20alias/).

**Comment by helicos6** [comment]
Hi @tadashi-aikawa 

Thanks for your response.

> `Please set Full to Description on suggestion.`

Yes, this worked.

> `Please set ON to Suggest with an alias`

This works only for notes that have aliases defined using YAML.

If there are no defined aliases, I am not able to get the file name of the note added as the alias.

What is added: `[[Programming/Python/Resources]]`

My request: `[[Programming/Python/Resources|Resources]]`

**Comment by tadashi-aikawa** [comment]
@helicos6 
> If there are no defined aliases, I am not able to get the file name of the note added as the alias.

I got it. I'll add an option to work as you expected.

**Comment by helicos6** [comment]
@tadashi-aikawa Thank you so much! I'm looking forward to it. 😃

**Comment by tadashi-aikawa** [comment]
Soon 👍 

![2023-01-22-14-22-16](https://user-images.githubusercontent.com/9500018/213901892-3d48c877-8312-4d76-8187-4162c8cb8941.gif)

**Comment by tadashi-aikawa** [comment]
@helicos6 
Released in [v8.0.0-beta3](https://github.com/tadashi-aikawa/obsidian-various-complements-plugin/discussions/183) 🚀

If you use BRAT, please confirm it. If not, please wait to release it as official, v8.0.0.

**Comment by helicos6** [comment]
@tadashi-aikawa I installed v8.0.0-beta3 and toggled ON Suggest with an Alias, but the alias is not added for me.

<img width="467" alt="image" src="https://user-images.githubusercontent.com/34452093/213930089-95c5a1aa-2b32-4460-88c7-40d20ecafeaf.png">

<img width="742" alt="image" src="https://user-images.githubusercontent.com/34452093/213930093-9ccf48dd-8885-450b-8b91-845138d48c78.png">

![2023-01-22_12-22-11 (1)](https://user-images.githubusercontent.com/34452093/213930302-bb701419-8ff0-494d-9452-c21fabe94576.gif)

**Comment by tadashi-aikawa** [comment]
@helicos6 
Could you tell me the "New link format" setting?

![image](https://user-images.githubusercontent.com/9500018/213944354-9e55bcce-2551-4d32-98de-de278123ed54.png)

**Comment by helicos6** [comment]
@tadashi-aikawa I had it set to 'Absolute path in vault'.

<img width="735" alt="image" src="https://user-images.githubusercontent.com/34452093/213946138-a527bde0-d4c0-486a-9384-48896ad038c9.png">

The Alias works correctly when I set this to 'Shortest path when possible'.

I would prefer 'Absolute path in vault' if possible to make it work with Alias. But if that's too much trouble, no worries. Thanks for adding my request!

**Comment by tadashi-aikawa** [comment]
@helicos6 
Thank you for your reply :)

Unfortunately, I am not going to fulfill your request because the user who set `Absolute path in vault` to `New link format` should expect that all internal links are as an absolute path in general.

Best regards.

**Comment by tadashi-aikawa** [comment]
But it would be possible to add an "Always insert a file name as an alias" option... 🤔

**Comment by helicos6** [comment]
> But it would be possible to add an "Always insert a file name as an alias" option... 🤔

Yes, that would be great! 😃

**Comment by tadashi-aikawa** [comment]
Hi, @helicos6 :)

I have released v8.0.0-beta9; it adds the "An excluded regular expression pattern from the displayed internal link" option. The option may resolve your following issue 🤔 

> Unfortunately, I am not going to fulfill your request because the user who set Absolute path in vault to New link format should expect that all internal links are as an absolute path in general.

**Comment by helicos6** [comment]
Hi @tadashi-aikawa,

I currently have v8.0.0-beta10 installed but cannot find the "An excluded regular expression pattern from the displayed internal link" option.

![image](https://user-images.githubusercontent.com/34452093/219963269-2eb87b34-28d7-4abc-836f-84242d07bf3b.png)

Can you please share a screenshot?

**Comment by tadashi-aikawa** [comment]
@helicos6 

Please see https://github.com/tadashi-aikawa/obsidian-various-complements-plugin/discussions/183.

**Comment by helicos6** [comment]
@tadashi-aikawa Okay, I see the option now. I had to disable and enable the plugin.

Setting the regex to .+/ has the following effect:
`[[Programming/Python/Resources]]` changes to `[[Programming/Python/Resources|Resources]]` _as desired_.

However, this means I have to choose between the above _**or**_ this change:
`[[hoge(huga)]]` will transform to `[[hoge(huga)|hoge]]`

The current implementation doesn't allow setting both options simultaneously.

If instead there was a Regex Find/Replace option, then both of the above (as well as far greater flexibility for other options) would be possible, like this:

Find: .+/(.+) \(.+\)
Replace: $1

Example result:
[[Programming/Python/Resources (Python)]] will transform to [[Programming/Python/Resources (Python)|Resources]]

**Comment by tadashi-aikawa** [comment]
Thank you for your confirming, @helicos6 :)

> If instead there was a Regex Find/Replace option, then both of the above (as well as far greater flexibility for other options) would be possible, like this:

It is so cool! I'll replace the "An excluded regular expression pattern from the displayed internal link" option with your suggestion. (It is a breaking change, but the version is still beta👍 )

**Comment by tadashi-aikawa** [comment]
This option is for professionals😂 But highly customizable 👍 

![image](https://user-images.githubusercontent.com/9500018/220111883-1a6b8bbe-76b1-4ade-95b3-e8575684dee9.png)

**Comment by tadashi-aikawa** [comment]
@helicos6 
Released in [v8.0.0-beta11](https://github.com/tadashi-aikawa/obsidian-various-complements-plugin/releases/tag/8.0.0-beta11) 🚀

I hope you will be satisfied 🙏

**Comment by helicos6** [comment]
@tadashi-aikawa It works perfectly now, thank you so much! 

Do you have this so I can support you?
![image](https://user-images.githubusercontent.com/34452093/220155647-6b8005d0-407f-4bff-9930-663f06552691.png)

**Comment by tadashi-aikawa** [comment]
@helicos6 
Cool!

> Do you have this so I can support you?

I didn't have them, but I have created the "Buy me a coffee" button! I would be happy if you used it 😄

**Comment by helicos6** [comment]
@tadashi-aikawa Something is wrong.

![image](https://user-images.githubusercontent.com/34452093/220359847-07de86d0-0e98-412a-85b9-7a09ba13d58d.png)

**Comment by tadashi-aikawa** [comment]
@helicos6 
Thank you! Unfortunately, my account had been suspended. I sent an e-mail to the support team. Please wait for the follow-up information🙇

**Comment by tadashi-aikawa** [comment]
@helicos6 
Released in [v8.0.0](https://github.com/tadashi-aikawa/obsidian-various-complements-plugin/releases/tag/8.0.0) 🚀 

P.S. I still wait for the response from "Buy me a coffee" team. I'll inform to you after receiving their responses.

**Comment by tadashi-aikawa** [comment]
@helicos6 
Sorry to keep you waiting! But we have some unfortunate news. "Buy me a coffee" team permanently banned my account without explanation or reason😢 

As we don't want to spend any more effort on things that have nothing to do with development, we will only take your sentiments. Thank you!!

**Comment by helicos6** [comment]
@tadashi-aikawa So sorry to hear that. Thank you for your efforts with the plug-in.
