### ISSUE TITLE
complement does not work after the [ ]

### ISSUE THREAD

**Issue by YoungChan404** [tadashi-aikawa/obsidian-various-complements-plugin#194]
I want Various Complements(VC) to help me to insert inline metadata. But I find that VC can't be triggered after typing "[inline field:: xxx]"(i.e., the first inline metadata). It will work again only when I switch to a new line. Is there a solution? Thank you.

**Comment by tadashi-aikawa** [comment]
Thank you for your report, @YoungChan404 :)

However, I couldn't imagine your situation. Could you tell me a specific example, or, reproduction steps in the sandbox vault?

**Comment by YoungChan404** [comment]
I'm currently trying to manage my metadata with the plugin Metadata Menu(short for MM in the following). By MM, I can pre-define various metadata fields and corresponding values (e.g.  the field task_priority with values: [🔴🔴🔴🔴🔴, 🔴🔴🔴🔴, 🔴🔴🔴]). MM can automatically complete the values to select with, if and only if I insert the correct field. However, it's hard to remmeber precisely every field. So I use VC to help me. For example, for the inline metadata fields for ToDos, I defined following in the dictionary file:
[inl_td_ToDoPriority::<CARET> ]|inline field-ToDo Priority|ilftdpriority
[inl_td_TodoTypse::<CARET> ]|inline field-Todo Typse|ilftdtype
[inl_td_TodoFocus::<CARET> ]|inline field-Todo Focus|ilftdfocus
[inl_td_ToDoStatus::<CARET> ]|inline field-Todo Status|ilftdstatus
So all can show up if I just type "ilft". Sometimes I want to insert multiple inline metadata in the same line for the same task, and the problems appears. It's not a big problem. It's just a little unconvanient. Anyway, thank for your kind replying.

**Comment by tadashi-aikawa** [comment]
Thank you for your information :)

I thought you were using [Front matter complement], but it is my misunderstanding, and you didn't use [Front matter complement] ?

I have never used MM, so it is difficult to reproduce your situation. So it would be helpful to write reproduction steps if you can. (if you want to answer this question)

[Front matter complement]: https://tadashi-aikawa.github.io/docs-obsidian-various-complements-plugin/1.%20Features/Front%20matter%20complement/

**Comment by YoungChan404** [comment]
Thanks for your kind reply. I didn't use [Front matter complement](https://tadashi-aikawa.github.io/docs-obsidian-various-complements-plugin/1.%20Features/Front%20matter%20complement/). I want to insert the inline field in the text of the note, rather than its front matter. The following is my procedure:
Step 1:
add "[inl_td_ToDoPriority:: ]|inline field-ToDo Priority|ilftdpriority","[inl_td_TodoTypse:: ]|inline field-Todo Typse|ilftdtype" to my dictionary. Reload the dictionary to make it work.
Step 2:
On any note, add a task, for example
- [ ] meet some,[inl_td_ToDoPriority:: ], [inl_td_TodoTypse:: ]
With the help of VC, I expect to add this task by typing the following characters:
- [ ] meet some,ilftdpriority, ilftdtype
Step 3:
When I type "ilftdpriority", VC can be triggered and works well to insert [inl_td_ToDoPriority:: ].
But VC cannot be triggered again to insert [inl_td_TodoTypse:: ] when I continue to type "ilftdtype". It works only when I switch to a new line. It seems that VC cannot be triggered when there is a "[]" in the same line.

**Comment by tadashi-aikawa** [comment]
Thank you for your details, @YoungChan404 :)

But unfortunately, I couldn't reproduce it in the sandbox vault.

https://user-images.githubusercontent.com/9500018/215251199-3019e4b4-c843-4107-b6c2-578e1e145fe6.mp4

Did I misread your reproduction steps?

`settings` (by `Copy plugin settings` command)
```
{
    "version": "7.3.0",
    "mobile": false,
    "settings": {
        "strategy": "default",
        "matchStrategy": "prefix",
        "maxNumberOfSuggestions": 5,
        "maxNumberOfWordsAsPhrase": 3,
        "minNumberOfCharactersTriggered": 0,
        "minNumberOfWordsTriggeredPhrase": 1,
        "complementAutomatically": true,
        "delayMilliSeconds": 0,
        "disableSuggestionsDuringImeOn": false,
        "insertAfterCompletion": true,
        "firstCharactersDisableSuggestions": ":/^",
        "showMatchStrategy": true,
        "showComplementAutomatically": true,
        "showIndexingStatus": true,
        "descriptionOnSuggestion": "Short",
        "selectSuggestionKeys": "Enter",
        "additionalCycleThroughSuggestionsKeys": "None",
        "disableUpDownKeysForCycleThroughSuggestionsKeys": false,
        "openSourceFileKey": "None",
        "propagateEsc": false,
        "enableCurrentFileComplement": true,
        "currentFileMinNumberOfCharacters": 0,
        "onlyComplementEnglishOnCurrentFileComplement": false,
        "enableCurrentVaultComplement": false,
        "currentVaultMinNumberOfCharacters": 0,
        "includeCurrentVaultPathPrefixPatterns": "",
        "excludeCurrentVaultPathPrefixPatterns": "",
        "includeCurrentVaultOnlyFilesUnderCurrentDirectory": false,
        "enableCustomDictionaryComplement": true,
        "customDictionaryPaths": "dictionary.md",
        "columnDelimiter": "Pipe",
        "customDictionaryWordRegexPattern": "",
        "delimiterToHideSuggestion": "",
        "delimiterToDivideSuggestionsForDisplayFromInsertion": "",
        "caretLocationSymbolAfterComplement": "",
        "displayedTextSuffix": " => ...",
        "enableInternalLinkComplement": true,
        "suggestInternalLinkWithAlias": true,
        "excludeInternalLinkPathPrefixPatterns": "",
        "enableFrontMatterComplement": true,
        "frontMatterComplementMatchStrategy": "inherit",
        "insertCommaAfterFrontMatterCompletion": false,
        "intelligentSuggestionPrioritization": {
            "maxDaysToKeepHistory": 30,
            "maxNumberOfHistoryToKeep": 0
        },
        "showLogAboutPerformanceInConsole": true,
        "selectionHistoryTree": null
    }
}
```

**Comment by YoungChan404** [comment]
It seems to be the problem of the plugin Metadata Menu. After I update Metadata Menu to its latest version, the problem disappeared. Thank you very much for your kind help.

**Comment by tadashi-aikawa** [comment]
I’m glad to hear that 😄
