### ISSUE TITLE
Bug Report: Does not respect First Characters Settings

### ISSUE THREAD

**Issue by brimwats** [tadashi-aikawa/obsidian-various-complements-plugin#195]
I have settings like this 
![image](https://user-images.githubusercontent.com/73113656/213100159-7f627093-7142-4214-91b6-7283b683666d.png)

So I can use Note Auto Creator like this:

![image](https://user-images.githubusercontent.com/73113656/213100189-ac0d684b-8c4d-408b-846e-2011ec687a65.png)

However when Complement Automatically is on, it stops respecting the setting:
![image](https://user-images.githubusercontent.com/73113656/213100255-7f460e58-64be-4deb-aed8-9da4802485f2.png)

This worked until recently, not sure whose update affected it.

**Comment by tadashi-aikawa** [comment]
Thank you for your bug report, @brimwats :)

Unfortunately, I couldn't reproduce your situation. Could you tell me the reproduction steps in the sandbox vault?

**Comment by brimwats** [comment]
sure! I'll try this weekend

**Comment by brimwats** [comment]
good news! it resolved through someone's update :) closing
