### ISSUE TITLE
Save history data in separate file

### ISSUE THREAD

**Issue by sanjarcode** [tadashi-aikawa/obsidian-various-complements-plugin#197]
## Current situation and solution
The history is saved in `.obsidian/plugins/various-complements/data.json` under `selectionHistoryTree` key.

Can we move this to a dedicated file?

## Problem
I want to save preferences using `git`, but the file keeps on changing. 

If the history was saved in a different file, I could add that file to `.gitignore`. But this is not possible now, since everything is in the same file.

**Comment by tadashi-aikawa** [comment]
Hi, @sanjarcode :)

I agree with your requirements. However, Obsidian recommends managing plugin data for syncing with other devices in a data.json file.

I want to and will attempt to try the implementation, but it might not be easy.

Best regards.

**Comment by sanjarcode** [comment]
Okay, let me know if I can help.

**Comment by tadashi-aikawa** [comment]
@sanjarcode 
I'm back now. I have released it in [v8.2.0-beta3](https://github.com/tadashi-aikawa/obsidian-various-complements-plugin/releases/tag/8.2.0-beta3) 🚀

If you use [BRAT](https://github.com/TfTHacker/obsidian42-brat), please confirm whether it works as you expected.

**Comment by tadashi-aikawa** [comment]
Released in [v8.2.0](https://github.com/tadashi-aikawa/obsidian-various-complements-plugin/releases/tag/8.2.0) 🚀
