### ISSUE TITLE
FR: (beta) allow setting of the Use common prefix completion of suggestion hotkey

### ISSUE THREAD

**Issue by brimwats** [tadashi-aikawa/obsidian-various-complements-plugin#198]
This might already on the map but I love this feature and would love to use it more, but tab is currently the key I use to cycle between options, and enter to select. 

I would love to cycle with a left hand key and select with a right hand, which is not currently possible (without using cmd keys, I don't have CMD on the right side of my keyboard)

**Comment by tadashi-aikawa** [comment]
Hi, @brimwats :)

Your issue looks to be duplicated with [#156 (comment)](https://github.com/tadashi-aikawa/obsidian-various-complements-plugin/issues/156#issuecomment-1312658780). If so, let me close this issue.

Best regards.

**Comment by brimwats** [comment]
agreed! closing
