### ISSUE TITLE
Q: Does this plugin support dictionaries in the .dic / .dict filetype? 

### ISSUE THREAD

**Issue by brimwats** [tadashi-aikawa/obsidian-various-complements-plugin#20]
i.e. https://www.ibm.com/docs/en/iis/8.1?topic=files-dictionary-file-format

**Comment by tadashi-aikawa** [comment]
Hi, @brimwats .

No, it doesn't support for `.dic` or `.dict`, but probably it can.

**Comment by tadashi-aikawa** [comment]
I have closed this issue for a moment.
