### ISSUE TITLE
[BUG]Selecting the `cedict_ts.u8` file will increase the plugin startup delay

### ISSUE THREAD

**Issue by dapaning** [tadashi-aikawa/obsidian-various-complements-plugin#200]
I don't know what it is, it confuses me，select "cedict_ts.u8" file, randomly open any plug-in, it will increase the delay time of **500ms+**.
Version：8.0.0-beta3

![348](https://user-images.githubusercontent.com/66105129/217742549-4b2fe199-d782-435f-9e00-a296da35315c.gif)

**Comment by tadashi-aikawa** [comment]
Does it reproduce without auto-note-mover?

![image](https://user-images.githubusercontent.com/9500018/217825458-01be2492-1325-49fb-a8e3-85027f2e69d0.png)

**Comment by dapaning** [comment]
- Close auto-note-mover after normal, again open a new plug-in, any plug-in, the delay increases
- Time does not stack, if I open multiple plugins at once, it will only increase the startup time of the first plugin
- Install Various Complements without opening cedict_ts.u8 file, normal
- Install Various Complements and open cedict_ts.u8 file, which will increase the delay
- There is a special case
    - Install Various Complements, open cedict_ts.u8 file. When I do not open a new plugin，normal
    - if I open a new plugin, the delay increases
![2023-02-10_01-33-57](https://user-images.githubusercontent.com/66105129/217892665-608eee36-023a-4fef-aa82-2811b397b54d.jpg)

**Comment by tadashi-aikawa** [comment]
Thank you for your kind report, @dapaning :)

In conclusion, this is not a bug.

I have surveyed elapsed times about the following two cases.

1. Read `cedict_ts.u8`
2. Load `cedict` by [chineseTokenizer](https://github.com/tadashi-aikawa/chinese-tokenizer) which is forked from [yishn/chinese-tokenizer](https://github.com/yishn/chinese-tokenizer)

Below is the results.

```
read cedict: 32.549072265625 ms
load cedict: 464.287109375 ms
```

`cedict_ts.u8` is a massive file with many tokens, So `chinese-tokeniser` needs enough time to load it.

Best regards.

----

## Source

```
      console.time("read cedict")
      const dict = await app.vault.adapter.read(settings.cedictPath);
      console.timeEnd("read cedict")
```

```
  static create(dict: string): ChineseTokenizer {
    const ins = new ChineseTokenizer();
    console.time("load cedict")
    ins._tokenize = chineseTokenizer.load(dict);
    console.timeEnd("load cedict")
    return ins;
  }
```

**Comment by tadashi-aikawa** [comment]
This issue will be closed for now, as there have been no comments from visitors for a month.
