### ISSUE TITLE
"Front matter complement" doesn't work.

### ISSUE THREAD

**Issue by young5lee** [tadashi-aikawa/obsidian-various-complements-plugin#201]
Hello.
First of all, you made a very useful plug-in, so I'm using it well.

However, the function is not working, so please review it. 
(It indexes, but no autocomplete appears!)

Thank you!

**Comment by tadashi-aikawa** [comment]
Hi, @young5lee :)

Sure. Please tell me more details. (ex: mp4 or reproduction steps)

**Comment by young5lee** [comment]
file, fault component works normally, but only front meter component does not work.

Is there any further action I should take?
<img width="785" alt="스크린샷 2023-02-13 오전 9 38 08" src="https://user-images.githubusercontent.com/85347663/218347993-7d0ea577-126b-4bb5-a83a-01c98e5e16a7.png">

<img width="807" alt="스크린샷 2023-02-13 오전 9 38 01" src="https://user-images.githubusercontent.com/85347663/218347998-aeb96bf8-d680-4589-bdf3-ddf8727ea443.png">
<img width="813" alt="스크린샷 2023-02-13 오전 9 44 32" src="https://user-images.githubusercontent.com/85347663/218348006-0ec6c493-c202-487a-a5cd-62a5309adf7f.png">
<img width="778" alt="스크린샷 2023-02-13 오전 9 49 06" src="https://user-images.githubusercontent.com/85347663/218348012-5c1b0a06-1b9c-4877-87c2-59d710fe9ceb.png">

**Comment by tadashi-aikawa** [comment]
@young5lee 
Thank you for details!

Its behavior is as expected.

https://github.com/tadashi-aikawa/obsidian-various-complements-plugin/releases/tag/5.8.0

> Don't show suggestions in the `alias` or `aliases` front matter

**Comment by young5lee** [comment]
Oh my God, that was my mistake.
thank you
