### ISSUE TITLE
confused about「current vault complement」

### ISSUE THREAD

**Issue by jisidehuli** [tadashi-aikawa/obsidian-various-complements-plugin#202]
when i open the 「current vault complement 」,i always met the question that can't show the correct suggestion i want.
for example:
when i type 「丙日主 bing3 ri4 zhu3」,i'm wondering it could suggest some information like the pic_1 left, but it show me thing about 「主 zhu4」. 
the status bar shows there are more than 24k complements in my vault ,but i don't know what they are,  even i choose partial it didn't show me the suggestion i wanted.

![image](https://user-images.githubusercontent.com/39455147/218431641-f3b0b079-2081-43d7-ad2e-dda97fa90fb7.png)

setting are showed as below:
`{
    "version": "7.3.0",
    "mobile": false,
    "settings": {
        "strategy": "chinese",
        "matchStrategy": "partial",
        "maxNumberOfSuggestions": 5,
        "maxNumberOfWordsAsPhrase": 5,
        "minNumberOfCharactersTriggered": 0,
        "minNumberOfWordsTriggeredPhrase": 1,
        "complementAutomatically": true,
        "delayMilliSeconds": 0,
        "disableSuggestionsDuringImeOn": false,
        "insertAfterCompletion": true,
        "firstCharactersDisableSuggestions": ":/^",
        "showMatchStrategy": true,
        "showComplementAutomatically": true,
        "showIndexingStatus": true,
        "descriptionOnSuggestion": "Full",
        "selectSuggestionKeys": "Enter",
        "additionalCycleThroughSuggestionsKeys": "None",
        "disableUpDownKeysForCycleThroughSuggestionsKeys": false,
        "openSourceFileKey": "None",
        "propagateEsc": false,
        "enableCurrentFileComplement": true,
        "currentFileMinNumberOfCharacters": 0,
        "onlyComplementEnglishOnCurrentFileComplement": false,
        "enableCurrentVaultComplement": true,
        "currentVaultMinNumberOfCharacters": 0,
        "includeCurrentVaultPathPrefixPatterns": "",
        "excludeCurrentVaultPathPrefixPatterns": "",
        "includeCurrentVaultOnlyFilesUnderCurrentDirectory": false,
        "enableCustomDictionaryComplement": false,
        "customDictionaryPaths": "https://raw.githubusercontent.com/first20hours/google-10000-english/master/google-10000-english-no-swears.txt",
        "columnDelimiter": "Tab",
        "customDictionaryWordRegexPattern": "",
        "delimiterToHideSuggestion": "",
        "delimiterToDivideSuggestionsForDisplayFromInsertion": "",
        "caretLocationSymbolAfterComplement": "",
        "displayedTextSuffix": " => ...",
        "enableInternalLinkComplement": true,
        "suggestInternalLinkWithAlias": false,
        "excludeInternalLinkPathPrefixPatterns": "",
        "enableFrontMatterComplement": true,
        "frontMatterComplementMatchStrategy": "inherit",
        "insertCommaAfterFrontMatterCompletion": false,
        "intelligentSuggestionPrioritization": {
            "maxDaysToKeepHistory": 30,
            "maxNumberOfHistoryToKeep": 0
        },
        "showLogAboutPerformanceInConsole": false,
        "selectionHistoryTree": null
    }
}`

and i'm wondering whether it's my settings or files that makes that problems. For videos about settings are lacks, i can only looking for u help. 😩

**Comment by jisidehuli** [comment]
![image](https://user-images.githubusercontent.com/39455147/218432638-7764a00f-8bc0-4397-be74-714e4aa17ba2.png)
the pic of status bar

**Comment by tadashi-aikawa** [comment]
@jisidehuli 
I could reproduce your situation. And your settings would be correct.

At the end of the investigation, I found that the Chinese tokenizer tokenized "丙日主" as "丙", "日" and "主". Unfortunately, It would be difficult for me to fix it even if the tokenizer did the wrong behavior.

```
[onTrigger] tokens is 丙,日,主
plugin:various-complements:4219 [onTrigger] currentTokens is [{"word":"丙日主 ","offset":0},{"word":"日主 ","offset":1},{"word":"主 ","offset":2}]
```

Another case

```
[onTrigger] tokens is 今天,从,早上,开始,就,很,冷,，,但,城市,里,到处,都,是,自行车,,
plugin:various-complements:4219 [onTrigger] currentTokens is [{"word":"都是自行车,","offset":17},{"word":"是自行车,","offset":18},{"word":"自行车,","offset":19}]
plugin:various-complements:4219 [onTrigger] currentToken is 都是自行车,
```

**Comment by tadashi-aikawa** [comment]
This issue will be closed for now, as there have been no comments from visitors for a month.
