### ISSUE TITLE
Option to disable completion on mobile only?

### ISSUE THREAD

**Issue by lebigot** [tadashi-aikawa/obsidian-various-complements-plugin#205]
On my phone (iPhone 13 Pro), Various Complements, when displaying the list of suggestions, pushes the cursor to the very top of the screen. This is doubly impractical:

1) My keyboard already gives me suggestions.
2) I lose track of the context of what I am writing (especially of what I just wrote).

Is there a way of disabling auto-completion on mobile _only_? Having this option would be very useful.

PS: I tried to activate "Disable suggestion during IME on": while I have no idea what this refers to (Googling IME didn't help), I tried it but it didn't do anything.

**Comment by tadashi-aikawa** [comment]
Hi, @lebigot :)

> Is there a way of disabling auto-completion on mobile only?

Unfortunately, no. But it would be possible to implement it.

By the way, can't you disable completion only on mobile using different settings from the desktop?

**Comment by tadashi-aikawa** [comment]
Thanks! I got it 👍

**Comment by mariomui** [comment]
@tadashi-aikawa how do you want this implemented btw?
I also want to disable it but via a command. I want to manually turn it on.

My idea is this.

Disable Various Complements  
Mobile [x]. [] 
Desktop [x] [ ]
brackets represent  a toggle switch
default is that it is enabled for both.

**Comment by tadashi-aikawa** [comment]
@mariomui 
I will add a "Disable on mobile" option.

I think we can use the [Toggle Complement automatically](https://tadashi-aikawa.github.io/docs-obsidian-various-complements-plugin/3.%20Commands/%F0%9F%8E%AEToggle%20Complement%20automatically/) option when we don't want to show suggestions automatically.

**Comment by tadashi-aikawa** [comment]
@lebigot 
Released in [8.1.0-beta3](https://github.com/tadashi-aikawa/obsidian-various-complements-plugin/releases/tag/8.1.0-beta3) 🚀 

![image](https://user-images.githubusercontent.com/9500018/224475604-eb99b083-e530-4bae-8658-2ed5d72666a2.png)

If you use [BRAT](https://github.com/TfTHacker/obsidian42-brat), please confirm whether it works as you expected.

**Comment by tadashi-aikawa** [comment]
Released in [8.1.0](https://github.com/tadashi-aikawa/obsidian-various-complements-plugin/releases/tag/8.1.0) 🚀

**Comment by lebigot** [comment]
Great, thanks!
