### ISSUE TITLE
[FR] Include fuzzy matching for diacritics

### ISSUE THREAD

**Issue by zanodor** [tadashi-aikawa/obsidian-various-complements-plugin#211]
Greetings,

I was happy to see you added support for fuzzy matching.  
I am using a native language (Hungarian) that has a lot of compound words, accented characters and agglutinations.  

It would be a nice improvement to have the plugin look for matches across a range of similar sounds/letters: `aáäā` etc., and the same for e, i, o, u (including ü, ű, of course).  

Thus, if I write `korny`, `környezet` would pop up, for instance.  

Excited for future implementations of this.  

ありがとう

Cheers,

Zan

**Comment by tadashi-aikawa** [comment]
Thank you for your FR, @zanodor :)

Your suggestion looks good. I'll implement it by adding options if there is no or little performance degrade 👍

**Comment by tadashi-aikawa** [comment]
@zanodor 
I have released in [obsidian-various-complements-plugin-beta v8.1.0-beta1](https://github.com/tadashi-aikawa/obsidian-various-complements-plugin/releases/tag/8.1.0-beta1) 🚀 

If you use [BRAT](https://github.com/TfTHacker/obsidian42-brat), please confirm whether it works as you expected. 

![image](https://user-images.githubusercontent.com/9500018/222941562-c3df480e-d994-46ea-bb00-f4069a795b83.png)

**Comment by tadashi-aikawa** [comment]
No, there is not.

If you want it, please create a new issue. But users should set all the patterns they want to use.

**Comment by tadashi-aikawa** [comment]
Released in [8.1.0](https://github.com/tadashi-aikawa/obsidian-various-complements-plugin/releases/tag/8.1.0) 🚀
