### ISSUE TITLE
Results with fuzzy match feature turned on should be topped by exact match

### ISSUE THREAD

**Issue by zanodor** [tadashi-aikawa/obsidian-various-complements-plugin#213]
I don't know the proper computer term for this but the results should come in in order of how exact the matches are.  
So for example, in the following attachment, the exact match is down in fourth slot for no reason (I can't see by what fuzzy rule those three finds come in those top positions, either):  
![See here](https://i.imgur.com/8OMKvWN.png)  

Cheers

**Comment by tadashi-aikawa** [comment]
Ah.. that is an special case.

Various complements are always before the result of [phrase-completion](https://tadashi-aikawa.github.io/docs-obsidian-various-complements-plugin/4.%20Options/4.1.%20Main/%E2%9A%99%EF%B8%8FMax%20number%20of%20words%20as%20a%20phrase/) than word-completion.

![image](https://user-images.githubusercontent.com/9500018/222935279-a98ffa13-7855-459a-8d09-8e6c0ba95d27.png)

However, as you said, it is not ideal. So I want to give it a try 👍

**Comment by tadashi-aikawa** [comment]
@zanodor 
I have released in [obsidian-various-complements-plugin-beta v8.1.0-beta1](https://github.com/tadashi-aikawa/obsidian-various-complements-plugin/releases/tag/8.1.0-beta1) 🚀 

If you use [BRAT](https://github.com/TfTHacker/obsidian42-brat), please confirm whether it works as you expected.

**Comment by tadashi-aikawa** [comment]
Released in [8.1.0](https://github.com/tadashi-aikawa/obsidian-various-complements-plugin/releases/tag/8.1.0) 🚀
