### ISSUE TITLE
[FR] "Front matter complement": Tags as indented list

### ISSUE THREAD

**Issue by avirosso** [tadashi-aikawa/obsidian-various-complements-plugin#214]
Thanks for your great plugin!

Regarding "Front matter complement": I (and probably many others too) write my tags not 'in a single line seperated by commas' but as 'indented list' (two spaces, dash, another space followed by the tag name):

```
tags:
  - recipe
  - cooking
```

If I use the plugin, my tag structure unfortunately is changed to 

```
tags: [recipe, cooking]
```

It would be great, if there would be an option (in settings) to use/leave the tag structure as 'indented list'! (I use many long/nested tags, so the 'indented structure' is much clearer and easier to handle in search/replace etc)

Thanks in advance!

**Comment by tadashi-aikawa** [comment]
Hi, @avirosso :)

Unfortunately, I couldn't reproduce it. Could you tell me the reproduction steps in the sandbox vault?

https://user-images.githubusercontent.com/9500018/223424904-8636c25e-3856-4925-81fc-e78074b2738f.mp4

**Comment by avirosso** [comment]
I have to apologize! I found out that the (recently added) plugin 'Metadata Menu' changed the frontmatter lists to arrays (not your Plugin Various Complements).

Thanks for the efforts and sorry for having stolen your time!

**Comment by tadashi-aikawa** [comment]
@avirosso 
I’m glad to hear that! 😄
