### ISSUE TITLE
Automatic Note Linking from Pasting (and voice to text, ongoing writing) with no confirm

### ISSUE THREAD

**Issue by LaureanoBlonsky** [tadashi-aikawa/obsidian-various-complements-plugin#215]
Hi, 

  I love this plugin! But there is an awesome feature that lacks:

  I dictate a lot with the stock Android's "voice to text" tool. I would love to have an option that makes it possible to automatically create links to existent notes when a word matches, without having to confirm it. 

  For example, if Im talking to the phone "...so Bulgaria is one of the oldest countries on Europe..." I want to have Bulgaria and Europe linked to pre existent notes (if there are) automatically (select the first match, if many). At the moment it doesn't work, because the plugin expects you to confirm it with Enter or with a click/touch.

  It should work for pasting text from clipboard too.

  Thanks!!

Lau.

**Comment by tadashi-aikawa** [comment]
Hi, @LaureanoBlonsky :)

I understand your requirements. However, I think that feature is a bit out of the mainstream of this plugin and seems difficult because this plugin is for auto-completion, not a linter.

Best regards.
