### ISSUE TITLE
无法正常启用中文支持

### ISSUE THREAD

**Issue by injoylin** [tadashi-aikawa/obsidian-various-complements-plugin#217]
问题：无法启用中文支出
打印信息：cedict_ts.u8 doesn't exist in./cedict_ts.u8

1. cedict_ts.u8文件已经放置了目录，无效
2. 出现问题先改成默认，再改成中文可以生效，但再次启动ob则失效

**Comment by tadashi-aikawa** [comment]
This issue will be closed for now, as there have been no comments from visitors for a month.

P.S. If you need help, please rewrite it in English because I can hardly read & write Chinese, sorry.
