### ISSUE TITLE
[Feature Request] Custom Dictionary → Render Markdown and HTML Tags

### ISSUE THREAD

**Issue by FelipeRearden** [tadashi-aikawa/obsidian-various-complements-plugin#220]
Hello again @tadashi-aikawa !!!!!

My FR is simple to explain: would be amazing if we could render **html tags** and **markdown syntax** inside `.various-complements__suggestion-item > div {
}`

🆘 **Important**: My idea is to apply the render when a custom dictionary suggestion HAS an **alias**  (more below)

📸 Like this setup 

![A274F7B8-FDE4-48A8-8E2F-E2D54A7CAA99](https://user-images.githubusercontent.com/85180696/230725907-4732f440-cd86-4814-9782-8ff806e322bc.jpeg)

### Why Are you Asking for this Feature

I would like to create VC suggestion like this mock up...

![294D2CEE-7512-4AC5-AA21-0B7F20A98406](https://user-images.githubusercontent.com/85180696/230725879-6d3614e3-2a70-4074-a0de-6881bb093a92.jpeg)

My idea is to use a html tag like `<q id=@@@>` for example and create a css snippet with lucide icons (Obsidian standard icons)

**⭘** CSS Snippet

```css
q#icon01:after {
content: url();
}
```

**⭘** VC Custom Dictionary entry: 

```
꜔<q id=icon01></q>⦊⦊⦊Lorem Ipsum		nnn
꜔<q id=icon02></q>⦊⦊⦊Lorem Ipsum		nnn
```
---

Thanks for reading this !!!!! I hope you like my suggestion 🙏 🙏 🙏

Let me know if you need more information !!!

It's so good to talk with you again 💬

Have a great day 🌞

**Comment by tadashi-aikawa** [comment]
Hi, @FelipeRearden :)

It seems pretty exciting!😄 I'll try to implement it 👍

**Comment by FelipeRearden** [comment]
> It seems pretty exciting!😄 

Hello @tadashi-aikawa !!!!

I knew you would like this feature !!!!!!!

> I'll try to implement it 👍 

Good luck @tadashi-aikawa !!!! I hope you find a solution for this feature 🙏🙏🙏

Have a great day ☀️

**Comment by tadashi-aikawa** [comment]
Hi. I decided to close this issue because it is hard to implement for security reasons.

Best regards.

**Comment by FelipeRearden** [comment]
> Hi. I decided to close this issue because it is hard to implement for security reasons.
> 
> 
> 
> Best regards.

Hi @tadashi-aikawa !!!

Okay, thanks for trying :) 

Best regards. 
Have a great day.
