### ISSUE TITLE
[Feature Request] Disable Tab key trigger for show suggestions and Consistent Home/End Keys

### ISSUE THREAD

**Issue by woshitoutouge** [tadashi-aikawa/obsidian-various-complements-plugin#221]
1. Disable Tab key trigger for show suggestions

I often use Tab key to indent, but it always trigger show suggestions (depend on the cursor location), which may cause accidental clicks, any way to disable the Tab trigger?

2. Consistent Home key and End key functionality

I hope the home key and the end key always move the cursor to the beginning and the end of the line, but when the suggestion box is triggered, the home key and the end key change to select the first and the last entry. Is there any way to solve it?

Thanks again for developing such a great plugin!

**Comment by tadashi-aikawa** [comment]
Hi, @woshitoutouge :)

> I often use Tab key to indent, but it always trigger show suggestions (depend on the cursor location), which may cause accidental clicks, any way to disable the Tab trigger?

No. But I agree with you. So I'll try to solve the problem.

> I hope the home key and the end key always move the cursor to the beginning and the end of the line, but when the suggestion box is triggered, the home key and the end key change to select the first and the last entry. Is there any way to solve it?

Perhaps, it is because of the latest Obsidian updating. I agree with your opinion, so I'll try to solve it, too.

**Comment by tadashi-aikawa** [comment]
@woshitoutouge 
Released in [v8.2.0-beta2](https://github.com/tadashi-aikawa/obsidian-various-complements-plugin/releases/tag/8.2.0-beta2) 🚀 

If you use [BRAT](https://github.com/TfTHacker/obsidian42-brat), please confirm whether it works as you expected.

**Comment by woshitoutouge** [comment]
@tadashi-aikawa That works perfectly as i wish! Apreciate your excellent work!

**Comment by tadashi-aikawa** [comment]
I found some more cases should be suppressed.

![2023-04-30-12-34-23](https://user-images.githubusercontent.com/9500018/235334249-01deead2-015b-43da-bb56-716beda8b310.gif)

I have succeeded in suppressing these cases and will in the next release.

**Comment by woshitoutouge** [comment]
Explicit trigger scenarios would be great!

**Comment by tadashi-aikawa** [comment]
Released in [v8.2.0](https://github.com/tadashi-aikawa/obsidian-various-complements-plugin/releases/tag/8.2.0) 🚀

**Comment by woshitoutouge** [comment]
after I updated OB, the pop-up box cannot be closed using left key, right key, home or end key... Plugin developers really have a tough job.

**Comment by tadashi-aikawa** [comment]
> after I updated OB, the pop-up box cannot be closed using left key, right key, home or end key...

I didn't reproduce it on Obsidian v1.3.0 and Various Complements v8.2.2.

**Comment by woshitoutouge** [comment]
@tadashi-aikawa hi, I reinstall ob (v1.3.0), reinstall the plugin (v8.2.2), and record my screen.
I found when press Left key, Right key and End key, the popup box don't disappear, Home key i'm not sure.

video:
https://github.com/tadashi-aikawa/obsidian-various-complements-plugin/assets/99337435/9de98f8d-3d03-4390-8d24-a3ccccab4634

plugin setting:
<img width="1279" alt="2023-05-12_220014" src="https://github.com/tadashi-aikawa/obsidian-various-complements-plugin/assets/99337435/87304cf4-08ea-492a-9839-660db7331fe5">

**Comment by tadashi-aikawa** [comment]
@woshitoutouge 
Thank you for your details :)

I could reproduce it. That should be a bug for Various Complements. If so, I'll fix it👍

**Comment by woshitoutouge** [comment]
@That was fast! really appreciate your work!
