### ISSUE TITLE
Internal link complement adds redundant alias

### ISSUE THREAD

**Issue by vanbang9710** [tadashi-aikawa/obsidian-various-complements-plugin#222]
A file named Aqua will be suggested as [[Aqua|Aqua]]

**Comment by tadashi-aikawa** [comment]
Hi, @vanbang9710 :)

Unfortunately, I couldn't reproduce it. Could you tell me the reproduction steps in the sandbox vault?

**Comment by vanbang9710** [comment]
Turning off "Insert an alias that is transformed from the displayed internal link" fixes this. I thought leaving the "Before" and "After" regex blank will have the same effect as turning it off

**Comment by tadashi-aikawa** [comment]
Thank you for your reply 👍

I could reproduce it with the following settings.

![image](https://user-images.githubusercontent.com/9500018/233762796-0a637f8c-d782-4eff-af08-d429ad5d5527.png)

> I thought leaving the "Before" and "After" regex blank will have the same effect as turning it off

That makes sense. It is not a bug but a specification.
