### ISSUE TITLE
Notes with special characters don't show up as suggestions

### ISSUE THREAD

**Issue by MMoMM-org** [tadashi-aikawa/obsidian-various-complements-plugin#223]
Hi, I have notes which start with §

Those will not show up as suggestions either with typing the § or without.

**Comment by tadashi-aikawa** [comment]
Hi, @MMoMM-org :)

Unfortunately, I couldn't reproduce it. Could you tell me the reproduction steps in the sandbox vault?

![image](https://user-images.githubusercontent.com/9500018/234606586-85811329-9e7e-4b7c-a2de-9c81244cdaaf.png)

**Comment by MMoMM-org** [comment]
Try it without the starting §...  for example if I have a document §Test and a document Test and I type tst only Test shows up. I would assume that it would show both documents.

**Comment by tadashi-aikawa** [comment]
That is as expected if [Match strategy](https://tadashi-aikawa.github.io/docs-obsidian-various-complements-plugin/4.%20Options/4.1.%20Main/%E2%9A%99%EF%B8%8F%20Match%20strategy/) is `prefix`.

**Comment by tadashi-aikawa** [comment]
This issue will be closed for now, as there have been no comments from visitors for a month.
