### ISSUE TITLE
[Question] How to Pre-populate Items with Aliases Correctly in Custom Dictionary

### ISSUE THREAD

**Issue by zanodor** [tadashi-aikawa/obsidian-various-complements-plugin#224]
Hi Tadashi,

I am populating my custom dictionary file from the outside complete with aliases. In order to know how to do that, I first tried creating items through Obsidian/VC and seeing in my dictionary file what pattern is used to store the main entry and its aliases.  

What I found is that the first alias follows the main entry by two tabs and the others are separated by one tab.  

My question:  
Am I counting the tabs/spaces correctly (it is difficult to see properly)?
Is this how it is intended and taken to be a rule and can I take this for granted it will be future-proof in later releases?  
Are there other ways to do it or would you consider a more easily followed rule? E.g. 
`Item\nAlias1\nAlias2\nAlias3\nAlias99`

Thanks in advance

Cheers,
Z.

**Comment by tadashi-aikawa** [comment]
Hi, @zanodor :)

> What I found is that the first alias follows the main entry by two tabs and the others are separated by one tab.

Please see the "Custom dictionary formats". The second column is not an alias but a description.

https://tadashi-aikawa.github.io/docs-obsidian-various-complements-plugin/5.%20Terms/%F0%9F%93%9A%20Custom%20dictionary%20formats/

> Are there other ways to do it or would you consider a more easily followed rule?

You could set "Column delimiter".

https://tadashi-aikawa.github.io/docs-obsidian-various-complements-plugin/4.%20Options/4.6.%20Custom%20dictionary%20complement/%E2%9A%99%EF%B8%8F%20Column%20delimiter/

**Comment by tadashi-aikawa** [comment]
> I think I have waited enough to let the index refresh itself...?

Yes. Please see ["When does it update tokens?"](https://tadashi-aikawa.github.io/docs-obsidian-various-complements-plugin/1.%20Features/Custom%20dictionary%20complement/#when-does-it-update-tokens).

> I showcased your plugin (again) on the Obs forum:

Thanks! 😍

**Comment by tadashi-aikawa** [comment]
Works fine on my sandbox environment 🤔 

![2023-05-04-14-42-08](https://user-images.githubusercontent.com/9500018/236120760-89a9e981-3c8b-412d-990a-7c32092ccb94.gif)
