### ISSUE TITLE
[FR] add a Ctrl+Esc shortcut key to pause the use of the plugin

### ISSUE THREAD

**Issue by TheGodOfKing** [tadashi-aikawa/obsidian-various-complements-plugin#226]
You should add a Ctrl+Esc shortcut key to pause the use of the plugin. 
Even if you restart Obsidian, it won’t change until you press the shortcut key again to resume use. 
I only use this plugin when embedding code blocks in Obsidian. I don’t want to use it at other times. 
Although pressing Esc can return to normal now, it’s not permanent. 
When I enter text again, the pop-up window will appear again, which greatly affects my writing experience. 
Thank you for your help!!!!!

**Comment by tadashi-aikawa** [comment]
Hi, @TheGodOfKing :)

I think you should use the following option.

https://tadashi-aikawa.github.io/docs-obsidian-various-complements-plugin/3.%20Commands/%F0%9F%8E%AE%20Toggle%20Complement%20automatically/

**Comment by TheGodOfKing** [comment]
> Hi, @TheGodOfKing :)
> 
> I think you should use the following command.
> 
> https://tadashi-aikawa.github.io/docs-obsidian-various-complements-plugin/3.%20Commands/%F0%9F%8E%AE%20Toggle%20Complement%20automatically/

- Yes, I found this option and set the shortcut. 
- ![image](https://github.com/tadashi-aikawa/obsidian-various-complements-plugin/assets/32014745/6d2da6c1-e499-42c5-b650-366440d04c3c)

- Now the plugin is working very well. 
- Thank you for your help !!!

**Comment by tadashi-aikawa** [comment]
I’m glad to hear that!
