### ISSUE TITLE
[Question] Can URLs be excluded from a fuzzy match search (strategy = partial).

### ISSUE THREAD

**Issue by MDsza** [tadashi-aikawa/obsidian-various-complements-plugin#227]
**Example**: searching for 'hallo' offers - as one of the results - a part of a encypted link in my notes, which should not be shown as an fuzzy search result: 

**Result in the dropdown list of the Various Complements - Plugin**  after having typed 'hallo' :QUFFLUhqbjd4TXg0OU5LVGd5UEdPZHZSY0lOaXpHVFRnQXxBQ3Jtc0trSWZTQ19USWI4YWw2YklrNjdybWlzRmhscERrcVJOZERsbFFyc2NyU3ZDcGJLM3Q1M1FSNjZWNjAzWFF2RUJDQW1rNmtlYTA2UndxU3B6TGl3Z2l6Q01idElFa09iY2k4WHUzZm9LYUROUHF1OHJFaw&q 

**Link in the Obsidian Note** = [https://www.physik-im-advent.de](https://www.youtube.com/redirect?event=video_description&redir_token=QUFFLUhqbkNkNjBiSmdLUEJlUHpzbW1Ua25Mc01Fek9uZ3xBQ3Jtc0ttOTVoSXRaYlVuaHFBMVlCb1h5VlBvaUg5aXQxNzdlWG1DLThGUTBGVW5jY29JdWtaXzBrVHhGUF9QOTg5TmJCYnVIX1UyY3g3YXRQLUM2R25QQ1prN2lzOXBLOXVOOUJNbkVKNG82UUc1elB4REFtZw&q=https%3A%2F%2Fwww.physik-im-advent.de%2F&v=kwzcmR1i80M)

**Exact Link** = https://www.youtube.com/redirect?event=video_description&redir_token=QUFFLUhqbkNkNjBiSmdLUEJlUHpzbW1Ua25Mc01Fek9uZ3xBQ3Jtc0ttOTVoSXRaYlVuaHFBMVlCb1h5VlBvaUg5aXQxNzdlWG1DLThGUTBGVW5jY29JdWtaXzBrVHhGUF9QOTg5TmJCYnVIX1UyY3g3YXRQLUM2R25QQ1prN2lzOXBLOXVOOUJNbkVKNG82UUc1elB4REFtZw&q=https%3A%2F%2Fwww.physik-im-advent.de%2F&v=kwzcmR1i80M)

**Comment by EricEWeir** [comment]
I’d like to be able to do this, too.

**Comment by MDsza** [comment]
@tadashi-aikawa: WOW, what for a fast and great reaction from your side. I am looking forward for this feature, because it will clean up all the fuzzy search results for so many users of your fantastic obsidian plugin. Your plugin still accelerates my daily writing and working with Obsidian to a whole new level. Thank you very much for your work and implementing this useful feature, that will enable ignoring specific patterns during indexing. Best, Wolfgang (from Switzerland)

**Comment by tadashi-aikawa** [comment]
@MDsza 
I have released [Another Quick Switcher v8.10.0-beta3](https://github.com/tadashi-aikawa/obsidian-another-quick-switcher/discussions/167), a plugin I develop. This version supports processes that suppress results based on the score of fuzzy matching.

I believe that if we add a similar feature to the Various Complements plugin, we could reduce the display of low match-rate noise, such as URLs. What do you think?

**Comment by MDsza** [comment]
@tadashi-aikawa: Absolutely, this should definitively solve this issue and clean up effectively the fuzzy search results (with a little bit of trial and error, finding the best score of fuzzy matching what works best for everyones dataset).

**Comment by EricEWeir** [comment]
I agree. That would be very helpful.I have a question though. I turned to Various Compliments when it appeared that Obsidian would not offer suggestions when creating a markdown note. I am curious about the other ways Various Compliments are used?———————————Eric Weir Atlanta, GA  USA“It has all been combustion.”- W.G. SebaldOn May 14, 2023, at 2:12 AM, Tadashi Aikawa ***@***.***> wrote:﻿
@MDsza
I have released Another Quick Switcher v8.10.0-beta3, a plugin I develop. This version supports processes that suppress results based on the score of fuzzy matching.
I believe that if we add a similar feature to the Various Complements plugin, we could reduce the display of low match-rate noise, such as URLs. What do you think?

**Comment by tadashi-aikawa** [comment]
@MDsza @EricEWeir 
Released in [v8.3.0](https://github.com/tadashi-aikawa/obsidian-various-complements-plugin/releases/tag/8.3.0) 🚀

**Comment by tadashi-aikawa** [comment]
@EricEWeir 

> I am curious about the other ways Various Compliments are used?

I use the following features.

- Current file complement
- Custom dictionary complement
- Internal link complement
- Front matter complement

For details of the features, please below official document.

https://tadashi-aikawa.github.io/docs-obsidian-various-complements-plugin/#features
