### ISSUE TITLE
Prevent complementing while composing text?

### ISSUE THREAD

**Issue by EricEWeir** [tadashi-aikawa/obsidian-various-complements-plugin#228]
With just Complement internal links enabled and Complement automatically turned on I get suggestions while composing a note. I find this very distracting. Can it be prevented.

**Comment by tadashi-aikawa** [comment]
Thank you for your details.

I want to know the concrete situation. Could you tell me the following things?

- Reproduction steps in the sandbox vault
- Images or movies (or gif)
- What is the expected result?
- What was the actual result?

**Comment by EricEWeir** [comment]
I have been unaware until just now that there are two “complement automatically” settings: “complement automatically” and “show complement automatically.” 

And when combined with the “internal link complement they produce different results. In that case only “complement automatically” causes suggestions to be offered when composing a note as well as when creating a link. Which is the result I want to avoid. 

Actually that result is also avoided if neither “complement automatically” nor “show complement automatically” is enabled. If just “internal link complement” is enabled, complements are offered only when creating a link.

 So, the undesirable result can be avoided after all.

**Comment by tadashi-aikawa** [comment]
>  In that case only “complement automatically” causes suggestions to be offered when composing a note as well as when creating a link. 

I can't image the above situation. So please share the following resources.

> - Reproduction steps in the sandbox vault
> - Images or movies (or gif)

**Comment by tadashi-aikawa** [comment]
This issue will be closed for now, as there have been no comments from visitors for a month.
