### ISSUE TITLE
Removing complements with periods

### ISSUE THREAD

**Issue by Caffa** [tadashi-aikawa/obsidian-various-complements-plugin#229]
![image](https://github.com/tadashi-aikawa/obsidian-various-complements-plugin/assets/1797721/315dc1bf-026c-4749-a863-c740f4887ba1)
Hi, so the problem is that I want the words with periods so 'you.' and 'you...' to be removed because I only need the word to be complemented 'you'

**Comment by tadashi-aikawa** [comment]
Thank you, @Caffa :)

It would be a bug at the v8.2.0. I'll fix it 👍

**Comment by tadashi-aikawa** [comment]
@Caffa 
Fix in [v8.2.2](https://github.com/tadashi-aikawa/obsidian-various-complements-plugin/releases/tag/8.2.2) 🚀
