### ISSUE TITLE
Front matter complement stopped working after Update to 8.2.2

### ISSUE THREAD

**Issue by jayambede** [tadashi-aikawa/obsidian-various-complements-plugin#230]
Hello!

Thank you for this very helpful plugin. I'm using it virtually since I'm using Obsidian.

But since the Update to Version 8.2.2 the Front matter Complement stopped working. This has happened before, but then I was able to get it working again by turning settings on and off or by restarting once while turning of the plugin entirely and turning it on again  (works nearly every time ;-)). But this time I can't get the front matter complement to work. It worked fine before the update to 8.2.2.
Settings are correct in the data.json, and the histories.json contains the values used in the front matter before the update.

I would appreciate any help.

Thanks a lot, Jay

**Comment by tadashi-aikawa** [comment]
Hi, @jayambede :)

Unfortunately, I couldn't reproduce it. Could you tell me the reproduction steps in the sandbox vault?

![image](https://github.com/tadashi-aikawa/obsidian-various-complements-plugin/assets/9500018/5bb43c80-f814-442a-9527-04242a1fa13c)

**Comment by jayambede** [comment]
It's weird. I tried with two new notes in the sandbox vault, and it worked. I tried in my current vault, and it didn't. I de- and reinstalled the plugin, but still it doesn't work. But it has worked fine until the last update. 

---

Now I've been fiddling with deactivating and reactivating various plugins, and it works again. 
Don't know how that was, changes in the settings of the plugin changed nothing, deactivating and reactivating plugins that work on the front matter (like Metadata menu), did. Could be a conflict in there, (and I suspect Metadata menu), but now it's solved. 

Sorry for bothering you ...

**Comment by jayambede** [comment]
Still, I would remark that, now that I think of it, there could indeed be a conflict with Metadata Menu, since both - by design - overlap in monitoring the same set of data (be it frontmatter, or main text (at least when it comes to inline data fields)). 

Maybe, IMHO, it would be an idea, to coordinate somehow with the creator of Metadata Mneu to avoid such conflicts ... 

Just a thought.

Sit: Thank you very much for this helpful plugin!!

Jay

**Comment by tadashi-aikawa** [comment]
@jayambede 
Thank you for the update. The following issue might be able to help you.

https://github.com/tadashi-aikawa/obsidian-various-complements-plugin/issues/209

**Comment by tadashi-aikawa** [comment]
This issue will be closed for now, as there have been no comments from visitors for a month.
