### ISSUE TITLE
Bug: Underscores wrongly considered part of a word

### ISSUE THREAD

**Issue by chrisgrieser** [tadashi-aikawa/obsidian-various-complements-plugin#231]
I prefer to use underscores `__` instead of `**` as markup for bold text. However, doing so leads to a small bug when the "Current File Complement"  Setting has been enabled:

As opposed to `*`, the `_` character is considered part of the word and therefore picked up by Various Complements, resulting in undesired suggestions:

![image](https://github.com/tadashi-aikawa/obsidian-various-complements-plugin/assets/73286100/33f668b2-b3e2-4a87-ac10-1e70ca1c9ae9)

---

I think that's due to CodeMirror considering `_` part of a word, and removing underscores from Current-File-Complements would probably suffice to fix this issue?

**Comment by tadashi-aikawa** [comment]
Hi, @chrisgrieser :)

I could reproduce it. I'll fix it 👍

**Comment by tadashi-aikawa** [comment]
@chrisgrieser 
Fixed in [v8.3.1](https://github.com/tadashi-aikawa/obsidian-various-complements-plugin/releases/tag/8.3.1) 🚀

**Comment by tadashi-aikawa** [comment]
P.S.

> I think that's due to CodeMirror considering _ part of a word

This plugin does not use the tokenizer of CodeMirror. Instead, I've created custom tokenizers for each language.

**Comment by chrisgrieser** [comment]
Thank you for the quick fix 🚀
