### ISSUE TITLE
bug: Stuck bugs

### ISSUE THREAD

**Issue by hanliren** [tadashi-aikawa/obsidian-various-complements-plugin#233]
About the lag in about 10S after opening the software nothing can be operated.

Windows platform, obsidian version is 1.3.5 latest.

And, check the task manager of Windows, it shows that it will occupy a thread, full 10S.

**Comment by tadashi-aikawa** [comment]
I have never had such a problem in my environment, please give me a reproducible procedure to determine that Various Complements is the cause.

**Comment by tadashi-aikawa** [comment]
This issue will be closed for now, as there have been no comments from visitors for a month.
