### ISSUE TITLE
[FR] Disable Intelligent Suggestion Prioritization

### ISSUE THREAD

**Issue by mdSlash** [tadashi-aikawa/obsidian-various-complements-plugin#234]
Hi there, thanks for this awesome plugin. 
I don't wanna keep a history of my snippets. Could you add a button to disable it?

**Comment by tadashi-aikawa** [comment]
Hi, @MDslash :)

I'll consider it 👍

**Comment by tadashi-aikawa** [comment]
I have released it in the [v9.0.0-beta5](https://github.com/tadashi-aikawa/obsidian-various-complements-plugin/releases/tag/9.0.0-beta5) 🚀 

If you use BRAT, I would appreciate it if you could check it out before the official release.

**Comment by mdSlash** [comment]
> If you use BRAT, I would appreciate it if you could check it out before the official release.

It worked, thanks!
