### ISSUE TITLE
Dash (-) "breaks" fuzzy "link complement"

### ISSUE THREAD

**Issue by lebigot** [tadashi-aikawa/obsidian-various-complements-plugin#236]
When a link contains a dash (-), the "link complement" fuzzy matching seems to _require_ the dash, and this is cumbersome.

For example, if a note is entitled "Jean-Paul Gaultier", typing "jpg" won't trigger the link complement. Instead, one has to type "j-pg", which is not convenient.

Could non-alphanumeric characters stop blocking the fuzzy matching, for link complements? That would make typing faster (otherwise, one has to go fetch the "-" key on the keyboard for all note titles with a dash).

Thanks!

**Comment by tadashi-aikawa** [comment]
@lebigot 
You should not have to type dashes.

![image](https://github.com/tadashi-aikawa/obsidian-various-complements-plugin/assets/9500018/926ff127-9940-4c8c-a254-71b1b9f8615e)

You will show the suggestion if you decrease the `Min fuzzy match score` from 0.5 (default) to 0.1.

![image](https://github.com/tadashi-aikawa/obsidian-various-complements-plugin/assets/9500018/f9ece359-4d04-4a43-afc4-3e4dd83b44e3)

![image](https://github.com/tadashi-aikawa/obsidian-various-complements-plugin/assets/9500018/26cf2c8d-f872-4af9-a3eb-7622ac8c67bc)

**Comment by lebigot** [comment]
Decreasing the "Min fuzzy match score" like you indicated did work. 👍 Thanks a lot!
