### ISSUE TITLE
No ("link complement") completion in check lists?

### ISSUE THREAD

**Issue by lebigot** [tadashi-aikawa/obsidian-various-complements-plugin#237]
With "Internal link complement" activated, the feature doesn't work in a check list item.

Interestingly enough, the Boost Link Suggestion plugin suffers from a [similar problem](https://github.com/jglev/obsidian-boost-link-suggestions/issues/9#issuecomment-1606276005), where the plugin is not triggered as normal, inside check list items. Maybe it's related to a common underlying problem in Obsidian itself??

**Comment by tadashi-aikawa** [comment]
@lebigot 
Unfortunately, I couldn't reproduce it. Could you tell me the reproduction steps in the sandbox vault?

https://github.com/tadashi-aikawa/obsidian-various-complements-plugin/assets/9500018/6a550254-446a-4627-bc83-7c1053629125

**Comment by lebigot** [comment]
Thank you for your support.

I followed your (good) idea of trying with the Sandbox vault, and things worked, there—I should have done this first, sorry.

Now, you motivated me to investigate and I found the culprit: the Tasks plugin also offers a menu with suggestions, when its "Auto-suggest task content" option is on. It interferes with Various Complements. (The problem with Boost Link Suggestion I mentioned in the original post similarly disappears when disabling this option.)

Is there a way for plugins that suggest while typing to cohabitate peacefully? I'm not sure whether this would be fully practical, but interlacing the items from multiple plugins may be a reasonable option (for Obsidian itself, I guess)??

**Comment by tadashi-aikawa** [comment]
@lebigot 
As far as I know, Obsidian determines the priority of the autocomplete process according to the order in which plug-ins are loaded (often the same as the installation order). Unless that behavior changes, fine-tuning the plug-ins to co-exist will be tough.

The Various Complements plugin offers the following two settings, but it is impossible to prioritize Various Complements completions over other plugins unless the installation order is adjusted.

- [⚙️ First characters to disable suggestions \- Various Complements](https://tadashi-aikawa.github.io/docs-obsidian-various-complements-plugin/4.%20Options/4.1.%20Main/%E2%9A%99%EF%B8%8F%20First%20characters%20to%20disable%20suggestions/)
- [⚙️ Patterns to suppress trigger \- Various Complements](https://tadashi-aikawa.github.io/docs-obsidian-various-complements-plugin/4.%20Options/4.1.%20Main/%E2%9A%99%EF%B8%8F%20Patterns%20to%20suppress%20trigger/)

**Comment by tadashi-aikawa** [comment]
This issue will be closed for now, as there have been no comments from visitors for a month.
