### ISSUE TITLE
Fix for conflict with Obsidian Tasks plugin

### ISSUE THREAD

**Issue by Net-Slayer** [tadashi-aikawa/obsidian-various-complements-plugin#238]
I'm not sure where else to put this but...

This will prevent the Various Complements plugin from conflicting with entering task dates using Obsidian Tasks.
Add the following regex pattern to "Patterns to suppress trigger":

```
^\s*-\s{1}\[.\]\s+.*
```

I hope this helps others struggling with accidentally linking to daily notes!

**Comment by tadashi-aikawa** [comment]
Thank you! @Net-Slayer 👍
