### ISSUE TITLE
FR: Support for multi-word-completions

### ISSUE THREAD

**Issue by chrisgrieser** [tadashi-aikawa/obsidian-various-complements-plugin#24]
I noticed that one enters a phrase or term consisting of multiple words, the plugin still works nicely: `European Union`. So I was thinking of even using the plugin for some common phrases, too, for example these:

```
On the one hand, 
On the other hand,
```
However, they are not triggered on `On the` since the space in between resets the minimum length threshold.

I am wondering whether there is an elegant solution to keep the minimum threshold and still be able to autocomplete phrases like `On the one hand, `? 🤔

**Comment by tadashi-aikawa** [comment]
How about that when you input `onth`, it suggests `On the one hand` and `On the other hand` ?

In other words, multi-word like `On the one hand` is treated as `Ontheonehand` on the matching logic.

**Comment by chrisgrieser** [comment]
that kinda of works, but isn't a perfect solution. In my view, the value of autocomplete arises from the fact that you do not have to think about it, it just nicely works for you. Having to actively remember "The autocomplete I want is below the threshold, so I need to type it without spaces" probably defeats the purpose for that 🤔

**Comment by tadashi-aikawa** [comment]
I agree that `you do not have to think about it` is ideal.

However, I think `minimum length threshold` is not an important problem. It is an actual problem that it doesn't understand `On t` as a part of Idioms.

As far as I know, Even famous IDEs, like a VSCode, IntelliJ IDEA, seems not to be supported as an above feature. 🤔

**Comment by tadashi-aikawa** [comment]
I may came up with a good idea.. 💡

**Comment by tadashi-aikawa** [comment]
@chrisgrieser 
By the way, Inspired by your comment, I have implemented the below feature as an experiment.

![2021-11-21](https://user-images.githubusercontent.com/9500018/142764497-23ea3395-6270-4feb-9a75-ea8ce1774a69.gif)

It enables us not to remember whether it created one word as `*.md` or not :)

**Comment by chrisgrieser** [comment]
ooh, that is a killer feature, I assume many people are going to be thankful for :D

**Comment by FelipeRearden** [comment]
This a fantastic idea @tadashi-aikawa !!!!!!

**Comment by tadashi-aikawa** [comment]
If you use [BLAT](https://github.com/TfTHacker/obsidian42-brat), you can try the latest development version from `tadashi-aikawa/obsidian-plugin-dev-sandbox`. It is for me to verify on mobile (so, it is not stable.. 😅 )

**Comment by chrisgrieser** [comment]
I don't use Obsidian much on mobile, so I cannot really test mobile, sorry :(

**Comment by tadashi-aikawa** [comment]
Don't worry 👍 

BLAT is not only for mobile but also desktop, so if you are interested in the development version, please try it to use. (of course, if you want to :) )

**Comment by tadashi-aikawa** [comment]
That's what you mean 😄

**Comment by tadashi-aikawa** [comment]
@chrisgrieser @FelipeRearden 
I have created a new issue, https://github.com/tadashi-aikawa/obsidian-various-complements-plugin/issues/28#issue-1060190042 about above :)

**Comment by tadashi-aikawa** [comment]
I may have come up with a good idea again when I implemented #58 💡. It probably reduces performance several times; however, it may be handy for users, whether they use `Prefix` or `Partial`.

**Comment by eleanorkonik** [comment]
I came here to request this because I type so fast that autocompleting words like "obsidian" is of limited use, but I actually really love the autocomplete for "common phrases" that gmail does and having that in Obsidian would be awesome. I would love to urn off "single word completion" and just use phrases if that were an option; I've discovered that I really love this for things like:

![image](https://user-images.githubusercontent.com/75856959/149574874-fe83278a-a547-41ec-8939-2539d4d2528c.png)

Here's more about Google's [smart compose](https://www.buzzfeednews.com/article/venessawong/gmail-auto-complete-smart-compose-creepy-amazing) which I imagine is tricky to implement but would be _so cool_.

**Comment by tadashi-aikawa** [comment]
WIP/FYI

Prototype which supports only whitespace separated.

If it supports English only, it is not very difficult. But combining with tokenizers is difficult, especially CJK.

![2022-01-15](https://user-images.githubusercontent.com/9500018/149613326-cd62181d-c8b3-4d18-9f92-285327c2ceb4.gif)

**Comment by tadashi-aikawa** [comment]
Coming soon! It works on Japanese, too :)

https://user-images.githubusercontent.com/9500018/149619405-94ba566e-260b-4073-8487-7e1b36265b93.mp4

**Comment by tadashi-aikawa** [comment]
Added 2 options.

![image](https://user-images.githubusercontent.com/9500018/149624947-4202eb72-7e4b-4ec9-bd0e-0dd222583ff2.png)
![image](https://user-images.githubusercontent.com/9500018/149624953-8f93fdf8-f568-4e9c-b537-9099f5650eef.png)

It works as the follows.

![2022-01-15](https://user-images.githubusercontent.com/9500018/149625028-ae2d3b68-58fa-4251-acbd-7a8dbce5ed2a.gif)

**Comment by tadashi-aikawa** [comment]
Hi, @chrisgrieser @eleanorkonik, Thanks for your patience. It's time to release the big issue as beta :)

I have updated beta version to [obsidian-various-complements-plugin-beta v5.0.0-beta5](https://github.com/tadashi-aikawa/obsidian-various-complements-plugin-beta/releases/tag/5.0.0.beta5) 🚀 

If you use [BRAT](https://github.com/TfTHacker/obsidian42-brat), please try it 👍 

>  I would love to urn off "single word completion" and just use phrases 
@eleanorkonik 
You can ignore single word completion by specifying the `Min number of words for trigger` option to 2 or upper.

**Comment by eleanorkonik** [comment]
THIS IS SO COOL thank you!

**Comment by tadashi-aikawa** [comment]
I have updated beta version to [obsidian-various-complements-plugin-beta v5.0.0-beta6](https://github.com/tadashi-aikawa/obsidian-various-complements-plugin-beta/releases/tag/5.0.0.beta6) 🚀

**Comment by chrisgrieser** [comment]
got not time to betatest the next couple of days, but looking forward to it 👀

thank you so much for the implementation!

**Comment by tadashi-aikawa** [comment]
I have been using 5.0.0.beta every day this week and have found no bugs yet for now. Therefore I will release an official version in a few days :)

**Comment by tadashi-aikawa** [comment]
I started writing documentation for this plugin, and I will publish it with v5.0.0 simultaneously. So please wait for a little more :)

![image](https://user-images.githubusercontent.com/9500018/150641178-4520978f-81aa-4849-834e-24d397208cf0.png)

**Comment by tadashi-aikawa** [comment]
I did it! I am now starting to release `v5.0.0` ❤️ 

https://tadashi-aikawa.github.io/docs-obsidian-various-complements-plugin/

**Comment by tadashi-aikawa** [comment]
@chrisgrieser @eleanorkonik @FelipeRearden 
I have released to [v5.0.0](https://github.com/tadashi-aikawa/obsidian-various-complements-plugin/releases/tag/5.0.0) 🚀

Please confirm whether it works as you expected.

**Comment by chrisgrieser** [comment]
<img width="422" alt="Screenshot 2022-01-23 22 47 40" src="https://user-images.githubusercontent.com/73286100/150699236-210aab20-b83b-4386-9a09-d79d8ba6108f.png">

can confirm, it works for me :)

**Comment by tadashi-aikawa** [comment]
Thank you for your confirming!
