### ISSUE TITLE
Supporting new Obsidian properties with link suggestions

### ISSUE THREAD

**Issue by aravindk100** [tadashi-aikawa/obsidian-various-complements-plugin#242]
With front matter complement enabled, it suggests links as long as the link was filled once in front matter before. Is there a way to make it suggest links that are not yet in front matter, just like how the link complement works otherwise in the main text.

**Comment by tadashi-aikawa** [comment]
Hi, @aravindk100 :)

> With front matter complement enabled, it suggests links as long as the link was filled once in front matter before. 

This only shows the value of a previously entered property as a candidate for completion and does not suggest links.

>  Is there a way to make it suggest links that are not yet in front matter, just like how the link complement works otherwise in the main text.

No, there are not. Internal link complements on the front matter are too noisy that disturb select the property suggestion.

**Comment by tadashi-aikawa** [comment]
This issue will be closed for now, as there have been no comments from visitors for a month.
