### ISSUE TITLE
auto completion is not trigged when typing 

### ISSUE THREAD

**Issue by zxqcs** [tadashi-aikawa/obsidian-various-complements-plugin#247]
After I have installed this plugin and enable it,   I found that auto completion/suggestion is not trigged when typing. I wonder whether I should press some hotkey to trigger this function?

**Comment by tadashi-aikawa** [comment]
Hi, @zxqcs :)

> I should press some hotkey to trigger this function?

No, if you use default settings. 

Could you tell me your settings copied by the [Copy plugin settings](https://tadashi-aikawa.github.io/docs-obsidian-various-complements-plugin/3.%20Commands/%F0%9F%8E%AE%20Copy%20plugin%20settings/) command?

**Comment by zxqcs** [comment]
> Hi, @zxqcs :)
> 
> > I should press some hotkey to trigger this function?
> 
> No, if you use default settings.
> 
> Could you tell me your settings copied by the [Copy plugin settings](https://tadashi-aikawa.github.io/docs-obsidian-various-complements-plugin/3.%20Commands/%F0%9F%8E%AE%20Copy%20plugin%20settings/) command?
Hi, tadashi-aikawa, here is my settings copied by the "Copy plugin setting" command:
{
    "version": "8.4.1",
    "mobile": false,
    "settings": {
        "strategy": "default",
        "cedictPath": "./cedict_ts.u8",
        "matchStrategy": "prefix",
        "fuzzyMatch": true,
        "minFuzzyMatchScore": 0.5,
        "matchingWithoutEmoji": true,
        "treatAccentDiacriticsAsAlphabeticCharacters": false,
        "maxNumberOfSuggestions": 5,
        "maxNumberOfWordsAsPhrase": 3,
        "minNumberOfCharactersTriggered": 0,
        "minNumberOfWordsTriggeredPhrase": 1,
        "complementAutomatically": true,
        "delayMilliSeconds": 0,
        "disableSuggestionsDuringImeOn": false,
        "insertAfterCompletion": true,
        "firstCharactersDisableSuggestions": ":/^",
        "useCommonPrefixCompletionOfSuggestion": false,
        "patternsToSuppressTrigger": [
            "^~~~.*",
            "^```.*"
        ],
        "noAutoFocusUntilCycle": false,
        "showMatchStrategy": true,
        "showComplementAutomatically": true,
        "showIndexingStatus": true,
        "descriptionOnSuggestion": "Short",
        "selectSuggestionKeys": "Enter",
        "additionalCycleThroughSuggestionsKeys": "None",
        "disableUpDownKeysForCycleThroughSuggestionsKeys": false,
        "openSourceFileKey": "None",
        "propagateEsc": false,
        "enableCurrentFileComplement": true,
        "currentFileMinNumberOfCharacters": 0,
        "onlyComplementEnglishOnCurrentFileComplement": false,
        "enableCurrentVaultComplement": false,
        "currentVaultMinNumberOfCharacters": 0,
        "includeCurrentVaultPathPrefixPatterns": "",
        "excludeCurrentVaultPathPrefixPatterns": "",
        "includeCurrentVaultOnlyFilesUnderCurrentDirectory": false,
        "enableCustomDictionaryComplement": false,
        "customDictionaryPaths": "https://raw.githubusercontent.com/first20hours/google-10000-english/master/google-10000-english-no-swears.txt",
        "columnDelimiter": "Tab",
        "customDictionaryWordRegexPattern": "",
        "delimiterToHideSuggestion": "",
        "delimiterToDivideSuggestionsForDisplayFromInsertion": "",
        "caretLocationSymbolAfterComplement": "",
        "displayedTextSuffix": " => ...",
        "enableInternalLinkComplement": true,
        "suggestInternalLinkWithAlias": false,
        "excludeInternalLinkPathPrefixPatterns": "",
        "updateInternalLinksOnSave": true,
        "insertAliasTransformedFromDisplayedInternalLink": {
            "enabled": false,
            "beforeRegExp": "",
            "after": ""
        },
        "frontMatterKeyForExclusionInternalLink": "",
        "enableFrontMatterComplement": true,
        "frontMatterComplementMatchStrategy": "inherit",
        "insertCommaAfterFrontMatterCompletion": false,
        "intelligentSuggestionPrioritization": {
            "historyFilePath": "",
            "maxDaysToKeepHistory": 30,
            "maxNumberOfHistoryToKeep": 0
        },
        "disableOnMobile": false,
        "showLogAboutPerformanceInConsole": false,
        "selectionHistoryTree": {}
    }
}

**Comment by tadashi-aikawa** [comment]
@zxqcs 
That looks good. Could you tell me the reproduction steps in the sandbox vault? or video?

**Comment by zxqcs** [comment]
> @zxqcs
> That looks good. Could you tell me the reproduction steps in the sandbox vault? or video?

@tadashi-aikawa 

https://github.com/tadashi-aikawa/obsidian-various-complements-plugin/assets/10415430/f9126f62-a1dd-4bde-9a86-8b478cf9a567

**Comment by tadashi-aikawa** [comment]
@zxqcs 
It appears that a suggestion is displayed in your video. Can you specifically tell me the behavior you expect?

**Comment by zxqcs** [comment]
> @zxqcs
> It appears that a suggestion is displayed in your video. Can you specifically tell me the behavior you expect?

@tadashi-aikawa 
Yes, some suggestions is displayed indeed, but  the suggestions  are for obsidian markdown files which I have already created, not for English words. The behavior I expect is when I type "prog", a suggestion for "programming" should be displayed, for example.

**Comment by tadashi-aikawa** [comment]
@zxqcs 
Your setting is as follows.

```
"enableCurrentFileComplement": true,
"enableCurrentVaultComplement": false,
"enableCustomDictionaryComplement": false,
"enableInternalLinkComplement": true,
"enableFrontMatterComplement": true,
```

> The behavior I expect is when I type "prog", a suggestion for "programming" should be displayed, for example.

You might need to enable the [enableCustomDictionaryComplement](https://tadashi-aikawa.github.io/docs-obsidian-various-complements-plugin/4.%20Options/4.6.%20Custom%20dictionary%20complement/%E2%9A%99%EF%B8%8F%20Enable%20Custom%20dictionary%20complement/) option.

For more details, please see the documentation.

https://tadashi-aikawa.github.io/docs-obsidian-various-complements-plugin/#features

**Comment by zxqcs** [comment]
> @zxqcs Your setting is as follows.
> 
> ```
> "enableCurrentFileComplement": true,
> "enableCurrentVaultComplement": false,
> "enableCustomDictionaryComplement": false,
> "enableInternalLinkComplement": true,
> "enableFrontMatterComplement": true,

> You might need to enable the [enableCustomDictionaryComplement](https://tadashi-aikawa.github.io/docs-obsidian-various-complements-plugin/4.%20Options/4.6.%20Custom%20dictionary%20complement/%E2%9A%99%EF%B8%8F%20Enable%20Custom%20dictionary%20complement/) option.

@tadashi-aikawa 
Thank you. When this option is enabled,  the issue is solved. Maybe next time I should read documentation more carefully.
