### ISSUE TITLE
[FR] Make frontmatter complement trigger on JSON frontmatter

### ISSUE THREAD

**Issue by shemraz** [tadashi-aikawa/obsidian-various-complements-plugin#248]
I format my frontmatter as JSON for certain types of data. It would be great if the frontmatter complement autocomplete for JSON syntax as well as YAML!

**Comment by tadashi-aikawa** [comment]
Hi, @shemraz :)

I have never heard of the front matter of JSON. Can we write the front matter as JSON in Obsidian?

**Comment by shemraz** [comment]
Hi @tadashi-aikawa!

Yep, we can! Perhaps I'm in the minority who use it haha. From the Obsidian Docs:

<img width="543" alt="image" src="https://github.com/tadashi-aikawa/obsidian-various-complements-plugin/assets/112757453/ff72745c-7ca7-428b-91e8-15eff7beec53">

**Comment by tadashi-aikawa** [comment]
@shemraz 
Thank you for sharing. I tried it, but it did not work yesterday. However, I have tried it on today, and it works well!

**Comment by tadashi-aikawa** [comment]
@shemraz 
Released in [v9.0.0-beta6](https://github.com/tadashi-aikawa/obsidian-various-complements-plugin/releases/tag/9.0.0-beta6) 🚀 

I couldn't support the JSON format perfectly; however, it would work better than before.

![image](https://github.com/tadashi-aikawa/obsidian-various-complements-plugin/assets/9500018/6523e9a4-2f86-4a33-8261-ab91a37c3dfc)
![image](https://github.com/tadashi-aikawa/obsidian-various-complements-plugin/assets/9500018/c74e9aa0-1c4b-4865-beb5-a550b50ad35b)

**Comment by shemraz** [comment]
Amazing, thank you so much!
