### ISSUE TITLE
[Feature request] possibility to increase font size of suggestions

### ISSUE THREAD

**Issue by userrand** [tadashi-aikawa/obsidian-various-complements-plugin#249]
Thank you for this very nice plugin.

I struggle a bit to see the suggestions from autocomplete. Is there a way to increase the font size?

**Comment by tadashi-aikawa** [comment]
Hi, @userrand :)

You can increase the font size by setting CSS as follows.

```
.various-complements__suggestion-item {
  font-size: 1.5rem;
}
```

![image](https://github.com/tadashi-aikawa/obsidian-various-complements-plugin/assets/9500018/0f437918-e86a-4fcd-bfa9-fdb35285f875)

If you want to increase only the description's font size,

```
.various-complements__suggestion-item__description {
  font-size: 1.0rem;
}
```

![image](https://github.com/tadashi-aikawa/obsidian-various-complements-plugin/assets/9500018/3603a336-3425-4613-80a9-08c48d171171)

**Comment by userrand** [comment]
@tadashi-aikawa 

Great ! Thank you for you quick help and thank you again for this great plugin :)
