### ISSUE TITLE
[Feature Request] New Delimeter for Caret Position

### ISSUE THREAD

**Issue by FelipeRearden** [tadashi-aikawa/obsidian-various-complements-plugin#25]
Hello @tadashi-aikawa !!!!!!!!

I have one more FR for this amazing plugin !!!!

A new type of delimiter that let's the user define the caret position inside the token !!!!

Let's use a new example-> I use a lot of html tags to decorate my text :

```
<b id=aaa></b>		subheader
<b id=bbb></b>		subheader
<b id=ccc></b>		subheader
<mark id=ulm></mark>		list
<mark id=olm></mark>		list
<s id=asl></s>		asd
<s id=asr></s>		asd
```

A new delimiter to <CARET> to define the caret position after inserting the token. 

This way I can insert the caret position between them html tag which makes me much easier to write!

```
<b id=aaa><CARET></b>		subheader
<b id=bbb><CARET></b>		subheader
<b id=ccc><CARET></b>		subheader
<mark id=ulm><CARET></mark>		list
<mark id=ulm><CARET></mark>		list
<s id=asl><CARET></s>		asd
<s id=asr><CARET></s>		asd
```

---

I hope you like my suggestion !

Let me know if you need more information !

Thanks for reading this!!!

Have a great day!

**Comment by tadashi-aikawa** [comment]
Thank you for your FR, @FelipeRearden !

I think it seems to be out of scope, so I will not implement it soon. However, I'll try it if I have a time in the future.

If you need it right now, I recommend `text-xnippets-obsidian` plugin, which is awesome :)

https://github.com/ArianaKhit/text-snippets-obsidian

**Comment by FelipeRearden** [comment]
Thanks for your reply @tadashi-aikawa !!!!

Okay ! Thanks for considering in a possible future :)

I agree text snippets plug-in is fantastic. I haven been using for a long time. Thanks for your kindness for suggesting :)

My idea is to combine these two plugins to have a full keyboard only experience for text replacement. 

Since I have a lot of tokens it's hard for me to remember every shortcut from text snippets. This way I can use your plug-in to stack groups of tokens by aliás and use a single hotkey to invoke each group of alias.

And text-snippets would be used with few hot keys tokens that have a single alias and more complex structure $nl$ and $tb$ 

---

Thanks again :) 

I'm really enjoying this amazing plug-in :)

Have a great day!

**Comment by tadashi-aikawa** [comment]
> My idea is to combine these two plugins to have a full keyboard only experience for text replacement.

Wow, it is cool!!

> Since I have a lot of tokens it's hard for me to remember every shortcut from text snippets. 

I completely agree with you. It might be ideal that we can fluently type even if we remember nothing. 😄

**Comment by FelipeRearden** [comment]
That's why I'm so excited about your plugin :) 

We can work faster on Obsidian without having to remember hotkeys. It's a double win :) 

With a good set of alias + a robust custom dictionary you can applied these performance gain with the entire vault (study,research,habit tracker, recipes ...) 

I wish you a fantastic day!

**Comment by Mara-Li** [comment]
I will love to have a carret implementation ! On mobile it will be :fire: if it works. Because text snippet doesn't work on mobile and templater cusor doesn't work too :(

**Comment by FelipeRearden** [comment]
🙏 🙏 🙏 🙏 🙏 🙏

**Comment by tadashi-aikawa** [comment]
@FelipeRearden @Mara-Li 
LGTM. How about?

![2021-12-13](https://user-images.githubusercontent.com/9500018/145818924-a3279956-816e-41a7-aec9-3af0d36d383f.gif)

**Comment by Mara-Li** [comment]
Oh wow thank you!!!

**Comment by rainsia** [comment]
When will this feature be released?

**Comment by tadashi-aikawa** [comment]
@rainsia 
Maybe, I will release in this weekend.

**Comment by rainsia** [comment]
@tadashi-aikawa Looking forward to it. Thank you for your fantastic work.

**Comment by tadashi-aikawa** [comment]
@FelipeRearden (@Mara-Li @rainsia)
I have released to [v3.4.0](https://github.com/tadashi-aikawa/obsidian-various-complements-plugin/releases/tag/3.4.0) 🚀

Please confirm whether it works as you expected.

**Comment by FelipeRearden** [comment]
> Please confirm whether it works as you expected.

Hello @tadashi-aikawa !!!!!!!

Thank you very much !!!!!!! I'm so happy to have this new feature. Thanks for making this real for us :)

I have one little comment to share with you:

When the word defined in the settings as the anchor is different from `<CARET>` the caret position is moved perfectly but the word used as anchor is show in note. 

## Example 1: Correct 

Caret Location Symbol: <CARET>

Custom Dic:
123<CARET>456

Target Note:
![72E41843-EC14-435C-A496-ABD317DDFAE6](https://user-images.githubusercontent.com/85180696/146637683-3b36e094-73e7-4409-b4d4-3e3087f60277.jpeg)



## Example 2: Not Correct

Caret Location Symbol: <&>

Custom Dic:
123<$>456

Target Note:
![FBD6D1AC-AA97-45E9-940E-3CC0FEA68E2D](https://user-images.githubusercontent.com/85180696/146637692-e522bb78-2316-4e72-bdf0-d7c1e4efcbfc.jpeg)


---

I tried different words like `@@` `$end$` and I had the same result. 

I can use <CARET> without any problem :) but I think it's my duty to tell you!



Have a great day and thanks again this spectacular feature :)

**Comment by tadashi-aikawa** [comment]
@FelipeRearden 
Thank you for your confirmation and kind bug report! That is a careless mistake. 😅 

I have fixed it and released [v3.4.1](https://github.com/tadashi-aikawa/obsidian-various-complements-plugin/releases/tag/3.4.1) 👍

**Comment by FelipeRearden** [comment]
> @FelipeRearden 
> 
> Thank you for your confirmation and kind bug report! That is a careless mistake. 😅 
> 
> 
> 
> I have fixed it and released [v3.4.1](https://github.com/tadashi-aikawa/obsidian-various-complements-plugin/releases/tag/3.4.1) 👍 

Thanks for the quick fix @tadashi-aikawa !!!!!!!!!!!


Working PERFECT on version `3.4.1` on Obsidian `0.12.19` !!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by tadashi-aikawa** [comment]
That's good! Thanks! 👍

**Comment by rainsia** [comment]
It works fine with release 3.4.1. However, I have another feature request on the caret position.

Is it possible to have multiple <CARET>s in the text? When the text is inserted, so I can jump to the next <CARET> with the tab key? It's more like a <TabStop>.

**Comment by tadashi-aikawa** [comment]
@rainsia 
Thank you for your confirming!

> Is it possible to have multiple s in the text? 

Sorry, I will not implement it. It's difficult. Also, it's beyond the role of this plugin.

Best regards.

**Comment by FelipeRearden** [comment]
> Is it possible to have multiple <CARET>s in the text? When the text is inserted, so I can jump to the next <CARET> with the tab key? It's more like a <TabStop>.

You already can achieve this using VC if you have the plug-in Text Snippets installed. 

Text Snippets have a delimiter that you can jump when hit tab (the default is $tb$ but you can change in the plug-in Settings)

This way you can create a token like this 

123’<CARET>’567$tb$789

Use VC to insert in the note than hit tab to jump .

I hope it helps you :)
