### ISSUE TITLE
[FR]Insert double quotes when the properties are internal links

### ISSUE THREAD

**Issue by kazdonkai** [tadashi-aikawa/obsidian-various-complements-plugin#250]
プロパティ（フロントマター）では、内部リンクの場合には、二重引用符が必要です。
そこで、プロパティの場合には、内部リンクを挿入するサジェスチョンを選択した場合には、自動的に二重引用符を前後に付けるようにして欲しいです。
ex. 内部リンク→”[[内部リンク]]”

Double quotes are required for properties when internal linking is enabled.
So, for properties, please have double quotes before and after the double quotes automatically if the proposal to insert internal links is selected.
ex. internal link -> "[[internal link]]"

**Comment by tadashi-aikawa** [comment]
Thank you for your FR, @kazdonkai :)

That looks good. I'll add it 👍

**Comment by tadashi-aikawa** [comment]
@kazdonkai 
I have released it in the [v9.0.0-beta5](https://github.com/tadashi-aikawa/obsidian-various-complements-plugin/releases/tag/9.0.0-beta5) 🚀 

If you use BRAT, I would appreciate it if you could check it out before the official release.
