### ISSUE TITLE
[FR] Min number of characters for trigger for Japanese

### ISSUE THREAD

**Issue by iiz00** [tadashi-aikawa/obsidian-various-complements-plugin#257]
いつも便利に使わせていただいています！ありがとうございます。
日本語固有名詞のついたノートが多くあり、それらにリンクを張ることも多い特定目的のvaultで、
Internal link complementをStrategy: Japanese, Match strategy: partial で使っています。
Min number of characters for triggerが0の場合、日本語2文字でヒットするのだと思いますが、
漢字については丁度良い感じでサジェストされる一方、平仮名2文字についてはサジェストしてほしくない
ノートがしばしばサジェストされるようになってしまいました。
「です」「ます」「よう」「たい」のような、日本語文の文末に出現するような平仮名をタイトルに含むノートがあるため、文末でサジェストされるという感じです。
（ノート名の途中の文字列でサジェストさせているのでpartialを使っています）
漢字等のひらがな以外は2文字で、ひらがなは3文字でサジェストというような設定の実装は難しいでしょうか。ご検討いただければと思います。

**Comment by tadashi-aikawa** [comment]
> 漢字等のひらがな以外は2文字で、ひらがなは3文字でサジェストというような設定の実装は難しいでしょうか

@iiz00 
[Pattern to suppress trigger](https://tadashi-aikawa.github.io/docs-obsidian-various-complements-plugin/4.%20Options/4.1.%20Main/%E2%9A%99%EF%B8%8F%20Patterns%20to%20suppress%20trigger/) の設定で実現できます。

たとえば、『ひらがなとカタカナのみから構成される2文字以下の文字列』は `[\u3040-\u309F\u30A0-\u30FF]{1,2}` と表現できます。

【上記正規表現確認用サイト】
https://regex101.com/r/6gvQYK/1

※ ハイライトされているものがマッチするパターン (サジェストが表示されないパターン)

【設定イメージ】
![image](https://github.com/tadashi-aikawa/obsidian-various-complements-plugin/assets/9500018/a1a4ab09-4776-445f-a036-4d40c8b351c4)

他にも同じような要望はありそうですので、Various Complementsのドキュメントの方にユースケースとして追加しておきますね 👍

**Comment by tadashi-aikawa** [comment]
@iiz00 
... と思いましたが、上記の設定では十分ではありませんでした...。

上記設定は **現在行の文字列パターンによってサジェストを無視する** ものですが **現在のトークンパターンによってサジェストを無視する** 設定が必要そうです。こちらは別途検討してみます。

**Comment by tadashi-aikawa** [comment]
https://github.com/tadashi-aikawa/obsidian-various-complements-plugin/issues/258

**Comment by iiz00** [comment]
ありがとうございます。なるほど、正規表現で除外するのですね。
難解ですが、考えてみると自分のユースケースだと行頭指定を除いた`[\u3040-\u309F]{1,2}$`で
大体対応できるのかな？という気もします（しばらく使ってみないと分かりませんが…）
トークンへのパターン適用にも期待しています！

**Comment by tadashi-aikawa** [comment]
> [\u3040-\u309F]{1,2}$

このケースは『ひらがな or カタカナ 1～2文字で終わること』なので『プラグイン』みたいな5文字でもサジェストが出なくなってしまうんですよね... (最後が『イン』であり条件を満たすから)

**Comment by tadashi-aikawa** [comment]
@iiz00 
対応版の [v9.1.0-beta1](https://github.com/tadashi-aikawa/obsidian-various-complements-plugin/releases/tag/9.1.0-beta1) を利リリースしました 🚀 

インストールにはBRATが必要ですが、よろしければ正式版リリース前にご確認いただけると助かります 🙏 

新しく『Phrase patterns to suppress trigger』というオプションが増えていますので、そこに無視するフレーズパターンを指定していただければと。

![image](https://github.com/tadashi-aikawa/obsidian-various-complements-plugin/assets/9500018/1cfb7905-3278-475b-ad0d-03eb849ee889)

- パターンは完全一致
    - `[0-9]{2}` なら 数字を連続して2つ含むフレーズ (ex: 123, ほげ12ふが) の場合にサジェストを出さない
- 改行区切りで複数指定可能
    - いずれかのパターンに一致したらサジェストを出さない

今回のケースなら

```
[\u3040-\u309F\u30A0-\u30FF]{1,2}
```

でいけると思います。

**Comment by iiz00** [comment]
びっくりするくらい早い対応ありがとうございます！
少し試してみた限りでは、問題なく期待通りの動作をしているように思います（平仮名のみの[\u3040-\u309F]{1,2}としました）。
これならMin number… を1にして漢字1文字でサジェストするように設定してもいいかもしれないですね。
また正規表現でなくても、単に反応させたくない単語をそのまま入力しておけばその単語を含むファイル名のサジェストがされなくなるという認識で良いでしょうか？これだとよりフレキシブルに設定できて良い感じです。
複数の補完法を使っている人は補完法ごとにパターンを指定したくなるかも、と思いました（今のところ自分はinternal link complementしか有効にしていないので想像にすぎませんが）

**Comment by tadashi-aikawa** [comment]
@iiz00 
ご確認ありがとうございます 🙏 

> 正規表現でなくても、単に反応させたくない単語をそのまま入力しておけば

はい。以下のケースであれば『ます』や『です』を含む入力は除外対象になります。

```
ます
です
```

※ 正規表現特有の記法がないだけで、上記も正しい正規表現です

> その単語を含むファイル名のサジェストがされなくなるという認識で良いでしょうか？

雰囲気はあっていますが、正確には少し違います。『その単語を含む入力がされたときは *補完が出ない* 』が正しいです。

候補そのものを除外したい場合は [⚙️ Exclude prefix path patterns \(Internal link complement\)](https://tadashi-aikawa.github.io/docs-obsidian-various-complements-plugin/4.%20Options/4.7.%20Internal%20link%20complement/%E2%9A%99%EF%B8%8F%20Exclude%20prefix%20path%20patterns%20%28Internal%20link%20complement%29/) を使ってください。 

※ 正規表現には対応してなく、path前方一致のみになってしまいますが (以前は正規表現に対応しましたが、pathの指定が難解で不評だったため仕様を変えています)

**Comment by tadashi-aikawa** [comment]
@iiz00 
すいません。一部誤りがありました。

> 正規表現でなくても、単に反応させたくない単語をそのまま入力しておけば

正規表現の完全一致ですので、以下のような記載が必要になります。

```
.*ます.*
.*です.*
```

または

```
.*です|ます.*
```

**Comment by iiz00** [comment]
ありがとうございます、使い方研究してみます。

**Comment by iiz00** [comment]
その後、平仮名1～2文字の指定といくつかの特定単語の指定で、私の環境では非常によく機能しているように思います。
してほしくないサジェストの頻度がかなり減りました。internal link complementとの相性がいいように思います。
issueをcloseすべきだったでしょうか？作法を知らなくてすいません…
改めて対応ありがとうございました！

**Comment by tadashi-aikawa** [comment]
@iiz00 
ご報告ありがとうございます。それでは公式版として9.1.0をリリースいたします。

クローズは9.1.0リリース後にしていただくのが確実ですが、中身は一緒なので今すぐでも問題ございません。

**Comment by tadashi-aikawa** [comment]
@iiz00 
[v9.1.0](https://github.com/tadashi-aikawa/obsidian-various-complements-plugin/releases/tag/9.1.0) をリリースしました 🚀
