### ISSUE TITLE
Words like `$XYZ` do not appear as a suggestion.

### ISSUE THREAD

**Issue by sudodo** [tadashi-aikawa/obsidian-various-complements-plugin#259]
Hello there. I truly love this plugin. I appreciate the efforts of the developers.

By the way, I noticed that words beginning with a dollar sign ($) do not show up as suggestions. I have confirmed that words beginning with `%` or `@` do show up as suggestions.

For example, `$XYZ` does not appear as a suggestion. However, `@XYZ` and `%XYZ` do appear.

Is this a bug? Or is this an expected feature?

I sometimes use obsidian to write shell scripts, so it would be more beneficial if `$XYZ` was recognized as a suggested word.

Thank you.

**Comment by tadashi-aikawa** [comment]
Thank you for your report, @sudodo :)

Do you use the [Japanese Strategy](https://tadashi-aikawa.github.io/docs-obsidian-various-complements-plugin/2.%20Strategies/japanese/) ?

**Comment by sudodo** [comment]
Sorry for my late reply, @tadashi-aikawa 

> Do you use the [Japanese Strategy](https://tadashi-aikawa.github.io/docs-obsidian-various-complements-plugin/2.%20Strategies/japanese/) ?

No. I am using [default](https://tadashi-aikawa.github.io/docs-obsidian-various-complements-plugin/2.%20Strategies/default/) strategy. However, the problem seems to reproduce even with the `Japanese strategy` in my environment.

**Comment by tadashi-aikawa** [comment]
@sudodo 
Thank you for your reply. I could reproduce it using the default strategy 👍

**Comment by tadashi-aikawa** [comment]
@sudodo 
Released in [v9.1.0-beta3](https://github.com/tadashi-aikawa/obsidian-various-complements-plugin/releases/tag/9.1.0-beta3) 🚀 

If the "[⚙️ First characters to disable suggestions](https://tadashi-aikawa.github.io/docs-obsidian-various-complements-plugin/4.%20Options/4.1.%20Main/%E2%9A%99%EF%B8%8F%20First%20characters%20to%20disable%20suggestions/)" contains "$", it must be removed.

![image](https://github.com/tadashi-aikawa/obsidian-various-complements-plugin/assets/9500018/53a925d5-284d-4f92-81c5-7023217a3134)

**Comment by sudodo** [comment]
Thank you so much. I'm traveling this week. So I'll check it next week.

**Comment by tadashi-aikawa** [comment]
Released in [v9.1.0](https://github.com/tadashi-aikawa/obsidian-various-complements-plugin/releases/tag/9.1.0) 🚀
