### ISSUE TITLE
Question: Does the 2.0 plug-in version and the path of the dictionary file no longer support absolute paths?

### ISSUE THREAD

**Issue by tyf2018** [tadashi-aikawa/obsidian-various-complements-plugin#26]
Does the 2.0 plug-in version and the path of the dictionary file no longer support absolute paths?

If so, I would be a little sad. My dictionary file is stored outside the obsidian vault and must be accessed using an absolute path.

**Comment by tadashi-aikawa** [comment]
> Does the 2.0 plug-in version and the path of the dictionary file no longer support absolute paths?

You're right. It is necessary for support mobile.

Could you store the dictionary files in obsidian vault? I want to know why you need to do if you have a critical problem.

**Comment by tyf2018** [comment]
> I want to know why you need to do if you have a critical problem.

I have several libraries, sharing a dictionary file, so it is the most convenient to put it outside the vault.

**Comment by tadashi-aikawa** [comment]
@tyf2018 
Thanks.

By the way, on my Windows, It could load dictionary files located outside of vault by `..\`. Would you try it?

![image](https://user-images.githubusercontent.com/9500018/142763544-4db2f81b-f595-4910-9ed6-f9309a50c293.png)

**Comment by tyf2018** [comment]
> Would you try it?`..\`

Wow, I will try it, thank you.

**Comment by tyf2018** [comment]
> By the way, on my Windows, It could load dictionary files located outside of vault by

The files outside the library keep reporting errors. I have tried various possible formats, and all report errors.

![image](https://user-images.githubusercontent.com/56342788/142764278-d45a3396-8d85-4ba7-bce8-5e30f673fd93.png)

**Comment by tadashi-aikawa** [comment]
Mmm... Where is your vault root path?

**Comment by tyf2018** [comment]
> Where is your vault root path?

My vault root path:：
![image](https://user-images.githubusercontent.com/56342788/142787124-b076e89d-52bd-43d4-b506-9d31ee8404cd.png)
Could it be because this place has a solid point? 🤣

**Comment by tyf2018** [comment]
After testing, it is indeed because the path of the dictionary file contains "." and an error is reported.😅

**Comment by tyf2018** [comment]
Hi， @tadashi-aikawa 
Regarding the format of ..\folder, if there are multiple files with the same name (but with different parent folders), can they all be matched?

**Comment by tadashi-aikawa** [comment]
@tyf2018 
It sounds strange.. If your root vault is `1工作万方`, It should show `1工作万方` in your error report capture.

You use `Various Complements` v2.0.0 and later, don't you?

**Comment by tyf2018** [comment]
> It sounds strange.. If your root vault is `1工作万方`, It should show `1工作万方` in your error report capture.

I have several vaults, and the two screenshots are not the same vault.

In short, I have no problems now, thank you.

**Comment by tadashi-aikawa** [comment]
Thanks for reply!

> I have no problems now

Do you mean that you could load dictionary files, right?

**Comment by tyf2018** [comment]
> Do you mean that you could load dictionary files, right?

Yes, Windows: For dictionary files stored outside the vault, as long as the path does not contain ".", they can be read and loaded normally.

But now there is a small problem. The path setting normally used in the window keeps reporting an error on Android.

Is there any special attention to the path setting on Android? The plug-in instructions do not seem to mention it.

**Comment by tadashi-aikawa** [comment]
@tyf2018 
Sorry, It doesn't support to load dictionary files from relative paths, that point outside of Vault on mobile. 

> The plug-in instructions do not seem to mention it.

You are right. I'll update README and a description in settings. Thank you!
