### ISSUE TITLE
Various complements breakes Templater "syntax dialog"

### ISSUE THREAD

**Issue by Acuena85** [tadashi-aikawa/obsidian-various-complements-plugin#263]
Hi,

I discovered that enabling both "Various complements" and "Templater" simultaneously causes the information box, which appears when using Templater syntax, to stop working. Please refer to the attached image for clarification (I'm not sure what these boxes are officially called).

I encountered an issue where the information box wasn't appearing, but as soon as I disabled the "Various complements" plugin, it began to function properly.

![image](https://github.com/tadashi-aikawa/obsidian-various-complements-plugin/assets/62965652/3157347e-e510-4683-9252-959fb734f033)

**Comment by tadashi-aikawa** [comment]
@Acuena85 
Please see https://github.com/tadashi-aikawa/obsidian-various-complements-plugin/issues/111#issuecomment-1088157244.

**Comment by Acuena85** [comment]
Adding "<%.*" to "Patterns to suppress trigger" seems to make it work.
