### ISSUE TITLE
Feature Request: Option treat "words containg underscore like foo_bar" as one word

### ISSUE THREAD

**Issue by wafe** [tadashi-aikawa/obsidian-various-complements-plugin#271]
As a programmer, I often use variables such as 'foo_bar' and 'latest_comments_for_user' in my Obsidian notes. It would greatly enhance my efficiency and comfort if these types of variable names could be auto-completed. 

Thank you for developing such a useful Obsidian plugin.

**Comment by tadashi-aikawa** [comment]
Sorry for my late answer, @wafe.

I agree with you. I want to give it a try 👍

**Comment by tadashi-aikawa** [comment]
Since underscores are used in Markdown syntax, it's difficult for Various Complements to determine whether they signify names or formatting.

Therefore, we will introduce an advanced option to address this.

**Comment by tadashi-aikawa** [comment]
@wafe 
Released in [v9.2.0](https://github.com/tadashi-aikawa/obsidian-various-complements-plugin/releases/tag/9.2.0) 🚀
