### ISSUE TITLE
FR: Apply Various Complements' hotkeys also to suggestions from Obsidian Core

### ISSUE THREAD

**Issue by chrisgrieser** [tadashi-aikawa/obsidian-various-complements-plugin#272]
Hi again!

So I have customized my hotkeys for Various Complements to cycle to the next/previous suggestion with `Tab` and `ShiftTab`. 

I got so used to it, that I also use the hotkey in suggestions from Obsidian, e.g. the ones for a wikilink when you type `[[`. However, the suggestions from Obsidian have their own hotkeys, and there `Tab` selects and inserts the suggestion instead of cycling to the next suggestion. And having to remember that there are two different set of hotkeys, depending on which type of suggestion you have, is really, really annoying.

Would it be possible for Various Completions to "apply" its hotkeys to the Obsidian hotkeys as well?

**Comment by tadashi-aikawa** [comment]
Hi, @chrisgrieser :)

Sorry, at this moment, I do not plan to implement this feature because the Various Complements is not intended to affect the core functionality of Obsidian.
