### ISSUE TITLE
FR: Anchor (Header) Link Support

### ISSUE THREAD

**Issue by HugoCortell** [tadashi-aikawa/obsidian-various-complements-plugin#274]
Request to add support for anchor links (linking to headers within a note).

As an example use case, game design docs usually have a concepts page where every keyword is detailed. In Obsidian, this would be one large note with many headers for every relevant keyword (as it would make little sense to have many notes with just two lines of text in them).

![sampleuse](https://github.com/tadashi-aikawa/obsidian-various-complements-plugin/assets/59887727/9bdbf09d-8449-49f9-a8e2-66e18df9e586)
In the image above, you can see me trying to link to the word "party" but it keeps brining up an unrelated note.

[Obsidian already supports this](https://help.obsidian.md/Linking+notes+and+files/Internal+links#Link+to+a+heading+in+a+note) (using `[[##TEXT]`]), but it does not seem like the plugin does.

Relevant: [Reddit post about it](https://www.reddit.com/r/ObsidianMD/comments/18xwwjp/various_complements_plugin_create_links_to_titles/).

**Comment by tadashi-aikawa** [comment]
Thank you for your FR, @HugoCortell :)

Might this Issue also be relevant?

https://github.com/tadashi-aikawa/obsidian-various-complements-plugin/issues/72
