### ISSUE TITLE
Suggestion: Prefer words from current file over custom dictionary

### ISSUE THREAD

**Issue by qazxcdswe123** [tadashi-aikawa/obsidian-various-complements-plugin#275]
https://github.com/tadashi-aikawa/obsidian-various-complements-plugin/blob/1027befd2ab630e406c699124ebfb99158101711/src/model/Word.ts#L67-L76

Currently the custom dictionary has higher priority than current file, however, if the word has appeared in the same file, I am more likely to input the same word again!

**Comment by tadashi-aikawa** [comment]
Thank you for your suggestion, @qazxcdswe123 :)

Might this Issue also be relevant?

https://github.com/tadashi-aikawa/obsidian-various-complements-plugin/issues/216

**Comment by qazxcdswe123** [comment]
Yes this is definitely relevant but my focus is more on "the default priority can be better (file > dictionary)" side
The idea is, one will more likely to input words that already in the file (like a context)

What do you think?  : )

**Comment by tadashi-aikawa** [comment]
Thank you for your response :)

In my opinion, it's better not to change the default priority. The reasons are as follows:

1. Many users are already using the current priority, and there have been no requests for such a change so far.
2. If snippets are registered in the Custom dictionary complements, I believe they should be prioritized.
3. What to prioritize varies from user to user, depending on which features they are using and for what purpose.
