### ISSUE TITLE
[FR] Variable names with underscores(eg.xxx_yyy) cannot be completed with the plugin

### ISSUE THREAD

**Issue by wangemal** [tadashi-aikawa/obsidian-various-complements-plugin#277]
xxx_yyy can only complete xxx or yyy in the current plugin version，

Whether it can support the completion of xxx_yyy, just like vim

**Comment by tadashi-aikawa** [comment]
Hi, @wangemal :)

Might this Issue also be relevant?

https://github.com/tadashi-aikawa/obsidian-various-complements-plugin/issues/271

**Comment by wangemal** [comment]
> Hi, @wangemal :)
> 
> Might this Issue also be relevant?
> 
> #271

yeah, it's exactly the same need, looking forward to the update

Thank you for developing such a useful Obsidian plugin
