### ISSUE TITLE
[v3.0.0] Internal Link complement

### ISSUE THREAD

**Issue by tadashi-aikawa** [tadashi-aikawa/obsidian-various-complements-plugin#28]
Coming soon!

![2021-11-22](https://user-images.githubusercontent.com/9500018/142870959-75bd2add-b73d-421a-937f-1300b73b33e1.gif)

## Feature

- Complement both resolved and unresolved link
- It supports aliases
- It can complement `AWS Lambda` when you input `awslam`

## Performance

In my vault (2795 markdown files / 48411 lines / 1763815 chars / No custom dictionary)

| Function | Time (msec) |
|-|-|
| Show suggestions | 2 < x < 7 |
| Indexing links and aliases | 2 < x < 7 |

In most cases, this is no problem :)

**Comment by FelipeRearden** [comment]
> Upload latest version at https://github.com/tadashi-aikawa/obsidian-plugin-dev-sandbox/releases/tag/0.0.5

Hello @tadashi-aikawa !!!!!

The word to describe this new feature is AMAZING !!!!!!!!

I update and tested and I have to suggestions based on my workflow (let me know if you want me to create separate FR for one of then)

🟡 I'm gonna the term `Backlinks Dictionary` for this feature to make easier for me to explain in my poor English :)

## FR1 - Only Suggest from `Backlinks Dictionary` option in Settings

Same behavior that my previous FR #14 applied to `Backlinks Dictionary` 

This way I can use this feature only + my Custom Dictionary  
- I have a lot of backlinks commom for terms like [[Fear]],[[Angry]],[[Love]],[[Sadness]],[[Discipline]],[[Courage]] ... so for me would amazing to just have a autocomplete for backlinks only and for my custom dictionary :)


## FR2 - Settings option to insert an `whitespace - \s` after  choosing a Backlinks

It's feels nature to me while typing a Backlink and always insert a whitespace (spacebar keyboard key) 

I think would be great to have an option to have this automatic after selecting a backlink :)


---

Thank you very much for this new feature and for the opportunity to suggest a few things !!!!!

Have a great day!

**Comment by tadashi-aikawa** [comment]
Hi, @FelipeRearden. Thank you for trying new feature and your suggestions!! 😄 

> I'm gonna the term Backlinks Dictionary for this feature to make easier for me to explain in my poor English :)

🟢 Sure, but generally, [Backlinks](https://help.obsidian.md/Plugins/Backlinks) seem to mean `backlinks plugins`. So I think it would be better to call it [Internal link complete](https://help.obsidian.md/How+to/Internal+link).

> FR1 - Only Suggest from Backlinks Dictionary option in Settings

Since as the version increases, so have the features, I want to reorganize `enable/disable` options :)

> FR2 - Settings option to insert an whitespace - \s after choosing a Backlinks

I agree to add this option :)

This is the option I was wondering if I should add or not, even if I usually don't write English except for development. (FYI: It doesn't use whitespace in Japanese.)

Additionally, I think it should insert whitespace not only Backlink (Internal link) but also others (custom dictionary, current file tokens, etc.), don't you?

**Comment by tadashi-aikawa** [comment]
New simplify options coming soon 🚀 

![image](https://user-images.githubusercontent.com/9500018/142983681-0f96f77b-44e1-40bb-b669-65dcc6281adb.png)

**Comment by tadashi-aikawa** [comment]
@FelipeRearden @chrisgrieser

I have uploaded the latest development version to [here](https://github.com/tadashi-aikawa/obsidian-plugin-dev-sandbox/releases/tag/0.0.7). (Changed a plugin name due to avoid confusion with production 😉 )

There are various updates apart from this issue. Roughly writes..

---

- Renew options
    - Add `Enable Current file complement` option
    - Add `Enable Custom dictionary complement` option
    - Add `Enable Internal link complement` option
    - Add `Show log about performance in a console` option
    - Add `Propagate ESC` option 🤖 
    - Add `Insert space after completion` option 😉 
    - Update a range of `Max number of suggestions` from `5 to 50` to `1 to 255`
    - Remove `Only suggest from custom dictionaries` option 🔥 
    - Optimize performance according to settings
- Improve suggestion order
- Fix a bug that registers duplicated events when it reloads plugins

---

While using and verifying the latest development version, I want to release it as v3.0.0 this weekend. 🍷

**Comment by FelipeRearden** [comment]
> 🟢 Sure, but generally, [Backlinks](https://help.obsidian.md/Plugins/Backlinks) seem to mean `backlinks plugins`. So I think it would be better to call it [Internal link complete](https://help.obsidian.md/How+to/Internal+link).

Great idea @tadashi-aikawa !!!!!!!

> Since as the version increases, so have the features, I want to reorganize `enable/disable` options :)

Great! We are getting a lot of customization and it's a good time to change the Settings :) 

> I agree to add this option :)

Thank you very much @tadashi-aikawa !!!!!!!

> This is the option I was wondering if I should add or not, even if I usually don't write English except for development. (FYI: It doesn't use whitespace in Japanese.)
> 
> Additionally, I think it should insert whitespace not only Backlink (Internal link) but also others (custom dictionary, current file tokens, etc.), don't you?

100% agree with you !!!! We save a lot of time for long writing :)

Have a great day!!!!!

**Comment by FelipeRearden** [comment]
> I have uploaded the latest development version to [here](https://github.com/tadashi-aikawa/obsidian-plugin-dev-sandbox/releases/tag/0.0.7). (Changed a plugin name due to avoid confusion with production 😉 )

Woowww !!! Taking a look right now and I get back to you soon !!!!!!!!

**Comment by chrisgrieser** [comment]
Unfortunately I do not have much time this week, but I'm looking forward to test everything on the weekend!

**Comment by FelipeRearden** [comment]
> Woowww !!! Taking a look right now and I get back to you soon !!!!!!!!

Hello @tadashi-aikawa !!!!!!

What a great update!!!! I loved everything, it's amazing :)

Tested mainly my scenario that is:
- `Enable Current file complement` OFF
- `Enable Custom dictionary complement` ON
- `Enable Internal link complement` ON
- `Insert space after completion` ON

For me working perfect on version `0.0.7` Obsidian `0.12.19`

Thanks for everything that you have been doing ! I'm so happy to have this new plugin for my workflow!


I wish you a fantastic day!

**Comment by tadashi-aikawa** [comment]
I have uploaded latest version.

https://github.com/tadashi-aikawa/obsidian-plugin-dev-sandbox/releases/tag/0.0.8

- Fix that doesn't suggest several unresolved links after booting Obsidian
- Update a range of `Delay milli-seconds for trigger` from `0 to 10000` to `0 to 1000`

**Comment by tadashi-aikawa** [comment]
@tadashi-aikawa 
Sure! Of course, after release v3.0.0, I always welcome a nice FR or Bug report 👍

**Comment by tadashi-aikawa** [comment]
@FelipeRearden 
Thank you for your quick test report! I'm so glad to hear that it is as you expected 😄

Please let me know if you have any questions 👍 

For your information, this is my settings.

- `Strategy` japanese
- `Max number of suggestions` 30
- `Min number of characters for trigger` **3**
- `Delay milli-seconds for trigger` **100**
- `Insert space after completion` OFF
- `Propagate ESC` **ON** (Because I always use vim mode 😄)
- `Enable Current file complement` ON
- `Enable Custom dictionary complement` OFF
- `Enable Internal link complement` ON
- `Debug` ON (Because I am a developer 😉 )

**Comment by FelipeRearden** [comment]
Thanks for sharing your Settings @tadashi-aikawa !!!

This is good because since we have different settings we can test different things on each new release :) 

And I'm almost sure that @chrisgrieser will have a different settings from us :)


Have a great day!

**Comment by tadashi-aikawa** [comment]
I have uploaded https://github.com/tadashi-aikawa/obsidian-plugin-dev-sandbox/releases/tag/0.0.9

- Remove hot key from `Toggl Auto-complete` command 🔥 
- Optimize suggestions (trim `\` and `/` )

**Comment by tadashi-aikawa** [comment]
I have uploaded https://github.com/tadashi-aikawa/obsidian-plugin-dev-sandbox/releases/tag/0.0.10

- Add `Disable suggestions during IME on` option
- Add `Show suggestions` command (default key: `Ctrl + Space`)

**Comment by tadashi-aikawa** [comment]
I have uploaded https://github.com/tadashi-aikawa/obsidian-plugin-dev-sandbox/releases/tag/0.0.12

- If your input starts with a capital letter, suggest starting with a capital letter even if original suggestions don't begin with a capital letter (#30)
- Use case-insensitive match except for `Internal Link Search` (#30)

**Comment by tadashi-aikawa** [comment]
This is really the final RC version if there are no problems :)

https://github.com/tadashi-aikawa/obsidian-various-complements-plugin/issues/33#issuecomment-980553533

**Comment by tadashi-aikawa** [comment]
I have uploaded https://github.com/tadashi-aikawa/obsidian-plugin-dev-sandbox/releases/tag/0.0.15

**Comment by tadashi-aikawa** [comment]
I'll close this issue since it releases [v3.0.0](https://github.com/tadashi-aikawa/obsidian-various-complements-plugin/releases/tag/3.0.0).

**Comment by FelipeRearden** [comment]
Hello @tadashi-aikawa !!!!

Just to let you know that I update to version `3.0.1` and based on my workflow everything is perfect on Obsidian `0.12.19` 

Thank you very much for the new features !!!!!!!!!

Have a great day!
