### ISSUE TITLE
Histories,json file only modified if default config folder .obsidian installation exists

### ISSUE THREAD

**Issue by zanodor** [tadashi-aikawa/obsidian-various-complements-plugin#280]
So if I have .mobile, .billgates_sucks, etc. config folders where I installed the plugin in, the histories.json file is not created in these and thus it is not written to, unless you have also a default .obsidian config folder as well on which you installed the plugin.  

This can be fortunate as well, I guess: I reckon that now if you are on any device, you will enjoy the benefit of a common json file's data.  

I wanted to put this up months ago but then I forgot about it and only installed on .obsidian the other day.

I'll make it up to you do anything you want about it. :)

**Comment by tadashi-aikawa** [comment]
@zanodor 
Thank you for sharing!

I hadn't thought about it that deeply, but it's good to know it seems to work fine👍
