### ISSUE TITLE
Portuguese - BR Dictionary!

### ISSUE THREAD

**Issue by lucasbcgeo** [tadashi-aikawa/obsidian-various-complements-plugin#281]
First of all, nice work! Your plugin is awesome!

Do you intend to add other languages?

Thanks!

**Comment by tadashi-aikawa** [comment]
Hi, @lucasbcgeo :)

If Portuguese is a language that separates words with spaces, similar to English, it can be used with the strategy set to 'default'.

**Comment by ThomasEricB** [comment]
@lucasbcgeo Hey Lucas, just solved your problem! Add this link into the dictionary section:

 https://raw.githubusercontent.com/ThomasEricB/words-pt-uncompressed-with-utf8-txt/master/wordsList.txt

Like this:

![Obsidian_11tdoiITRs](https://github.com/tadashi-aikawa/obsidian-various-complements-plugin/assets/9662095/1d9631f1-f18a-484b-a6ec-70de3d65750b)

Funciona perfeitamente!

**Comment by tadashi-aikawa** [comment]
https://tadashi-aikawa.github.io/docs-obsidian-various-complements-plugin/4.%20Options/4.6.%20Custom%20dictionary%20complement/%E2%9A%99%EF%B8%8F%20Custom%20dictionary%20paths/#language-dictionary-file-url

**Comment by lucasbcgeo** [comment]
Thanks, @tadashi-aikawa  and @ThomasEricB
