### ISSUE TITLE
Easily rename accepted internal link suggestion.

### ISSUE THREAD

**Issue by tadashi-aikawa** [tadashi-aikawa/obsidian-various-complements-plugin#282]
### Discussed in https://github.com/tadashi-aikawa/obsidian-various-complements-plugin/discussions/273

<div type='discussions-op-text'>

<sup>Originally posted by **lukasschulte03** January  2, 2024</sup>
First off, this plugin is amazing, and I use it everyday, especially its internal link complement features.

But I have the issue that I, most of the time I want to rename my internal links, since they're almost always either incorrectly capitalized, or inflected incorrectly, or so on...
This becomes quite a hassle after a while. Always having to go back a couple of characters, insert a pipe character, write the actual display name, and go forward again.

I was wondering if there's any way to make a feature, where every time you accept an autocomplete suggestion to an internal link, an input prompt pops up where you can insert if you want the display name to be different that of the underlying notes name (or alias that you've referred to). If you don't want a different display name, just hit enter again and leave it empty, but if you type something and hit enter, the display name should be changed to that.

Of course it should be toggleable in the settings, and off by default, since I don't see this fitting the needs of the majority of users.

I would find this much easier than alias managing since that's not really applicable in my case. This solution feels much easier when the alternative is to make 10's of aliases for each note, which would suck...

*(Maybe there's already a good solution for this and I'm just ignorant, please inform me that case.)*</div>

**Comment by tadashi-aikawa** [comment]
@lukasschulte03
I have moved from the Discussion, so let's continue here.

**Comment by tadashi-aikawa** [comment]
@lukasschulte03
Coming soon...

![2024-02-18-21-18-48](https://github.com/tadashi-aikawa/obsidian-various-complements-plugin/assets/9500018/373eb208-bcc2-47bf-a027-2fa676ebbfcc)

![image](https://github.com/tadashi-aikawa/obsidian-various-complements-plugin/assets/9500018/f3487604-6236-40ac-b09c-c1a31b737fa4)

**Comment by lukasschulte03** [comment]
> @lukasschulte03 Coming soon...
> 
> ![2024-02-18-21-18-48](https://private-user-images.githubusercontent.com/9500018/305713787-373eb208-bcc2-47bf-a027-2fa676ebbfcc.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgyNjA0NjcsIm5iZiI6MTcwODI2MDE2NywicGF0aCI6Ii85NTAwMDE4LzMwNTcxMzc4Ny0zNzNlYjIwOC1iY2MyLTQ3YmYtYTAyNy0yZmE2NzZlYmJmY2MuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIxOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMThUMTI0MjQ3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDc2M2IwMTMzNDFhZTQwYTViMDRjZDhlNmM2ZWE1NWQ2ZGYwYTU2NWYzNmFlZGNmYTA3Y2FiYTkyNzZiOWMzOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.CqO3UWki7EPzyJYRfKRXEvGJ67E5yF23WkmD5xuDM1w) [ ![2024-02-18-21-18-48](https://private-user-images.githubusercontent.com/9500018/305713787-373eb208-bcc2-47bf-a027-2fa676ebbfcc.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgyNjA0NjcsIm5iZiI6MTcwODI2MDE2NywicGF0aCI6Ii85NTAwMDE4LzMwNTcxMzc4Ny0zNzNlYjIwOC1iY2MyLTQ3YmYtYTAyNy0yZmE2NzZlYmJmY2MuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIxOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMThUMTI0MjQ3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDc2M2IwMTMzNDFhZTQwYTViMDRjZDhlNmM2ZWE1NWQ2ZGYwYTU2NWYzNmFlZGNmYTA3Y2FiYTkyNzZiOWMzOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.CqO3UWki7EPzyJYRfKRXEvGJ67E5yF23WkmD5xuDM1w) ](https://private-user-images.githubusercontent.com/9500018/305713787-373eb208-bcc2-47bf-a027-2fa676ebbfcc.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgyNjA0NjcsIm5iZiI6MTcwODI2MDE2NywicGF0aCI6Ii85NTAwMDE4LzMwNTcxMzc4Ny0zNzNlYjIwOC1iY2MyLTQ3YmYtYTAyNy0yZmE2NzZlYmJmY2MuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIxOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMThUMTI0MjQ3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDc2M2IwMTMzNDFhZTQwYTViMDRjZDhlNmM2ZWE1NWQ2ZGYwYTU2NWYzNmFlZGNmYTA3Y2FiYTkyNzZiOWMzOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.CqO3UWki7EPzyJYRfKRXEvGJ67E5yF23WkmD5xuDM1w) [ ](https://private-user-images.githubusercontent.com/9500018/305713787-373eb208-bcc2-47bf-a027-2fa676ebbfcc.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgyNjA0NjcsIm5iZiI6MTcwODI2MDE2NywicGF0aCI6Ii85NTAwMDE4LzMwNTcxMzc4Ny0zNzNlYjIwOC1iY2MyLTQ3YmYtYTAyNy0yZmE2NzZlYmJmY2MuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIxOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMThUMTI0MjQ3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDc2M2IwMTMzNDFhZTQwYTViMDRjZDhlNmM2ZWE1NWQ2ZGYwYTU2NWYzNmFlZGNmYTA3Y2FiYTkyNzZiOWMzOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.CqO3UWki7EPzyJYRfKRXEvGJ67E5yF23WkmD5xuDM1w)
> 
> ![image](https://private-user-images.githubusercontent.com/9500018/305713882-f3487604-6236-40ac-b09c-c1a31b737fa4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgyNjA0NjcsIm5iZiI6MTcwODI2MDE2NywicGF0aCI6Ii85NTAwMDE4LzMwNTcxMzg4Mi1mMzQ4NzYwNC02MjM2LTQwYWMtYjA5Yy1jMWEzMWI3MzdmYTQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIxOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMThUMTI0MjQ3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTVjNjYwYjg0ZWJhMGUzZTBmZGM1YzdjOWFkMTNkODg4Yzg3ZjcxZDNiYTFjNTQ3OTA5MGU1YTEwOGZhMzQ1OSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.r3oEm0qb9D4maXZqiBjCzU67gk5WR_0_dO2U6Zd4jos)

Ohhh, looks very promising!!

**Comment by lukasschulte03** [comment]
@tadashi-aikawa 
Ohhh looks very promising!!😄

**Comment by tadashi-aikawa** [comment]
@lukasschulte03 
Released in [v9.3.0](https://github.com/tadashi-aikawa/obsidian-various-complements-plugin/releases/tag/9.3.0) 🚀

**Comment by lukasschulte03** [comment]
@tadashi-aikawa 
Amazing!👏🙏
