### ISSUE TITLE
[FR] Don't highlight first result when opening completions

### ISSUE THREAD

**Issue by Kageetai** [tadashi-aikawa/obsidian-various-complements-plugin#284]
Hello,
thanks first for the excellent plugin. I have only one small problem with it. I often type many bullet lists and it often happens that at the end of the list the dropdown with the completions opens up, but I just quickly want to enter a new or so. But as the first item in the dropdown is preselected, it gets entered into the document.
I played around with the time delay, but I do still like to see the completions, but I prefer to consciously choose when to insert one or when not.
Therefore would it he possible to just not highlight the first result when the dropdown shows, so it won't get selected automatically when pressing "Enter"? Maybe have a setting to disable that?
Thanks

**Comment by tadashi-aikawa** [comment]
Hi, @Kageetai :)

The [⚙️ No auto focus until the cycle](https://tadashi-aikawa.github.io/docs-obsidian-various-complements-plugin/4.%20Options/4.1.%20Main/%E2%9A%99%EF%B8%8F%20No%20auto-focus%20until%20the%20cycle/) option could potentially assist you 👍

**Comment by Kageetai** [comment]
Ah nice, I overlooked or misunderstood that setting. That seems to exactly do what I want. Perfect 🙇
