### ISSUE TITLE
[New Feature Request] Add a Brazilian Portuguese profile with my dictionary word file link

### ISSUE THREAD

**Issue by ThomasEricB** [tadashi-aikawa/obsidian-various-complements-plugin#287]
Hey @tadashi-aikawa ! I am the discord user who contacted you on the Obsidian Discord Server! See exchange:

![Discord_Z10jYpuV2N](https://github.com/tadashi-aikawa/obsidian-various-complements-plugin/assets/9662095/f578474c-5688-4122-ba2f-f84e7ec3fa13)
![Discord_PQwNS7JPuv](https://github.com/tadashi-aikawa/obsidian-various-complements-plugin/assets/9662095/89ae339f-fbe4-4e84-bedf-fd6593f56859)

As requested, here is my word/dictionary fork that I made that works with your plugin: 
https://raw.githubusercontent.com/ThomasEricB/words-pt-uncompressed-with-utf8-txt/master/wordsList.txt

This world file would also fix #281 ! Thank you for your time!

**Comment by tadashi-aikawa** [comment]
Hi, @ThomasEricB :)

Thanks for creating an issue and following #281 !

**Comment by tadashi-aikawa** [comment]
@ThomasEricB 
I have added it to the documentation 👍 

https://tadashi-aikawa.github.io/docs-obsidian-various-complements-plugin/4.%20Options/4.6.%20Custom%20dictionary%20complement/%E2%9A%99%EF%B8%8F%20Custom%20dictionary%20paths/#language-dictionary-file-url
