### ISSUE TITLE
[FR] Ignore words by regex everywhere

### ISSUE THREAD

**Issue by shnurks** [tadashi-aikawa/obsidian-various-complements-plugin#288]
I have a lot of formulas in my vault (and open note) which I don't want to be reccomended at all, so I would like to exclude them via a regex.
This is already possible for the custom dictionary, but it would be great if that was possible for everything.

**Comment by tadashi-aikawa** [comment]
Hi, @shnurks :)

That looks good👍 Do you use either 'Current file complements' or 'Current vault complements' ?

**Comment by shnurks** [comment]
I use both of them and I would really enjoy it if it also was available in both.

**Comment by tadashi-aikawa** [comment]
@shnurks 
Released in [v10.0.0-beta2](https://github.com/tadashi-aikawa/obsidian-various-complements-plugin/discussions/291) 🚀 

If you use BRAT, I would appreciate it if you could check it out before the official release.

**Comment by tadashi-aikawa** [comment]
@shnurks 
Released in [v10.0.0](https://github.com/tadashi-aikawa/obsidian-various-complements-plugin/releases/tag/10.0.0) 🚀
