### ISSUE TITLE
Take care uppercase when input words

### ISSUE THREAD

**Issue by chenyukang** [tadashi-aikawa/obsidian-various-complements-plugin#30]
According discussion in https://github.com/tadashi-aikawa/obsidian-various-complements-plugin/issues/29.

For instance, we have 'banana' in dictionary, if I type this word in the beginning of a sentence, I will type "Ba", but it will not complete currently, 
![image](https://user-images.githubusercontent.com/230646/143556340-745e6233-0df2-415f-ab4d-243198b17690.png)

I guess ignore uppercase will be better. If "Banana" is in candidate list will be perfect.

**Comment by chenyukang** [comment]
I read the source code, and will make a PR for this :)

**Comment by tadashi-aikawa** [comment]
Thank you for creating a issue! I'm looking forward to your PR 💚 

And, I'm going to release v3.0.0 this weekend, so it would be next week at the earliest to release that includes your PR.

**Comment by tadashi-aikawa** [comment]
@chenyukang 
I have uploaded latest pre-release version to `tadashi-aikawa/obsidian-plugin-dev-sandbox` 🚀

It probably works perfectly as you expected.

**Comment by chenyukang** [comment]
> @chenyukang I have uploaded the latest pre-release version to `tadashi-aikawa/obsidian-plugin-dev-sandbox` 🚀
> 
> It probably works as you expected.

Yes, it works like a charm! Awesome 🙌

But I can feel it a little bit slower when typing. 
Again, because my words list is long. 

I can image if we can use some algorithm like bucket sort will make it much quicker, split the list into 26 sub list according first character, and iterate the sub list only.

**Comment by chenyukang** [comment]
Here I find a corner case, I have `program` and `programming` and `programmer` in dictionary, 
but only internal link show in candiates:

![image](https://user-images.githubusercontent.com/230646/143608235-f09ef893-904d-46e1-abf7-e6599e36708a.png)

Reading the code, haven't figure out.

**Comment by chenyukang** [comment]
> Here I find a corner case, I have `program` and `programming` and `programmer` in dictionary, but only internal link show in candiates:
> 
> ![image](https://user-images.githubusercontent.com/230646/143608235-f09ef893-904d-46e1-abf7-e6599e36708a.png)
> 
> Reading the code, haven't figure out.

I'm working on a PR.

**Comment by tadashi-aikawa** [comment]
> Again, because my words list is long.

Would you tell me the number of your words? ( [this](https://github.com/first20hours/google-10000-english/blob/master/google-10000-english.txt) ? )

> I can image if we can use some algorithm like bucket sort will make it much quicker, split the list into 26 sub list according first character, and iterate the sub list only.

If everything works well after releasing v3.0.0 (which means nobody wants to partial match), I want to try it 👍

**Comment by chenyukang** [comment]
> > Again, because my words list is long.
> 
> Would you tell me the number of your words? ( [this](https://github.com/first20hours/google-10000-english/blob/master/google-10000-english.txt) ? )

yes

> 
> > I can image if we can use some algorithm like bucket sort will make it much quicker, split the list into 26 sub list according first character, and iterate the sub list only.
> 
> If everything works well after releasing v3.0.0 (which means nobody wants to partial match), I want to try it 👍

Nice, for prefix-matching trie tree is also efficient, but need a little bit more coding that sorting.

**Comment by chenyukang** [comment]
This VScode plugin is similar, you may have a reference 😏
https://github.com/yzhang-gh/vscode-dic-completion/blob/master/src/completion.ts

**Comment by tadashi-aikawa** [comment]
@chenyukang 
I have tried to use your custom dictionary. Sure, it is bit slow, but just few milliseconds.

![image](https://user-images.githubusercontent.com/9500018/143666819-24262c1e-5461-468b-9ab7-b295eb1e7122.png)

Would you show me console logs on Developer Tools?

**Comment by chenyukang** [comment]
![image](https://user-images.githubusercontent.com/230646/143668883-18792d27-75f1-4f58-81b9-8b6bc454d372.png)

**Comment by tadashi-aikawa** [comment]
Thanks. Surely, it is too slow..

**Comment by chenyukang** [comment]
> Thanks. Surely, it is too slow..

I think a hotkey or shortcut to toggle complementation will also useful, 😏

**Comment by tadashi-aikawa** [comment]
I agree. There is already a `Show suggestions` command that triggers manually, but it can't avoid trigger suggestions for now 😅 

![image](https://user-images.githubusercontent.com/9500018/143671240-f9cd3118-d6e5-49d1-a14f-cff26df3b2a7.png)

Probably I can, but I didn't know whether it needs or not.

**Comment by tadashi-aikawa** [comment]
I could make a slow environment by loading a dictionary you introduced first (about 500000words!). I will try to make it faster 😉 

![Uploading image.png…]()

**Comment by chenyukang** [comment]
> I could make a slow environment by loading a dictionary you introduced first (about 500000words!). I will try to make it faster 😉

I think it's not because my PC is not powerful. The time cost also related to the Obsidian contents. 
Essentially, a longer word list will cost more time. 

Handle internal link,  alias, dictionary complementation separately may help.
