### ISSUE TITLE
Devanagari Support

### ISSUE THREAD

**Issue by gautamneeraj** [tadashi-aikawa/obsidian-various-complements-plugin#306]
Could you please add Devanagari Script support for custom dictionaries?

Thank you,

**Comment by tadashi-aikawa** [comment]
Hi, @gautamneeraj :)

I do not plan to provide specific dictionary files as a custom dictionary. However, as discussed below, it is possible to include the dictionary files anyone created in the documentation.

https://github.com/tadashi-aikawa/obsidian-various-complements-plugin/discussions/297

**Comment by gautamneeraj** [comment]
Thank you, I've managed to create a custom dictionary for Nepali. Thank you!
