### ISSUE TITLE
Suggestion does not indicate what directory it's pulling from

### ISSUE THREAD

**Issue by Provmawn** [tadashi-aikawa/obsidian-various-complements-plugin#315]
In the suggestion is look like this:
![image](https://github.com/user-attachments/assets/b06c4bf0-6c0e-4677-9071-148b8ca7d1ae)

It should look like this:
![image](https://github.com/user-attachments/assets/a9a08ea1-759e-4ce0-94f6-df9248125e64)

**Comment by tadashi-aikawa** [comment]
Hi, @Provmawn :)

I think setting the [Description on suggestion](https://tadashi-aikawa.github.io/docs-obsidian-various-complements-plugin/4.%20Options/4.2.%20Appearance/%E2%9A%99%EF%B8%8F%20Description%20on%20suggestion/) to "full" will solve the issue.

**Comment by Provmawn** [comment]
Yeah that solved it. Thank you!
