### ISSUE TITLE
Improve performance of showing suggestions

### ISSUE THREAD

**Issue by tadashi-aikawa** [tadashi-aikawa/obsidian-various-complements-plugin#33]
From https://github.com/tadashi-aikawa/obsidian-various-complements-plugin/issues/30

**Comment by tadashi-aikawa** [comment]
About 500000words. (using https://raw.githubusercontent.com/dwyl/english-words/master/words.txt)

![](https://user-images.githubusercontent.com/9500018/143671459-eb58ba32-65b4-4e22-8f9b-3fba508acb65.png)

**Comment by tadashi-aikawa** [comment]
Ah... Against one's expectations, It is not working correctly to memoize 😱

**Comment by tadashi-aikawa** [comment]
@chenyukang
Probably, It will fast more than 100 times!! ✨ 

![image](https://user-images.githubusercontent.com/9500018/143673957-6acada8d-ca34-43f6-8233-0f1ed9b513a3.png)

**Comment by tadashi-aikawa** [comment]
Hi, @chenyukang!

I have uploaded the latest development version to `tadashi-aikawa/obsidian-plugin-dev-sandbox` 🚀  I re-architected the structure and improved both performances (about 10 times faster ✨) and quality of suggestions.

If there are no problems, I will release it tomorrow, officially :)

Kind regards.

**Comment by chenyukang** [comment]
> Hi, @chenyukang!
> 
> I have uploaded the latest development version to `tadashi-aikawa/obsidian-plugin-dev-sandbox` 🚀 I re-architected the structure and improved both performances (about 10 times faster ✨) and quality of suggestions.
> 
> If there are no problems, I will release it tomorrow, officially :)
> 
> Kind regards.

Thanks, I will have a try.

**Comment by chenyukang** [comment]
Oh, NICE！
![image](https://user-images.githubusercontent.com/230646/143681217-d529a1d9-0aba-4417-b8a7-50bb0144da10.png)

**Comment by chenyukang** [comment]
I suggest you add a default English dictionary, and give users an option whether to enable it.
The word list from Google search seems OK.

**Comment by tadashi-aikawa** [comment]
@chenyukang 
Thank you for your try! and I'm very happy to look at your screenshot! 😆 

> I suggest you add a default English dictionary, and give users an option whether to enable it.
The word list from Google search seems OK.

Nice suggestion 👍   does it mean https://github.com/first20hours/google-10000-english/blob/master/google-10000-english.txt ?

**Comment by chenyukang** [comment]
> @chenyukang Thank you for your try! and I'm very happy to look at your screenshot! 😆
> 
> > I suggest you add a default English dictionary, and give users an option whether to enable it.
> > The word list from Google search seems OK.
> 
> Nice suggestion 👍 does it mean https://github.com/first20hours/google-10000-english/blob/master/google-10000-english.txt ?

I think this one is better : https://github.com/first20hours/google-10000-english/blob/master/20k.txt

**Comment by tadashi-aikawa** [comment]
Thanks! I will consider using it.

**Comment by tadashi-aikawa** [comment]
I'll close this issue since it releases [v3.0.0](https://github.com/tadashi-aikawa/obsidian-various-complements-plugin/releases/tag/3.0.0).
