### ISSUE TITLE
Avoid complement when modify content in a sentence

### ISSUE THREAD

**Issue by chenyukang** [tadashi-aikawa/obsidian-various-complements-plugin#34]
I think this scenario is not we want:

![image](https://user-images.githubusercontent.com/230646/143683841-071e7a67-44b5-405f-9488-a3aac2cf885e.png)

In a long Chinese sentence, I want to modify some thing in the middle, the plugin complement the same sentence. I think it's because it treating a Chinese sentence as a word.

**Comment by tadashi-aikawa** [comment]
@chenyukang 
I think it will resolve when https://github.com/tadashi-aikawa/obsidian-various-complements-plugin/issues/7 is closed.

However, it may resolve if we can receive the key event that sends `BS` or `DEL` from CodeMirror or avoid `onTrigger`.

**Comment by chenyukang** [comment]
I'm looking at this package https://github.com/yanyiwu/nodejieba/blob/master/README_EN.md.

**Comment by tadashi-aikawa** [comment]
I found https://github.com/yishn/chinese-tokenizer, but it needed [CC-CEDICT](https://www.mdbg.net/chinese/dictionary?page=cc-cedict).

If `nodejieba` works as we expected, I want to use it :)

It is hard that Obsidian Plugins can't use libs in Node.js due to support on mobile 😓

**Comment by chenyukang** [comment]
> I found https://github.com/yishn/chinese-tokenizer, but it needed [CC-CEDICT](https://www.mdbg.net/chinese/dictionary?page=cc-cedict).
> 
> If `nodejieba` works as we expected, I want to use it :)
> 
> It is hard that Obsidian Plugins can't use libs in Node.js due to support on mobile 😓

emm..
![image](https://user-images.githubusercontent.com/230646/143685255-9561e0f8-ac8a-47f7-b4b2-8d897c6a9f39.png)

**Comment by tadashi-aikawa** [comment]
Oh.. sorry, the cause of this issue seems https://github.com/tadashi-aikawa/obsidian-various-complements-plugin/commit/c25aae86a8dc1925d123601509765bd05b55b0a8

**Comment by tadashi-aikawa** [comment]
@chenyukang 
Could you please continue with https://github.com/tadashi-aikawa/obsidian-various-complements-plugin/issues/7 regarding Chinese language support?

It will be beneficial to others, too :)

**Comment by tadashi-aikawa** [comment]
I'm going to fix the below issue here.

> Oh.. sorry, the cause of this issue seems c25aae8

**Comment by chenyukang** [comment]
> @chenyukang Could you please continue with #7 regarding Chinese language support?
> 
> It will be beneficial to others, too :)

I'd like to, but I haven't wrote TypeScript code, actually this is my first time working on a plugin.
Do you have any IM, I may need some help :)

**Comment by tadashi-aikawa** [comment]
@chenyukang 
Don't worry! `continue` means not developing but commenting about Chinese support (ex: tokenizer library). I have wanted to support the Chinese, so I'll implement it 💪

**Comment by chenyukang** [comment]
> @chenyukang Don't worry! `continue` means not developing but commenting about Chinese support (ex: tokenizer library). I have wanted to support the Chinese, so I'll implement it 💪

I have a naïve question, if a third party library was added into a plugin, how Obsidian find it, since the plugin's directory only have a main.js. 
![image](https://user-images.githubusercontent.com/230646/143685969-cc0e397f-0f04-4e30-9ee5-263517b0f502.png)

**Comment by chenyukang** [comment]
Oh, TinySegmenter is packed into main.js.
How to achieve this packing. I only run 'npm run dev' in my plugin directory, and then copy to plugins. And Obsidian can not find the package: 

```
app.js:1 Plugin failure: various-complements-yukang Error: Cannot find module 'chinese-tokenizer'
Require stack:
```

**Comment by chenyukang** [comment]
> Oh, TinySegmenter is packed into main.js. How to achieve this packing. I only run 'npm run dev' in my plugin directory, and then copy to plugins. And Obsidian can not find the package:
> 
> ```
> app.js:1 Plugin failure: various-complements-yukang Error: Cannot find module 'chinese-tokenizer'
> Require stack:
> ```

Got it, it's in external.

**Comment by tadashi-aikawa** [comment]
@chenyukang 
I have updated at https://github.com/tadashi-aikawa/obsidian-plugin-dev-sandbox/releases/tag/0.0.14.

That solution is not ideal, but practical enough, I think.

**Comment by tadashi-aikawa** [comment]
> Got it, it's in external.

It is easy to add into `external`. Of course, it is better to add dependencies by `npm install`. (I think it doesn't need :))

**Comment by tadashi-aikawa** [comment]
> I have updated at https://github.com/tadashi-aikawa/obsidian-plugin-dev-sandbox/releases/tag/0.0.14.
> That solution is not ideal, but practical enough, I think.

Ah.. it seems not to resolve.. 😅

**Comment by chenyukang** [comment]
Another trivial issue, current file contains a sentence with `TypeScript.`, the complement have this:
![image](https://user-images.githubusercontent.com/230646/143767189-997a8232-3c26-4be6-b7ae-809602b2a441.png)

**Comment by tadashi-aikawa** [comment]
I could reproduce. It is a very mysterious bug. 😭

**Comment by tadashi-aikawa** [comment]
Ah.. I understood.

**Comment by tadashi-aikawa** [comment]
I fixed. I'll release v3.0.1 soon.

**Comment by chenyukang** [comment]
> I fixed. I'll release v3.0.1 soon.

Yes, removed the `types`. And can we remove the end `。`？
I guess this also depends on Chinese support.

Btw, I think we should add some unit test, otherwise you will introduce errors when modify the code.

**Comment by tadashi-aikawa** [comment]
> can we remove the end 。？
> I guess this also depends on Chinese support.

You're right.

> I think we should add some unit test, otherwise you will introduce errors when modify the code.

Sure. I am going to add tests in when we should. (Perhaps, `Suggester` at first)

**Comment by chenyukang** [comment]
I fix this issue by this:
https://github.com/chenyukang/obsidian-various-complements-plugin/commit/a07487e1f0ca20ee748add8caea4bb9e2f61a313

It's a hotfix when Chinese tokenizer is not available. Maybe we can add an option "only complement English". 

This maybe helpful for those non-English native users like me. 😏

**Comment by tadashi-aikawa** [comment]
> Maybe we can add an option "only complement English".

LGTM 👍   I'll add the option.

**Comment by tadashi-aikawa** [comment]
Move to https://github.com/tadashi-aikawa/obsidian-various-complements-plugin/issues/46
