### ISSUE TITLE
[Help/Question] Trim `\t` Feature

### ISSUE THREAD

**Issue by FelipeRearden** [tadashi-aikawa/obsidian-various-complements-plugin#36]
Hello @tadashi-aikawa !!!!

Would you mind helping how to use the `\t` Feature from version `0.3.1` ? 

Sorry if it is a dumb question :)

Thanks :)

**Comment by tadashi-aikawa** [comment]
@FelipeRearden 
It is for removing noisy suggestions including `\t` (<TAB>).

Taking the following code as an example

```
def main():
    pass
```

As of v3.0.0, It showed a suggestion `\tpass` rather than `pass` because it regarded `\tpass` as one word.

As of v3.1.0, it can show a suggestion `pass`.

**Comment by FelipeRearden** [comment]
Hello @tadashi-aikawa !!!!

Thanks for the answer ! Now I get it :)

I was thinking that we could use `\t` as a  delimeter in the custom dictionary :)

I have an idea about a new feature that I will show to you. Maybe you will like :)

Have a great day!!!!
