### ISSUE TITLE
[Feature Request] Custom Dictionary Delimeter to reduce the text information on context/suggestion menu 

### ISSUE THREAD

**Issue by FelipeRearden** [tadashi-aikawa/obsidian-various-complements-plugin#37]
Hello @tadashi-aikawa !!!!!!!

My FR is about a new delimeter in the Custom Dictionary to hide/reduce the amount of text showed in the suggestion menu (context menu)

## My Workflow

I have some tokens that I use to store some Lorem Ipsum text generator from  https://www.lipsum.com

See below 3 of then:

Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.`<Lor_G><loi> `

Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit `<Lor_M><loi> `

Lorem Ipsum is simply dummy text `<Lor_S><loi> `

It's useful for me to have this because I'm always trying some CSS snippets and I wanna see/tweak how it looks on different amount of texts

Another usage is from users who needs to write documentation and have a a bunch of definitions of concepts like _mean_ ,_standard deviation_ ... and can create tokens with a definitions to avoid having to write the definition for every new documentation :)

## My FR

A new delimeter that could be placed in the note to limit the amount of characters that will be showed in the suggestion menu. Following my example, something like this:

Delimeter= `<STOP>`

Lorem Ipsum `<STOP>` is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.`<Lor_G><loi>`

Neque porro`<STOP>`quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit `<Lor_M><loi>`

Lorem`<STOP>` Ipsum is simply dummy text `<Lor_S><loi>`

---

Let me know if you need more information :)

Thanks for reading this :)

Have a great day!

**Comment by tadashi-aikawa** [comment]
Hi, @FelipeRearden. Thank you for your FR!

I understood and thought I needed it 👍

**Comment by tadashi-aikawa** [comment]
@FelipeRearden 

I have updated beta version to [obsidian-various-complements-plugin-beta](https://github.com/tadashi-aikawa/obsidian-various-complements-plugin-beta/releases/tag/3.3.0.b2) 🚀 

Please confirm whether it works as you expected by using [BRAT](https://github.com/TfTHacker/obsidian42-brat).

![image](https://user-images.githubusercontent.com/9500018/145663150-8809fa1e-23a9-4a05-bd46-f81d6caadf28.png)

![2021-12-11](https://user-images.githubusercontent.com/9500018/145663296-626ea15a-b773-46c5-b849-a1347634b124.gif)

**Comment by FelipeRearden** [comment]
> I have updated beta version to [obsidian-various-complements-plugin-beta](https://github.com/tadashi-aikawa/obsidian-various-complements-plugin-beta/releases/tag/3.3.0.b2) 🚀 

Hello @tadashi-aikawa !!!!!!!!!

Thank you very very very much !!!!!!!!!!

It's working perfect !!!!!

I loved that you created a text field in the Settings for us to customize the delimeter !!!! It's AMAZING

Working perfect on version `3.3.0.b2` Obsidian `0.12.19`

I wish you a fantastic day!!!!!

**Comment by tadashi-aikawa** [comment]
Released as [v3.3.0](https://github.com/tadashi-aikawa/obsidian-various-complements-plugin/releases/tag/3.3.0) 🚀

**Comment by FelipeRearden** [comment]
> Released as [v3.3.0](https://github.com/tadashi-aikawa/obsidian-various-complements-plugin/releases/tag/3.3.0) 🚀 

Working perfect on version `v3.3.0` Obsidian `0.12.19`

Thanks @tadashi-aikawa !!!!!!!
