### ISSUE TITLE
[Feature Request] cycle through suggestions with other than arrow keys

### ISSUE THREAD

**Issue by annenpolka** [tadashi-aikawa/obsidian-various-complements-plugin#38]
I'm used to cycling through suggestions with Tab/Ctrl+Tab and accepting one with Enter Key. (I think it's vscode's default behavior, as I remember.)
It's so helpful if there is an option(or keybindings?) to do that.

Anyway, thanks for your great works! Not only this plugin but I'm also amazed by your other stuff.

**Comment by tadashi-aikawa** [comment]
Hi, @annenpolka. Thank you for your FR!

It looks good. I'll add the option :)

(For your reference: My VSCode's behavior is not the same that you wrote, but this plugin's behavor 🤔)

**Comment by annenpolka** [comment]
@tadashi-aikawa Let me correct, go back with Shift+Tab, not Ctrl+Tab. (As you may noticed, Ctrl+Tab will conflict with switching tabs keybindings. I just misswrote it 😰)

**Comment by tadashi-aikawa** [comment]
@annenpolka 

I have updated beta version to [obsidian-various-complements-plugin-beta](https://github.com/tadashi-aikawa/obsidian-various-complements-plugin-beta/releases/tag/3.3.0.b3) 🚀 

If you use [BRAT](https://github.com/TfTHacker/obsidian42-brat), please confirm whether it works as you expected.

![image](https://user-images.githubusercontent.com/9500018/145664597-42df1bda-c41f-4e43-aab4-5c40415d7112.png)

**Comment by annenpolka** [comment]
@tadashi-aikawa 

Installed beta with BRAT.
And yes, this is exactly what I wanted! Looks good to me😁

**Comment by tadashi-aikawa** [comment]
Released as [v3.3.0](https://github.com/tadashi-aikawa/obsidian-various-complements-plugin/releases/tag/3.3.0) 🚀
