### ISSUE TITLE
Does the Android terminal currently support custom dictionaries?

### ISSUE THREAD

**Issue by tyf2018** [tadashi-aikawa/obsidian-various-complements-plugin#39]
Does the Android terminal currently support custom dictionaries? No matter the absolute path or the relative path, the Android terminal will report an error.

 I want to confirm whether my setting is incorrect or not supported at the moment, thank you!

**Comment by tadashi-aikawa** [comment]
> Does the Android terminal currently support custom dictionaries?

Yes, it supports for Android.

https://github.com/tadashi-aikawa/obsidian-various-complements-plugin#custom-dictionary-complement

![image](https://user-images.githubusercontent.com/9500018/144701398-08570eb9-2507-4407-935e-50ee3c323e67.png)

**Comment by tyf2018** [comment]
Thank you, the problem has been resolved.
It turns out that this path takes effect:
```
/00数据管理_vault/template/VC词库/VC词库1.txt
```
And this will report an error:
```
VC词库1.txt
```
