### ISSUE TITLE
Is it possible to add Spanish Language?

### ISSUE THREAD

**Issue by EhuddR** [tadashi-aikawa/obsidian-various-complements-plugin#4]
Hi! I must say that this is a great plugin, but i was wonder if you can add Spanish Language to it. It will be really helpful. Best regards.

**Comment by tadashi-aikawa** [comment]
Hi, @EhuddR! Thank you for your comment 😄

This plugin supports languages whose word break is whitespace, so I think Spanish is one of them. I'd appreciate it if you could tell me what's not working as expected.

https://user-images.githubusercontent.com/9500018/109076904-b3041900-773e-11eb-8323-c9abe066df02.mp4

Best regards.

**Comment by EhuddR** [comment]
Thanks! I don't know why the plugin was not working in my PC. I actualizad my Obsidian to V. 0.11.3 and now is working properly. The plugins is amazing!
