### ISSUE TITLE
Version 3.0 and above, the candidate words obtained are incomplete

### ISSUE THREAD

**Issue by tyf2018** [tadashi-aikawa/obsidian-various-complements-plugin#41]
Version 3.0 and above, the candidate words obtained are incomplete, and **there is no prompt for the existing phrases in the custom dictionary**.
The 2.0 version works normally.

Screenshot of the above situation:

![image](https://user-images.githubusercontent.com/56342788/144707174-d697a3b0-d233-4c17-baa2-8b42d64a15da.png)

Can you consider fixing this problem? Because I really like the new features of the 3.0 version, and the corresponding speed is faster, unlike the 2.0 version, there is a stuttering phenomenon.

Best wishes!

**Comment by tadashi-aikawa** [comment]
It is because version 3.0 and above only use prefix match, not partial match. 

https://github.com/tadashi-aikawa/obsidian-various-complements-plugin/releases

> Use prefix match instead of the partial match to reduce noisy suggestions

It needed to improve performance, so it is not easy to support them. If you want to use partial match at the expense of speed, please create another issue as a Feature Request. (I'll consider it if many people need it.)

Best regards.

**Comment by tadashi-aikawa** [comment]
I just came up with a workaround implementation.

You don't need to create a new issue, maybe :)

**Comment by tyf2018** [comment]
> I just came up with a workaround implementation.
> 

Wow, great, look forward to it.

**Comment by tadashi-aikawa** [comment]
Hi, @tyf2018.

I have uploaded beta version to [tadashi-aikawa/obsidian-plugin-dev-sandbox](https://github.com/tadashi-aikawa/obsidian-plugin-dev-sandbox/releases/tag/3.2.0.b1) 🚀 

Could you confirm the above release note and try it by using BRAT?

**Comment by tyf2018** [comment]
> Could you confirm the above release note and try it by using BRAT?
> 

Your development efficiency is amazing! But I am outside now, I will continue to go back to the computer at night.

**Comment by tyf2018** [comment]
> Could you confirm the above release note and try it by using BRAT?

After trial, it runs normally. Users can customize the settings according to their personal needs, which is very good! It is recommended to add it to the official version, thank you!

**Comment by tadashi-aikawa** [comment]
> Users can customize the settings according to their personal needs, which is very good! It is recommended to add it to the official version,

Of course 👍 I want to release it this weekend.

**Comment by tadashi-aikawa** [comment]
Released at [v3.2.0](https://github.com/tadashi-aikawa/obsidian-various-complements-plugin/releases/tag/3.2.0) 🚀 .
