### ISSUE TITLE
Assigning a shortcut key for switching between Partial match and Prefix match

### ISSUE THREAD

**Issue by tyf2018** [tadashi-aikawa/obsidian-various-complements-plugin#42]
Hi，@tadashi-aikawa 
Would you consider assigning a shortcut key for switching between Partial match and Prefix match? In this way, users can switch as needed according to usage scenarios.

Best Regards.

**Comment by chenyukang** [comment]
I think it's OK.

**Comment by tyf2018** [comment]
> I think it's OK.
> 

不好意思，@错人了

**Comment by tadashi-aikawa** [comment]
@tyf2018 
I have added and uploaded as https://github.com/tadashi-aikawa/obsidian-plugin-dev-sandbox/releases/tag/3.2.0.b2 🚀

**Comment by tadashi-aikawa** [comment]
Released at [v3.2.0](https://github.com/tadashi-aikawa/obsidian-various-complements-plugin/releases/tag/3.2.0) 🚀 .
