### ISSUE TITLE
Possibly change the name to "Intelligent completions"

### ISSUE THREAD

**Issue by seatrout** [tadashi-aikawa/obsidian-various-complements-plugin#43]
If I may say this without being rude, the name "Intelligent complements" is confusing to this native English speaker at least. It seems that the plugin actually makes intelligent _completions_ — I'm not sure what an intelligent _complement_ would look like. This must cut down on the number of people attracted to try it out.

**Comment by tadashi-aikawa** [comment]
Hi, @seatrout . Thank you for your suggestion :)

I wanted to use `Auto Complete` (which already exists), so I agree. However, it will be a cost; therefore, I don't want to change the plugin name.

Best regards.
