### ISSUE TITLE
[Feature Request] allow new line characters (\n or similar) in custom dictionary

### ISSUE THREAD

**Issue by marcjulianschwarz** [tadashi-aikawa/obsidian-various-complements-plugin#44]
Before finding your plugin I was using the "Text Snippets" plugin to get a semi-autocompletion by defining snippets similar to the custom dictionary in your "Various Complements" plugin.
However with text snippets you were able to use `$$nl$$` to indicate a new line in a snippet. I think this would be a nice addition to your plugin since it will allow for more complex autocompletions where whole structures can be used and not only words/one sentence.

**Comment by tadashi-aikawa** [comment]
Hi, @marcjulianschwarz . Thank your for your FR!

It looks good to me. I'll try it :)

**Comment by tadashi-aikawa** [comment]
@marcjulianschwarz 

I have updated beta version to [obsidian-various-complements-plugin-beta](https://github.com/tadashi-aikawa/obsidian-various-complements-plugin-beta/releases/tag/3.3.0.b1) 🚀 

If you use [BRAT](https://github.com/TfTHacker/obsidian42-brat), please confirm whether it works as you expected. If you don't use it, please verify the below GIF.

![2021-12-11](https://user-images.githubusercontent.com/9500018/145662320-6a50335c-ab79-4a12-a858-c75237117013.gif)

**Comment by marcjulianschwarz** [comment]
Looks great, thank you very much. I tested it with BRAT and it works like a charm!
Great work, can't wait for the official release :)

**Comment by tadashi-aikawa** [comment]
Released as [v3.3.0](https://github.com/tadashi-aikawa/obsidian-various-complements-plugin/releases/tag/3.3.0) 🚀
