### ISSUE TITLE
Only complement English on current file complement

### ISSUE THREAD

**Issue by tadashi-aikawa** [tadashi-aikawa/obsidian-various-complements-plugin#46]
See https://github.com/tadashi-aikawa/obsidian-various-complements-plugin/issues/34#issuecomment-982671358

**Comment by tadashi-aikawa** [comment]
@chenyukang 
Released as [v3.3.0](https://github.com/tadashi-aikawa/obsidian-various-complements-plugin/releases/tag/3.3.0) 🚀

**Comment by chenyukang** [comment]
> @chenyukang Released as [v3.3.0](https://github.com/tadashi-aikawa/obsidian-various-complements-plugin/releases/tag/3.3.0) 🚀

Thanks you very much, will check it out.
