### ISSUE TITLE
Bug/Feature Request: Custom trigger to avoid conflict with slash commands

### ISSUE THREAD

**Issue by frankreporting** [tadashi-aikawa/obsidian-various-complements-plugin#47]
This is a great plugin, and I see lots of good ideas for further development on here, but there appears to be a conflict between Various Complements and Obisidian's new slash commands feature. In any case, you may not want the frequent interruption of the suggestions, but a deliberate trigger might solve both problems. 

**Problem:**

Currently, if you type `/` plus two characters, Obsidian's commands list comes up and filters to your first two characters, but on the third character, it disappears. This is consistently happening on my end, but when I disable Various Complements, I can type as many characters as I want to filter the list of slash commands.

**Expected Behavior/Possible Solution:**

Many apps now employ the idea of inline commands using a dedicated symbol. In fact this seems to be a new trend across productivity apps. Google Docs has you type "@" to trigger actions. Notion, Obsidian and Slack all have "slash commands." And Notion uses different symbols to trigger different kinds of actions, like `@` to tag a page and `/` to insert a specific type of block. Dropbox Paper does something similar, and I could go on. 

Instead of being "always on," what if you could set your preferred trigger for Various Complements, in the same way that the [Natural Language Dates](https://github.com/argenos/nldates-obsidian) plugin allows you to specify what symbol will initiate the action to insert a date? In this way, even with multiple plugins, you could have, say, Various Complements, Natural Language Dates, and Obsidian slash commands all working at the same time, and you decide which one you want to trigger and when.

My own setup might be something like this:

`^` = Natural Language Dates
`@` = Various Complements
`/` = Obsidian commands

**Comment by tadashi-aikawa** [comment]
Hi, @frankreporting. Thank you for your kind bug report!

I could reproduce and fix it. Please wait the next release :)

> Possible Solution:

I will use this as a reference when I increase customizability in the future.

**Comment by tadashi-aikawa** [comment]
@frankreporting 
I have released to [v3.3.1](https://github.com/tadashi-aikawa/obsidian-various-complements-plugin/releases/tag/3.3.1) 🚀

Please confirm whether it works as you expected.

**Comment by frankreporting** [comment]
Looks like it's fixed! That was quick!

Thanks for your consideration of my feature request, too. I was actually considering learning how to develop plugins just so I could pull off something very much like what you're doing, and I'd love to be able to designate a trigger.

Thanks for all your work on this!
