### ISSUE TITLE
wow this is amazing! any chance it can complete tags?

### ISSUE THREAD

**Issue by zeltak** [tadashi-aikawa/obsidian-various-complements-plugin#48]
Hi, first of all thank you so much for this truly amazing plugin, it makes obsidian so much better!

one thing i would love is a way to complete tags based on all the tags in the vault

this would be super useful especially for the YAML front matter which dosent support tag completion

would that be possible to add as an option?

thx so much!

Z

**Comment by tadashi-aikawa** [comment]
Hi, @zeltak. Thank you for your Feature Request!

> this would be super useful especially for the YAML front matter which dosent support tag completion

Surelly, I perfectly agree with you. I'll try it. 👍

**Comment by tadashi-aikawa** [comment]
@zeltak 
I noticed that YAML front matter seems to support tag completion.

![image](https://user-images.githubusercontent.com/9500018/148640225-1f479cf9-aa0a-42ba-a485-efc8bcf6935e.png)

Doesn't it satisfy your requirements?

**Comment by zeltak** [comment]
thx!

well only if you prefix with `#` which is no really helpful :)

ie

```
tags:
  - cook-tips
  - ramen
  - japan
```

this syntax (the standard if i understand for other YAML users) doesn't allow completion

that is i have to start with the `#` sign then go back and delete all the # manually..kind of annoying #51 
would be great to complete the tags without the `#` 

thx so much

Z

**Comment by tadashi-aikawa** [comment]
Thank you for the detail explanation :)  I see.

**Comment by tadashi-aikawa** [comment]
Hi, @zeltak :)

I have released [v5.6.0.beta1](https://github.com/tadashi-aikawa/obsidian-various-complements-plugin-beta/releases/tag/5.6.0.beta1).

If you use [BRAT](https://github.com/TfTHacker/obsidian42-brat), please confirm whether it works as you expected. 

![image](https://user-images.githubusercontent.com/9500018/153699665-c1a1662e-ef43-4de9-8d09-179599f37fc4.png)

**Comment by zeltak** [comment]
wow amazing, just tested it out and its perfect!

thx so much!!

Z

**Comment by tadashi-aikawa** [comment]
Thank you for your confirming, @zeltak !

By the way, I have decided to release this feature as a Front matter complement. I have released a new beta version as [#74 (comment)](https://github.com/tadashi-aikawa/obsidian-various-complements-plugin/issues/74#issuecomment-1038766477).

If you are interested in it, it would be great to use it and give feedback to me 😄

**Comment by tadashi-aikawa** [comment]
I have released [v5.6.0](https://github.com/tadashi-aikawa/obsidian-various-complements-plugin/releases/tag/5.6.0) 🚀

Many thanks!

**Comment by zeltak** [comment]
my pleasure! any thanks to you for your amazing work!
