### ISSUE TITLE
[BUG]: URL components are being suggested

### ISSUE THREAD

**Issue by chrisgrieser** [tadashi-aikawa/obsidian-various-complements-plugin#50]
<img width="642" alt="Screenshot 2021-12-17 20 07 09" src="https://user-images.githubusercontent.com/73286100/146595563-e6b805f8-4ca2-4d63-90ce-4caeafe62b91.png">

Components of URLs that are included in the note are suggested, too, which probably makes little sense. I'd simply tell the plugin to ignore any url it finds?

**Comment by tadashi-aikawa** [comment]
Hi, @chrisgrieser. Thank you for your bug report.

I couldn't reproduce it. Could you tell me more details?

- URL on file
- settings

**Comment by tadashi-aikawa** [comment]
I could reproduce it. I'll fix it 👍

**Comment by tadashi-aikawa** [comment]
@chrisgrieser 
I have released to [v3.4.0](https://github.com/tadashi-aikawa/obsidian-various-complements-plugin/releases/tag/3.4.0) 🚀

Please confirm whether it works as you expected.

**Comment by chrisgrieser** [comment]
yep, can confirm, doe snot occur anymore. Thanks for the quick fix!
