### ISSUE TITLE
Plugin name and description

### ISSUE THREAD

**Issue by WhiteNoiseDev** [tadashi-aikawa/obsidian-various-complements-plugin#51]
Hi
I think it would be better if the plugin name and/or the description contain the words "autocompletion", "word suggestion", and "link suggestion". I think many people miss this plugin because they don't understand what it does from the name/description.

Thanks for your work!

**Comment by tadashi-aikawa** [comment]
Hi, @WhiteNoiseDev. Thank you for your suggestion :)

I will not rename the plugin name because of https://github.com/tadashi-aikawa/obsidian-various-complements-plugin/issues/43. On the other hand, it supposes to be better to update a description as follows.

```
This plugin for Obsidian enables you to complete words like the auto-completion of IDE.
```

What do you think?

**Comment by WhiteNoiseDev** [comment]
That's better! Thanks!

**Comment by tadashi-aikawa** [comment]
I have created PR on `obsidian-release`.

https://github.com/obsidianmd/obsidian-releases/pull/694
