### ISSUE TITLE
How to produce original "\t" and "\n"

### ISSUE THREAD

**Issue by shui-dun** [tadashi-aikawa/obsidian-various-complements-plugin#52]
How to produce original "\t" and "\n" in dictionary files, I tried "\\\\t" and "\\\\n", but it doesn't work.

**Comment by tadashi-aikawa** [comment]
Hi, @shui-dun .

It can't, but I'll try to make it possible :)

**Comment by tadashi-aikawa** [comment]
@shui-dun 
I have implemented it. Is it what as you expected?

![2021-12-22](https://user-images.githubusercontent.com/9500018/147031935-f7c68957-039e-4950-a3be-6b917981af89.gif)

**Comment by shui-dun** [comment]
Perfect, thanks! 😄

**Comment by tadashi-aikawa** [comment]
I'll release soon, please wait :)

**Comment by tadashi-aikawa** [comment]
I have released to [v3.5.0](https://github.com/tadashi-aikawa/obsidian-various-complements-plugin/releases/tag/3.5.0) 🚀

**Comment by shui-dun** [comment]
I have upgraded, thanks again 😄
