### ISSUE TITLE
Input space will not disappear candidate list in new version of Ob

### ISSUE THREAD

**Issue by chenyukang** [tadashi-aikawa/obsidian-various-complements-plugin#53]
I update Obsidian to v0.13.14, when I input words, the candidate list will not disappear when I finished a word(with space inputed), which is a different behavior as before.

![image](https://user-images.githubusercontent.com/230646/147020690-34643e23-a7b8-490c-b4e5-2289369c2e7e.png)

Maybe related to Live Preview.

**Comment by tadashi-aikawa** [comment]
@chenyukang 
Thank you for your bug report! I could reproduce it.

**Comment by tadashi-aikawa** [comment]
I have released to [v3.4.2](https://github.com/tadashi-aikawa/obsidian-various-complements-plugin/releases/tag/3.4.2) 🚀
