### ISSUE TITLE
Manual trigger

### ISSUE THREAD

**Issue by WhiteNoiseDev** [tadashi-aikawa/obsidian-various-complements-plugin#57]
Hi,
It seems that when I disable auto-complete (with toggle autocomplete), the manual trigger "show suggestion" (ctrl-space) is also disabled. I find this odd. I prefer to have autocomplete off and manual complete on. 

It would be nice to have a toggle for this in the settings too.

Thanks for you work

**Comment by tadashi-aikawa** [comment]
Hi, @WhiteNoiseDev.

When I implemented it, that was difficult, but I'll survey it again :)

**Comment by tadashi-aikawa** [comment]
It seems possible by using unofficial, closed API (`isOpen` getter) both on the New and Legacy editors.

**Comment by tadashi-aikawa** [comment]
@WhiteNoiseDev 
I have updated beta version to [obsidian-various-complements-plugin-beta](https://github.com/tadashi-aikawa/obsidian-various-complements-plugin-beta/releases/tag/4.4.0.beta1) 🚀 

If you use [BRAT](https://github.com/TfTHacker/obsidian42-brat), please confirm whether it works as you expected.

**Comment by WhiteNoiseDev** [comment]
Thanks, I tried quickly and it seems to be working fine. 
I am not sure if everybody will like the removal of `Toggle Auto-complete`.
Perhaps, you can find a way to reintroduce it and connect it to the settings toggle "Show suggestions command"

Thanks for you work.

**Comment by tadashi-aikawa** [comment]
Thank you for your confirming :)

I want to release v4.0.0 this weekend. 

> I am not sure if everybody will like the removal of Toggle Auto-complete.

I had wanted to remove the option because it often confuses anyone with `Show suggestions`. However, if anyone needs it, I will re-add the options depending on their reasons.

**Comment by tadashi-aikawa** [comment]
@WhiteNoiseDev 
I have released to [v4.0.0](https://github.com/tadashi-aikawa/obsidian-various-complements-plugin/releases/tag/4.0.0) 🚀

Please confirm whether it works as you expected.

**Comment by WhiteNoiseDev** [comment]
Yeah, it works great!
