### ISSUE TITLE
Load custom dictionaries from URL

### ISSUE THREAD

**Issue by tadashi-aikawa** [tadashi-aikawa/obsidian-various-complements-plugin#60]
![image](https://user-images.githubusercontent.com/9500018/147774876-19380417-7c74-4f33-b516-7458632248dc.png)

**Comment by FelipeRearden** [comment]
That's a fantastic idea @tadashi-aikawa :)

**Comment by tadashi-aikawa** [comment]
Used https://github.com/tadashi-aikawa/obsidian-various-complements-plugin/issues/33#issuecomment-980638282 as a default URL.

**Comment by tadashi-aikawa** [comment]
https://raw.githubusercontent.com/first20hours/google-10000-english/master/google-10000-english-no-swears.txt is better

**Comment by tadashi-aikawa** [comment]
I have updated beta version to [obsidian-various-complements-plugin-beta](https://github.com/tadashi-aikawa/obsidian-various-complements-plugin-beta/releases/tag/4.0.0.beta4) 🚀

**Comment by tadashi-aikawa** [comment]
I have released to [v4.0.0](https://github.com/tadashi-aikawa/obsidian-various-complements-plugin/releases/tag/4.0.0) 🚀

Please confirm whether it works as you expected.
