### ISSUE TITLE
Bug: a word shouldn't trigger the suggestion of itself

### ISSUE THREAD

**Issue by chrisgrieser** [tadashi-aikawa/obsidian-various-complements-plugin#61]
<img width="295" alt="Screenshot 2021-12-31 21 26 52" src="https://user-images.githubusercontent.com/73286100/147838273-6ee70a72-f338-4010-a7b8-62856634998c.png">

As you can see in this image, I typed the word "innovate" and get the very same word as a suggestion for auto-completion. Of course, this is rather useless.

While this bug more mostly an annoyance than a big problem, it does add unnecessary noise, something which autocompletion-functions should always try to reduce in my view.

**Comment by tadashi-aikawa** [comment]
Hi, @chrisgrieser.

I didn't reproduce it. Is `innovate` a word registered in the user dictionary?

![image](https://user-images.githubusercontent.com/9500018/147842853-3c197187-be41-4978-b168-d92d4f9dfb59.png)

**Comment by tadashi-aikawa** [comment]
![2022-01-01](https://user-images.githubusercontent.com/9500018/147842875-8600c981-d358-4157-921b-caa516285642.gif)

**Comment by tadashi-aikawa** [comment]
I have closed this issue for a moment. Please reopen if you found steps to reproduce.

**Comment by chrisgrieser** [comment]
couldn't reproduce it either, that's way I haven't gotten back – I'll report back when I know what caused it! 🙏

**Comment by tadashi-aikawa** [comment]
Sure! I hope nothing happens 🙏
