### ISSUE TITLE
[FR] Ability to select which key accepts the completion

### ISSUE THREAD

**Issue by Aaron-Bopp** [tadashi-aikawa/obsidian-various-complements-plugin#63]
I am often running into the situation where I will be at the end of the line and want to press enter to go to the next line, but there is currently a suggestion for autocompletion. If I press enter I will accept the completion, so I have to Esc and then press enter. If I could set accepting the completion to another key I could avoid this.

**Comment by tadashi-aikawa** [comment]
Hi, @Aaron-Bopp :)

The `Ignore Enter key` option enables you to select a suggestion only by `Tab` key. Please try it.

![image](https://user-images.githubusercontent.com/9500018/147998256-a90fce85-0e11-4be1-943d-ac9600130074.png)

**Comment by Aaron-Bopp** [comment]
Ahh, I didn't even realize tab could select the suggestion, because I had it set to cycle through the suggestions. I still think it would be valuable to set any key to accept the selection and to cycle through them.

**Comment by tadashi-aikawa** [comment]
I see, I understand.

Which key do you want to use for select a suggestion?

**Comment by Aaron-Bopp** [comment]
I think that having the options of ctrl/shift/alt enter would be a good start. It sounds like it's not possible to make it an assignable hotkey?

**Comment by tadashi-aikawa** [comment]
Thanks!

> It sounds like it's not possible to make it an assignable hotkey?

Maybe possible. On the other hand, it seems impossible to assign keys like the `Hotkeys` setting because this is not a command and an unofficial (unsafe) implementation.

I think only a few keys are possibly assigned to select the suggestion. Therefore using a select interface suppose easy to understand, like the `Additional cycle through suggestions keys` option.

**Comment by Aaron-Bopp** [comment]
Ahh, thank you for the explanation.

**Comment by tadashi-aikawa** [comment]
@Aaron-Bopp 
I have updated beta version to [obsidian-various-complements-plugin-beta v5.0.0-beta4](https://github.com/tadashi-aikawa/obsidian-various-complements-plugin-beta/releases/tag/5.0.0.beta4) 🚀 

If you use [BRAT](https://github.com/TfTHacker/obsidian42-brat), please confirm whether it works as you expected. 

If you don't use it, please wait for a next release, v5.0.0.

**Comment by Aaron-Bopp** [comment]
I have tested this and it works great, thanks for the options!

**Comment by tadashi-aikawa** [comment]
@Aaron-Bopp 
I have released to [v5.0.0](https://github.com/tadashi-aikawa/obsidian-various-complements-plugin/releases/tag/5.0.0) 🚀

Please confirm whether it works as you expected.

**Comment by tadashi-aikawa** [comment]
Let me close this issue because it worked fine in the beta version :)
