### ISSUE TITLE
[FR] Suggest Internal Links With Alias

### ISSUE THREAD

**Issue by almogtzabari** [tadashi-aikawa/obsidian-various-complements-plugin#64]
Hi,
I would like to ask for a feature, if it's okay.
I'll explain with an example:
Let's say I have a note called `04-01-2022 feature-request.md` which has an alias `feature-request`.

### Current behavior
If I start typing `feature-request` it suggest me `[[04-01-2022 feature-request]]`.

### Desired behavior
If I start typing `feature-request` it should suggest me `[[04-01-2022 feature-request|feature-request]]`.

Thanks in advance.

**Comment by tadashi-aikawa** [comment]
Hi, @almogtzabari. Thank you for your FR :)

It looks good to me. I'll implement it 👍

**Comment by tadashi-aikawa** [comment]
@almogtzabari 
I have released to [v4.1.0](https://github.com/tadashi-aikawa/obsidian-various-complements-plugin/releases/tag/4.1.0) 🚀

Please confirm whether it works as you expected.

**Comment by almogtzabari** [comment]
Works exactly how I expected!
Thank you very much!!
