### ISSUE TITLE
Feature Request: Add selected word to a custom dictionary

### ISSUE THREAD

**Issue by chrisgrieser** [tadashi-aikawa/obsidian-various-complements-plugin#67]
I heavily use the custom dictionaries and add words to them on a regular bases. Regularly switching to the note and back is quite inconvenient though, so I was thinking having an option to add a selected word quickly to a dictionary could be useful.

More concretely, I am thinking of a context menu item that first shows you a list of your custom dictionaries and and upon selection of a custom dictionary, automatically appends words to that custom dictionary note.

**Comment by tadashi-aikawa** [comment]
Thank you for your FR :) It looks good so I will implement it 👍

**Comment by tadashi-aikawa** [comment]
WIP
![image](https://user-images.githubusercontent.com/9500018/149295557-78854c4d-412f-41cb-84b6-427ab62c56ee.png)

**Comment by chrisgrieser** [comment]
💙

**Comment by tadashi-aikawa** [comment]
Hi, @chrisgrieser :)

I have updated beta version to [obsidian-various-complements-plugin-beta v5.0.0.beta1](https://github.com/tadashi-aikawa/obsidian-various-complements-plugin-beta/releases/tag/5.0.0.beta1) 🚀 

Please confirm whether it works as you expected. Probably, there are some bugs and points to be improved. It would be helpful to inform me on the thread of this issue for now. After that, I'll develop them little and little.

**Comment by chrisgrieser** [comment]
Fantastic, I tried it, and it already works well without any glitches I could notice. 🥳  seems to auto-reload after adding, checks whether the word is already in a dictionary, and inserts the correct column delimiter.

Add it to the context menu and it should be good to ship I guess?

The only to thing I'd probably consider to change is the use of emojis in the notifications, since it does not look great when you are using a font that does not display emojis well
![Screenshot 2022-01-13 13 29 11](https://user-images.githubusercontent.com/73286100/149330502-a138fba1-ad40-4cfe-b081-2d4b06288704.png)

**Comment by tadashi-aikawa** [comment]
Thank you for quick confirming! That was good 😄

> Add it to the context menu and it should be good to ship I guess?

OK. I'll add it like the command. (I couldn't notice it because I don't use context menu 😅 )

> it does not look great when you are using a font that does not display emojis well

Certainly. It is best if we could specify color of `Notice`(toaster), but...

**Comment by tadashi-aikawa** [comment]
Both looks of multi-lines and tabs make good 👁️ 

![image](https://user-images.githubusercontent.com/9500018/149354632-9d5ded1f-e6cd-4f7a-8b71-1001bfc5b83d.png)

**Comment by tadashi-aikawa** [comment]
Coming soon!

![image](https://user-images.githubusercontent.com/9500018/149431442-0d6b66c7-6f78-44cb-964e-6b068733eb1b.png)

**Comment by tadashi-aikawa** [comment]
Updated [obsidian-various-complements-plugin-beta v5.0.0.beta2](https://github.com/tadashi-aikawa/obsidian-various-complements-plugin-beta/releases/tag/5.0.0.beta2) 🚀

**Comment by tadashi-aikawa** [comment]
@chrisgrieser 
I have released to [v5.0.0](https://github.com/tadashi-aikawa/obsidian-various-complements-plugin/releases/tag/5.0.0) 🚀

Please confirm whether it works as you expected.

**Comment by chrisgrieser** [comment]
can confirm, works without any issue! thanks a lot 🥇
