### ISSUE TITLE
Setting multiple Location symbols is not supported？

### ISSUE THREAD

**Issue by zbqiang8** [tadashi-aikawa/obsidian-various-complements-plugin#70]
eg: /!/[/</CARET/>/]/(/</CARET/>/)
The cursor stays at the first <CARET> by default, jump to the second <CARET> by pressing the Tab key

**Comment by tadashi-aikawa** [comment]
Sorry, It doesn't, and I will not implement it.

Best regards.

**Comment by tadashi-aikawa** [comment]
Workaround

https://github.com/tadashi-aikawa/obsidian-various-complements-plugin/issues/25#issuecomment-997361792

**Comment by HaiNguyen007** [comment]
or use can you plugin Templater cursors <% tp.file.cursor(1) %>, <% tp.file.cursor(2) %>
