### ISSUE TITLE
help / documentation - CARET 

### ISSUE THREAD

**Issue by evezeyl** [tadashi-aikawa/obsidian-various-complements-plugin#71]
Hi,
I see that you have added the Caret location - and looked at the issue 
I was wondering if you could explain a bit better for creating the dictionary (formating) and how to configure

- in the various complement - I added <CARET> in the field
- in the dictionary I added: (tab separated) 
<mark class="pink"><CARET><\mark>	mark
This does not work
so I tried 
'<mark class="pink"><CARET><\mark>'	mark

none of that worked after reloading.
Maybe its still under development?

Thank you for this great plugin 
Eve

**Comment by tadashi-aikawa** [comment]
Hi, @evezeyl :)

Did you look https://github.com/tadashi-aikawa/obsidian-various-complements-plugin/releases/tag/3.4.0?

If you didn't, it supposes to help you. But, if you did, please let me know your settings by the `Copy plugin settings` command.

![image](https://user-images.githubusercontent.com/9500018/149152447-1f187252-dfd5-4bb2-943e-e58c8af1dac3.png)

**Comment by tadashi-aikawa** [comment]
Please see [⚙️Caret location symbol after complement \- Various Complements](https://tadashi-aikawa.github.io/docs-obsidian-various-complements-plugin/2.%20Options/2.4.%20Custom%20dictionary%20complement/%E2%9A%99%EF%B8%8FCaret%20location%20symbol%20after%20complement/) too

**Comment by tadashi-aikawa** [comment]
Let me close this issue because there has been no reply over two weeks :)
