### ISSUE TITLE
Uncaught (in promise) TypeError: Cannot read property 'nextKey' of undefined

### ISSUE THREAD

**Issue by arozehnal** [tadashi-aikawa/obsidian-various-complements-plugin#78]
Obsidian 0.13.23
OS Win10
complements-plugin 5.0.1

Plugin v.4 worked properly for me
after update to v.5.0.1 neither local file complement nor dictionary complement not working 

I see this
Uncaught (in promise) TypeError: Cannot read property 'nextKey' of undefined
    at AutoCompleteSuggest.registerKeymaps (eval at <anonymous> (app.js:1), <anonymous>:2307:90)
    at AutoCompleteSuggest.eval (eval at <anonymous> (app.js:1), <anonymous>:2298:18)
    at Generator.next (<anonymous>)
    at fulfilled (eval at <anonymous> (app.js:1), <anonymous>:23:58)
on console during Obsidian start.

**Comment by tadashi-aikawa** [comment]
Hi, @arozehnal.

Would you tell me your settings by [Copy plugin settings](https://tadashi-aikawa.github.io/docs-obsidian-various-complements-plugin/3.%20Commands/%F0%9F%8E%AECopy%20plugin%20settings/) command?

**Comment by arozehnal** [comment]
I'm very sorry... it was probably my fault.
First,  I had typo in custom dictionary path - I changed  it due the new features of plugin version 5.
I also tried reinstalling the plugin now.
Then the plugin works OK :-)

The issue can be closed.
