### ISSUE TITLE
Feature request: Internal link complement to open in a separate pane instead of a complement

### ISSUE THREAD

**Issue by kazdonkai** [tadashi-aikawa/obsidian-various-complements-plugin#79]
便利なプラグインをありがとうございます。
補完の候補が表示された時に、候補で表示されたノートの内容を見たいとか、タイトルを変更したいと思う事が結構あります。

そこで、何かのキーを押した時には(Shift+Returnとか、モバイルだったらダブル・タップとか)、補完して入力するのではなく、新しいペーンにノートを開くという補能は、付けられないでしょうか。

本来の使い方とは異なりますが、便利だと思うので要望させて頂きます。

**Comment by tadashi-aikawa** [comment]
@kazdonkai 
要望ありがとうございます。

プラグインのスコープから外れる機能な気もしましたが、ちょうどリファクタリングをしてsuggestionの元となるファイルを取得できるようにもなりましたので、検討してみます。

モバイルのダブルタップはおそらく厳しいと思います。( `Shift + Return` もObsidian Plugin APIでは提供されてはいないため、非公式の方法で実装しています )

**Comment by tadashi-aikawa** [comment]
@kazdonkai 
[v5.3.0](https://github.com/tadashi-aikawa/obsidian-various-complements-plugin/releases/tag/5.3.0)をリリースしました。ご確認ください。

**Comment by kazdonkai** [comment]
Macで試してみましたが、どのキーでも上手くいきました。
(モバイルは仕方無いですね)。
これで一層便利になりました。
対応ありがとうございます。
