### ISSUE TITLE
Feature request: Dictionary Filters

### ISSUE THREAD

**Issue by brimwats** [tadashi-aikawa/obsidian-various-complements-plugin#81]
Hello! I would like a way to filter the dictonary I am using (50k words) and make only words that are over 4 or 5 characters valid. I only see a way to filter triggers for the plugin in-editor but no filters on the dictionaries

**Comment by tadashi-aikawa** [comment]
Hi, @brimwats. Thank you for your FR :)

Would you tell me why [⚙️Min number of characters for trigger](https://tadashi-aikawa.github.io/docs-obsidian-various-complements-plugin/2.%20Options/2.1.%20Main/%E2%9A%99%EF%B8%8FMin%20number%20of%20characters%20for%20trigger/) doesn't satisfy a demand?

**Comment by brimwats** [comment]
The dictionary I use is [kpym/FrequencyDictionaries: Frequency dictionaries - one word per line simple text files](https://github.com/kpym/FrequencyDictionaries) because it is significantly more comprehensive than the default one you've added (I think). However, it does include words that are 3-5 letters long, but I don't want those to show up. Secondly, all "Min number of characters for a trigger" sets the min number of characters for a trigger of the app—it doesn't set a filter on the dictionary like what Completr (https://github.com/tth05/obsidian-completr) does.

**Comment by brimwats** [comment]
(on the reverse side, Completr doesn't set a threshold for trigger like you do—neither plugin will let users do both, and using them together causes conflict)

**Comment by tadashi-aikawa** [comment]
Thank you for your explanation. I have understood 👍

**Comment by brimwats** [comment]
thanks for asking!

**Comment by tadashi-aikawa** [comment]
@brimwats 
I have updated beta version to [obsidian-various-complements-plugin-beta v5.0.0-beta5](https://github.com/tadashi-aikawa/obsidian-various-complements-plugin-beta/releases/tag/5.1.0.beta5) 🚀 

If you use [BRAT](https://github.com/TfTHacker/obsidian42-brat), please confirm whether it works as you expected. 

> I am using (50k words) and make only words that are over 4 or 5 characters valid

Please set `.{4,}` or `.{5,}` to a `Regex pattern` option on `Custom dictionary complements`.

Note: This beta version includes many new updates, For details, please show [Releases](https://github.com/tadashi-aikawa/obsidian-various-complements-plugin-beta/releases).

**Comment by brimwats** [comment]
@tadashi-aikawa I'm sure it does! but getting errors from BRAT: 
![image](https://user-images.githubusercontent.com/73113656/153120419-2cbd3544-584e-4256-831d-90629327be62.png)

**Comment by brimwats** [comment]
oh wait I see I did it wrong

**Comment by tadashi-aikawa** [comment]
For your reference.

https://github.com/tadashi-aikawa/obsidian-various-complements-plugin/issues/73#issuecomment-1030617308

**Comment by brimwats** [comment]
Seems like this:  `.{4,}`
![image](https://user-images.githubusercontent.com/73113656/153120795-7c9050a7-5592-456b-b084-8651fb18b2b3.png)

Should not trigger on >3, but it does:
![image](https://user-images.githubusercontent.com/73113656/153120826-f66563bf-16da-48ca-916c-8875f8756e4a.png)

![image](https://user-images.githubusercontent.com/73113656/153120829-e7cc7d84-3efc-4d27-bea9-e499bdfbf151.png)

**Comment by brimwats** [comment]
Oh—I had to set the other setting (trigger on characters) again! It looks like it's working :D

**Comment by brimwats** [comment]
With the regex set to `.{5,}` and min number of chatacters for trigger set to `6` this triggers on organges, as would be expected! 

![image](https://user-images.githubusercontent.com/73113656/153120982-824c85e2-8053-46cb-946b-0ed0bffba590.png)

Thanks!

My only suggestion would be a slider for folks who don't know regex—but maybe my use case is advansed anyhow!

**Comment by tadashi-aikawa** [comment]
Thank you for your quick confirmation!

> My only suggestion would be a slider for folks who don't know regex—but maybe my use case is advanced anyhow!

I thought so, too, but this seems an advanced use case, as you said. Therefore I prefer to be highly customizable than usability for everyone :)

I will release it as official today or tomorrow 👍 

(Docs↓)
![image](https://user-images.githubusercontent.com/9500018/153121744-890219b6-db02-4fb4-b12e-4222d99a92a2.png)

**Comment by tadashi-aikawa** [comment]
(Btw. I notice that prefix icons are almost hidden in your theme... 😅 )

![](https://user-images.githubusercontent.com/73113656/153120982-824c85e2-8053-46cb-946b-0ed0bffba590.png)

**Comment by brimwats** [comment]
yeah I was wondering what those were! I'm on Minimal

**Comment by tadashi-aikawa** [comment]
Fixed at 5.1.0.beta6 👍

**Comment by tadashi-aikawa** [comment]
Released at v5.1.0 🚀 

https://github.com/tadashi-aikawa/obsidian-various-complements-plugin/releases/tag/5.1.0
