### ISSUE TITLE
Feature Suggestion: Complement Current *Folder*

### ISSUE THREAD

**Issue by chrisgrieser** [tadashi-aikawa/obsidian-various-complements-plugin#82]
Thanks yet again for the fantastic new Vault Complement!

Using the new features for a bit actually gave me an idea how this could be refined even further:
- the advantage of `current vault complement` is that it shows you suggestions from a bigger number of files
- the advantage of `current note complement` is that it shows you suggestions dynamically, e.g. not suggesting you technical terms, when you are in a note about cooking and vice versa.

I think one could combine both by implementing `current folder complement`, where dynamically only terms from notes in the current folder are suggested. For performance reasons, this should not reload automatically, but it also shouldn't reload, but reloading manually could actually be fine?

This could be very helpful for writers using the Longform plugin, where you split up a writing project into multiple notes (which are all located in one folder).

**Comment by tadashi-aikawa** [comment]
Hi, @chrisgrieser. Thanks for your fantastic suggestion :)

> I think one could combine both by implementing current folder complement, where dynamically only terms from notes in the current folder are suggested

I see. I ordinarily use different vaults in such a case, but that is an exciting idea and supposed useful for someone 👍

It depends on how many files we have in a directory; It seems acceptable to only reload when it changes the current directory. What do you think?

**Comment by chrisgrieser** [comment]
well, I would have about 12-15 notes with about 12 000 words in such a longform project (average length of a research paper), but I know that there are also people with much bigger projects.

Maybe make the automatic reloading simply a toggle?

**Comment by tadashi-aikawa** [comment]
Thank you for a reply :)

O.K. I'll add a new option `Include only files under current directory` in the `Current vault complement`. It will not take much time probably.

**Comment by tadashi-aikawa** [comment]
@chrisgrieser 
I have released [v5.4.0](https://github.com/tadashi-aikawa/obsidian-various-complements-plugin/releases/tag/5.4.0) 🚀  please confirm whether it works as you expected :)

**Comment by tadashi-aikawa** [comment]
Thank you for your quick confirming :)

> Could you maybe shorten the source path to the file name only? having the full file path makes it a bit much.

I see. I'll add options that decide what to show or hide completely. It would be helpful for me to create a new issue 🙏 

> I am not entirely sure, how exactly does the reloading work? Current file completions are automatically reload, while current vault & custom dictionaries have to be reloaded manually, is that correct?

Yes. You are generally correct. For details, please show the below pages.

- [Current file complement](https://tadashi-aikawa.github.io/docs-obsidian-various-complements-plugin/1.%20Features/Current%20file%20complement/#when-does-it-update-tokens)
- [Current vault complement](https://tadashi-aikawa.github.io/docs-obsidian-various-complements-plugin/1.%20Features/Current%20vault%20complement/#when-does-it-update-tokens)
- [Custom dictionary complement](https://tadashi-aikawa.github.io/docs-obsidian-various-complements-plugin/1.%20Features/Custom%20dictionary%20complement/#when-does-it-update-tokens)

And I want to implement auto-reload for the Current vault complement soon.

**Comment by chrisgrieser** [comment]
thanks, will do!
