### ISSUE TITLE
Status Bar items

### ISSUE THREAD

**Issue by menagerie198** [tadashi-aikawa/obsidian-various-complements-plugin#83]
Could you please add the ability to turn the new (v5.1.0) status bar items off/on? Individually or all ; they currently take up a lot of space and I find it a little 'noisy'. Many thanks

**Comment by tadashi-aikawa** [comment]
Thanks for creating issue 👍

**Comment by tadashi-aikawa** [comment]
Released as [v5.2.0](https://github.com/tadashi-aikawa/obsidian-various-complements-plugin/releases/tag/5.2.0) 🚀
