### ISSUE TITLE
FR: Shorten Source Information

### ISSUE THREAD

**Issue by chrisgrieser** [tadashi-aikawa/obsidian-various-complements-plugin#84]
> Could you maybe shorten the source path to the file name only? having the full file path makes it a bit much.
<img width="730" alt="Screenshot 2022-02-11 13 47 34" src="https://user-images.githubusercontent.com/73286100/153594300-c4a7ff63-72ca-43b0-8ab9-de650d90939f.png">

_Originally posted by @chrisgrieser in https://github.com/tadashi-aikawa/obsidian-various-complements-plugin/issues/82#issuecomment-1036181524_

**Comment by tadashi-aikawa** [comment]
@chrisgrieser 
I have released [v5.5.0](https://github.com/tadashi-aikawa/obsidian-various-complements-plugin/releases/tag/5.5.0) 🚀 

Maybe the default setting of a new option (`Short`) is what you like :)

**Comment by chrisgrieser** [comment]
works perfectly 💙
