### ISSUE TITLE
Question: What setting interfers with the word "I"?

### ISSUE THREAD

**Issue by brimwats** [tadashi-aikawa/obsidian-various-complements-plugin#88]
Hello!

I keep running into issues where the word "I" is getting replaced and I don't know what setting is causing it because the Minimum Trigger should be too high for this. Here is a gif of what I mean:
![Obsidian_9WmqjK7yNB](https://user-images.githubusercontent.com/73113656/153770844-c4967f02-7eb8-4977-b772-6d05ee0af42e.gif)

**Comment by tadashi-aikawa** [comment]
Hi, @brimwats. I have never seen such an issue.

- Does it reproduce when you disabled all plugins except for Various Complements?
- Does it reproduce in the clean vault?

Best regards.

**Comment by brimwats** [comment]
Does it reproduce when you disabled all plugins except for Various Complements?
Yes

Does it reproduce in the clean vault?
Yes

What the expected will you type ( Today I Intend is expected?)
Yes

**Comment by brimwats** [comment]
so long as the word Intends or something similar (Indigenous) is also in the file I think

**Comment by tadashi-aikawa** [comment]
@brimwats 
Don't you push a Space key with a Shift key? If so, you triggered [Predictable complement](https://tadashi-aikawa.github.io/docs-obsidian-various-complements-plugin/1.%20Features/Predictable%20complement/).

**Comment by brimwats** [comment]
yes! that's it! how do I turn off the predictable complement?

**Comment by brimwats** [comment]
I see toggles for the other sorts of complements: Current file complement, Current vault complement, Custom dictionary complement, Internal link complement, but don't see one for Predictable complement

**Comment by brimwats** [comment]
ah thank you!!
