### ISSUE TITLE
Is it possible to add a display item to the status bar to see at a glance whether it is a prefix or a partial?

### ISSUE THREAD

**Issue by tyf2018** [tadashi-aikawa/obsidian-various-complements-plugin#89]
I need to switch Match strategies frequently, but it's easy to forget whether the current one is prefix or partial. So is it possible to add a display item to the status bar to see at a glance whether it is a prefix or a partial?

Best Regards.

**Comment by tadashi-aikawa** [comment]
Hi, @tyf2018.

OK. I'll add the feature in the next release 👍

**Comment by tadashi-aikawa** [comment]
I'll release it on v5.6.0.

![2022-02-19](https://user-images.githubusercontent.com/9500018/154787199-21e655c1-0f41-4f28-bd09-f5d0ffdcd8e0.gif)

**Comment by tadashi-aikawa** [comment]
I have released [v5.6.0](https://github.com/tadashi-aikawa/obsidian-various-complements-plugin/releases/tag/5.6.0) 🚀
