### ISSUE TITLE
Exclude directories/tags

### ISSUE THREAD

**Issue by crazymedguy** [tadashi-aikawa/obsidian-various-complements-plugin#90]
Would it be possible to exclude certain folders or tags from resurfacing on various complements?

**Comment by tadashi-aikawa** [comment]
Hi, @crazymedguy :)

Is it the case of [Front matter complements]([Front matter complement](https://tadashi-aikawa.github.io/docs-obsidian-various-complements-plugin/1.%20Features/Front%20matter%20complement/)) that you want to exclude?

**Comment by crazymedguy** [comment]
Hello, nope I mean when generally typing in obsidian and getting partial matches. I have certain links that I'd like to exclude from being suggested, such as "event notes", or work-related or privacy-related stuff. I can't have them pop out while typing because it would obscure the results.

**Comment by tadashi-aikawa** [comment]
Thank you for your explanation :) I see. 

It would be possible to hide suggestions (not indexing) whose path matches specific patterns like a [Exclude prefix path patterns](https://tadashi-aikawa.github.io/docs-obsidian-various-complements-plugin/4.%20Options/4.5.%20Current%20vault%20complement/%E2%9A%99%EF%B8%8FExclude%20prefix%20path%20patterns/) option.

If you are OK, I'll add an option.

**Comment by tadashi-aikawa** [comment]
Ah.. but it doesn't show suggestions, so it doesn't need indexing.. 😅

**Comment by tadashi-aikawa** [comment]
Therefore, It seems best to add a `⚙️Exclude prefix path patterns` to the Internal link complements section and the Front matter complements section?

**Comment by crazymedguy** [comment]
Sounds like a good idea! So if it excludes the page, it isn't even indexed at all, is that what you mean? Sounds good. Maybe some support for inline metadata like in Dataview (`exclude:: true`) would be great too

**Comment by tadashi-aikawa** [comment]
> So if it excludes the page, it isn't even indexed at all, is that what you mean?

Yes. I'll try it first.

**Comment by tadashi-aikawa** [comment]
@crazymedguy 

I have released to [v5.9.0](https://github.com/tadashi-aikawa/obsidian-various-complements-plugin/releases/tag/5.9.0) 🚀

Please confirm whether it works as you expected.

**Comment by sohanglal** [comment]
Would it be possible to automatically pick up the directories the directories from `Settings > Files & Links > Excluded files`?
In Omnisearch the following is given: 
![image](https://user-images.githubusercontent.com/29398628/223951584-c0d9a3c2-a5b8-4e41-aae0-eb170f92bda5.png)

**Comment by tadashi-aikawa** [comment]
@sohanglal 
Duplicated https://github.com/tadashi-aikawa/obsidian-various-complements-plugin/issues/203
