### ISSUE TITLE
tab to cycle though suggestions not working?

### ISSUE THREAD

**Issue by dolphinpoint** [tadashi-aikawa/obsidian-various-complements-plugin#92]
Great plugin! I absolutely love it. 

However, the option to tab / shift tab to cycle through suggestions seems to have stopped working for me. I'm running macOS with the most recent app version 0.13.24. 

Symptoms: 
- fresh sandbox vault with only vanilla vc installed
- “additional cycle though suggestions keys” set to tab/shift tab
- suggestions shown in menu as expected
- press tab to cycle, text indents, rather than cycle though suggestions as expected

Do I have something wrong in how I'm using the plugin? Tab to cycle was working fine a few weeks ago.

**Comment by tadashi-aikawa** [comment]
Hi, @dolphinpoint. Thank you for your bug report :)

I could reproduce it. I'll fix it and release soon 👍

**Comment by tadashi-aikawa** [comment]
@dolphinpoint 
I have released [v5.6.1](https://github.com/tadashi-aikawa/obsidian-various-complements-plugin/releases/tag/5.6.1) 🚀

Please confirm whether it works as you expected.

**Comment by dolphinpoint** [comment]
The update works! Thanks!!
