### ISSUE TITLE
Is there a way to set "match strategy" separately for different types of complements

### ISSUE THREAD

**Issue by shui-dun** [tadashi-aikawa/obsidian-various-complements-plugin#93]
I want to set "prefix match strategy" as default match strategy but use "partial match strategy" for front matter complement. Is there a way to achieve it

**Comment by tadashi-aikawa** [comment]
Hi, @shui-dun :)

No. not yet. But I've always thought to need it.

I'll implement it 👍

**Comment by tadashi-aikawa** [comment]
@shui-dun 
I have released to [v5.8.0](https://github.com/tadashi-aikawa/obsidian-various-complements-plugin/releases/tag/5.8.0) 🚀

Please confirm whether it works as you expected.
