### ISSUE TITLE
[BUG] Space key doesn't work when holding down shift

### ISSUE THREAD

**Issue by sinewave** [tadashi-aikawa/obsidian-various-complements-plugin#94]
I've come across a weird bug that seems to be from this plugin which is that the spacebar doesn’t add a space when holding down shift.

I run into this quite often when creating headings e.g. 

1. Press and hold shift
2. Press #
3. Press spacebar
4. Press first letter of heading.

With this plugin enabled pressing space doesn’t work? 🤔

**Comment by tadashi-aikawa** [comment]
Hi, @sinewave :)

Please see https://github.com/tadashi-aikawa/obsidian-various-complements-plugin/issues/88#issuecomment-1038853234

**Comment by sinewave** [comment]
That was it, thx!
