### ISSUE TITLE
Suggest a portion of tags when triggered by a particular key

### ISSUE THREAD

**Issue by ooker777** [tadashi-aikawa/obsidian-various-complements-plugin#96]
Say if I press `cc`, then I will have suggestions for `category`, `subcategory`, `subsubcategory` only. If I type `dd` then I will have suggestions for `directory`, `subdirectory`, `subsubdirectory` only. Is that possible?

I think it's easy to implement via the dictionary

**Comment by ooker777** [comment]
Ah, I didn't think of using the same alias for different words

**Comment by tadashi-aikawa** [comment]
I want to close it if your problem has been resolved. If not, it would be helpful to tell me what doesn't make your issue resolved.

**Comment by ooker777** [comment]
Yeah it's resolved. I'm asking because I see that most other authors close
the issue too if it seems to resolved already

**Comment by tadashi-aikawa** [comment]
Good! I will close it.
