### ISSUE TITLE
Editing the doc gives 404

### ISSUE THREAD

**Issue by ooker777** [tadashi-aikawa/obsidian-various-complements-plugin#97]
I click on the edit button at the top of [Custom dictionary complement](https://tadashi-aikawa.github.io/docs-obsidian-various-complements-plugin/1.%20Features/Custom%20dictionary%20complement/ "Custom dictionary complement - Various Complements") to edit the requirement to a correct link, but it gives 404.

**Comment by tadashi-aikawa** [comment]
Thank for your report :)
